' Generated by TinyPG v1.3 available at www.codeproject.com

Imports System
Imports System.Collections.Generic
Imports System.Text.RegularExpressions
Imports System.Xml.Serialization


Namespace FEQL
#Region "Scanner"

    Partial Public Class Scanner
        Public Input As String
        Public StartPos As Integer = 0
        Public EndPos As Integer = 0
        Public CurrentLine As Integer
        Public CurrentColumn As Integer
        Public CurrentPosition As Integer
        Public Skipped As List(Of Token) ' tokens that were skipped
        Public Patterns As Dictionary(Of TokenType, Regex)

        Private LookAheadToken As Token
        Private Tokens As List(Of TokenType)
        Private SkipList As List(Of TokenType) ' tokens to be skipped

        Public Sub New()
            Dim regex As Regex
            Patterns = New Dictionary(Of TokenType, Regex)()
            Tokens = New List(Of TokenType)()
            LookAheadToken = Nothing
            Skipped = New List(Of Token)()

            SkipList = New List(Of TokenType)()
            SkipList.Add(TokenType.WHITESPACE)

            regex = new Regex("\!", RegexOptions.Compiled)
            Patterns.Add(TokenType.BANG, regex)
            Tokens.Add(TokenType.BANG)

            regex = new Regex("\(", RegexOptions.Compiled)
            Patterns.Add(TokenType.BROPEN, regex)
            Tokens.Add(TokenType.BROPEN)

            regex = new Regex("\)", RegexOptions.Compiled)
            Patterns.Add(TokenType.BRCLOSE, regex)
            Tokens.Add(TokenType.BRCLOSE)

            regex = new Regex("\^", RegexOptions.Compiled)
            Patterns.Add(TokenType.CARRET, regex)
            Tokens.Add(TokenType.CARRET)

            regex = new Regex("}", RegexOptions.Compiled)
            Patterns.Add(TokenType.CLOSEPARENTHESIS, regex)
            Tokens.Add(TokenType.CLOSEPARENTHESIS)

            regex = new Regex("]", RegexOptions.Compiled)
            Patterns.Add(TokenType.CLOSESQUAREBRACKET, regex)
            Tokens.Add(TokenType.CLOSESQUAREBRACKET)

            regex = new Regex(":", RegexOptions.Compiled)
            Patterns.Add(TokenType.COLON, regex)
            Tokens.Add(TokenType.COLON)

            regex = new Regex("(([a-zA-Z0-9][_a-z0-9]+)+[_|\s]?)+", RegexOptions.Compiled)
            Patterns.Add(TokenType.COLUMNNAMESTR, regex)
            Tokens.Add(TokenType.COLUMNNAMESTR)

            regex = new Regex(",", RegexOptions.Compiled)
            Patterns.Add(TokenType.COMMA, regex)
            Tokens.Add(TokenType.COMMA)

            regex = new Regex("&", RegexOptions.Compiled)
            Patterns.Add(TokenType.CONCATENATIONSYMBOL, regex)
            Tokens.Add(TokenType.CONCATENATIONSYMBOL)

            regex = new Regex("\}+", RegexOptions.Compiled)
            Patterns.Add(TokenType.CURLYBRACKETCLOSE, regex)
            Tokens.Add(TokenType.CURLYBRACKETCLOSE)

            regex = new Regex("\{+", RegexOptions.Compiled)
            Patterns.Add(TokenType.CURLYBRACKETOPEN, regex)
            Tokens.Add(TokenType.CURLYBRACKETOPEN)

            regex = new Regex("[aA-zZ]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.DATABASENAME, regex)
            Tokens.Add(TokenType.DATABASENAME)

            regex = new Regex("SQLite", RegexOptions.Compiled)
            Patterns.Add(TokenType.DATABASETYPE, regex)
            Tokens.Add(TokenType.DATABASETYPE)

            regex = new Regex("""", RegexOptions.Compiled)
            Patterns.Add(TokenType.DOUBLEQUOTE, regex)
            Tokens.Add(TokenType.DOUBLEQUOTE)

            regex = new Regex("^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})", RegexOptions.Compiled)
            Patterns.Add(TokenType.EMAILADDRESS, regex)
            Tokens.Add(TokenType.EMAILADDRESS)

            regex = new Regex("^$", RegexOptions.Compiled)
            Patterns.Add(TokenType.EOF, regex)
            Tokens.Add(TokenType.EOF)

            regex = new Regex("=", RegexOptions.Compiled)
            Patterns.Add(TokenType.EQUALS, regex)
            Tokens.Add(TokenType.EQUALS)

            regex = new Regex("[aA-zZ]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.FACTTYPENAME, regex)
            Tokens.Add(TokenType.FACTTYPENAME)

            regex = new Regex("^[a-zA-Z]:\\((?:[^/]*/)*)([aA-zZ0-9\-\.]*)", RegexOptions.Compiled)
            Patterns.Add(TokenType.FILELOCATIONNAME, regex)
            Tokens.Add(TokenType.FILELOCATIONNAME)

            regex = new Regex("([a-z]+[\s]?)+$", RegexOptions.Compiled)
            Patterns.Add(TokenType.FOLLOWINGREADINGTEXT, regex)
            Tokens.Add(TokenType.FOLLOWINGREADINGTEXT)

            regex = new Regex("^(?!\s)[aA-zZ0-9%\*\+\?\!&\.\( \-\:/]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.IDENTIFIER, regex)
            Tokens.Add(TokenType.IDENTIFIER)

            regex = new Regex("\#", RegexOptions.Compiled)
            Patterns.Add(TokenType.INCOMPARITOR, regex)
            Tokens.Add(TokenType.INCOMPARITOR)

            regex = new Regex("(([A-Z0-9]+[_a-z0-9]+[ |_]*)+[_|\s]?)+", RegexOptions.Compiled)
            Patterns.Add(TokenType.INDIVIDUALNAME, regex)
            Tokens.Add(TokenType.INDIVIDUALNAME)

            regex = new Regex("~", RegexOptions.Compiled)
            Patterns.Add(TokenType.LIKECOMPARITOR, regex)
            Tokens.Add(TokenType.LIKECOMPARITOR)

            regex = new Regex("<=|<|=|>=|>", RegexOptions.Compiled)
            Patterns.Add(TokenType.MATHFUNCTION, regex)
            Tokens.Add(TokenType.MATHFUNCTION)

            regex = new Regex("[aA-zZ]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.MODELNAME, regex)
            Tokens.Add(TokenType.MODELNAME)

            regex = new Regex("(([A-Z0-9]+[_a-z\-0-9]+[ |_]*)+[_|\s]?)+", RegexOptions.Compiled)
            Patterns.Add(TokenType.MODELELEMENTNAME, regex)
            Tokens.Add(TokenType.MODELELEMENTNAME)

            regex = new Regex("([0-9])+", RegexOptions.Compiled)
            Patterns.Add(TokenType.MODELELEMENTSUFFIX, regex)
            Tokens.Add(TokenType.MODELELEMENTSUFFIX)

            regex = new Regex("[aA-zZ0-9\-]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.MODELID, regex)
            Tokens.Add(TokenType.MODELID)

            regex = new Regex("[0-9]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.NUMBER, regex)
            Tokens.Add(TokenType.NUMBER)

            regex = new Regex("[aA-zZ0-9\s\-]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.PAGENAME, regex)
            Tokens.Add(TokenType.PAGENAME)

            regex = new Regex("{", RegexOptions.Compiled)
            Patterns.Add(TokenType.OPENPARENTHESIS, regex)
            Tokens.Add(TokenType.OPENPARENTHESIS)

            regex = new Regex("\[", RegexOptions.Compiled)
            Patterns.Add(TokenType.OPENSQUAREBRACKET, regex)
            Tokens.Add(TokenType.OPENSQUAREBRACKET)

            regex = new Regex("\.", RegexOptions.Compiled)
            Patterns.Add(TokenType.PERIOD, regex)
            Tokens.Add(TokenType.PERIOD)

            regex = new Regex("[a-z]+\-", RegexOptions.Compiled)
            Patterns.Add(TokenType.PREBOUNDREADINGTEXT, regex)
            Tokens.Add(TokenType.PREBOUNDREADINGTEXT)

            regex = new Regex("\-[a-z]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.POSTBOUNDREADINGTEXT, regex)
            Tokens.Add(TokenType.POSTBOUNDREADINGTEXT)

            regex = new Regex("(?!([a-z]+\-))(?!([a-z\s]+$)^$?)([a-z]+[^\-])", RegexOptions.Compiled)
            Patterns.Add(TokenType.PREDICATE, regex)
            Tokens.Add(TokenType.PREDICATE)

            regex = new Regex("[\s]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.PREDICATESPACE, regex)
            Tokens.Add(TokenType.PREDICATESPACE)

            regex = new Regex("(?:').*(?:')", RegexOptions.Compiled)
            Patterns.Add(TokenType.QUOTEDSTRING, regex)
            Tokens.Add(TokenType.QUOTEDSTRING)

            regex = new Regex("[aA-zZ]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.REFERENCEMODE, regex)
            Tokens.Add(TokenType.REFERENCEMODE)

            regex = new Regex("[a-z]+\-?", RegexOptions.Compiled)
            Patterns.Add(TokenType.ROLENAME, regex)
            Tokens.Add(TokenType.ROLENAME)

            regex = new Regex(";", RegexOptions.Compiled)
            Patterns.Add(TokenType.SEMICOLON, regex)
            Tokens.Add(TokenType.SEMICOLON)

            regex = new Regex("'", RegexOptions.Compiled)
            Patterns.Add(TokenType.SINGLEQUOTE, regex)
            Tokens.Add(TokenType.SINGLEQUOTE)

            regex = new Regex("\s", RegexOptions.Compiled)
            Patterns.Add(TokenType.SPACE, regex)
            Tokens.Add(TokenType.SPACE)

            regex = new Regex("\*", RegexOptions.Compiled)
            Patterns.Add(TokenType.STAR, regex)
            Tokens.Add(TokenType.STAR)

            regex = new Regex("[aA-zZ0-9]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.USERTABLENAME, regex)
            Tokens.Add(TokenType.USERTABLENAME)

            regex = new Regex("[aA-zZ0-9]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.WHERECLAUSECOLUMNNAMESTR, regex)
            Tokens.Add(TokenType.WHERECLAUSECOLUMNNAMESTR)

            regex = new Regex("\(", RegexOptions.Compiled)
            Patterns.Add(TokenType.WHICHCLAUSEBROPEN, regex)
            Tokens.Add(TokenType.WHICHCLAUSEBROPEN)

            regex = new Regex("\)", RegexOptions.Compiled)
            Patterns.Add(TokenType.WHICHCLAUSEBRCLOSE, regex)
            Tokens.Add(TokenType.WHICHCLAUSEBRCLOSE)

            regex = new Regex("[aA-zZ0-9\-\s+\#\*\?]*", RegexOptions.Compiled)
            Patterns.Add(TokenType.VALUE, regex)
            Tokens.Add(TokenType.VALUE)

            regex = new Regex("A\s|A$", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDA, regex)
            Tokens.Add(TokenType.KEYWDA)

            regex = new Regex("ADD", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDADD, regex)
            Tokens.Add(TokenType.KEYWDADD)

            regex = new Regex("ADD FACT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDADDFACT, regex)
            Tokens.Add(TokenType.KEYWDADDFACT)

            regex = new Regex("ADD FACTTYPE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDADDFACTTYPE, regex)
            Tokens.Add(TokenType.KEYWDADDFACTTYPE)

            regex = new Regex("ADD OBJECT TYPES RELATED TO", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDADDOBJECTTYPESRELATEDTO, regex)
            Tokens.Add(TokenType.KEYWDADDOBJECTTYPESRELATEDTO)

            regex = new Regex("ADD OBJECT TYPE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDADDOBJECTTYPE, regex)
            Tokens.Add(TokenType.KEYWDADDOBJECTTYPE)

            regex = new Regex("AN\s|AN$", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDAN, regex)
            Tokens.Add(TokenType.KEYWDAN)

            regex = new Regex("AND", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDAND, regex)
            Tokens.Add(TokenType.KEYWDAND)

            regex = new Regex("ANY FACT TYPE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDANYFACTTYPE, regex)
            Tokens.Add(TokenType.KEYWDANYFACTTYPE)

            regex = new Regex("ASC", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDASC, regex)
            Tokens.Add(TokenType.KEYWDASC)

            regex = new Regex("ASSERT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDASSERT, regex)
            Tokens.Add(TokenType.KEYWDASSERT)

            regex = new Regex("AS\s|AS$", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDAS, regex)
            Tokens.Add(TokenType.KEYWDAS)

            regex = new Regex("AT MOST ONE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDATMOSTONE, regex)
            Tokens.Add(TokenType.KEYWDATMOSTONE)

            regex = new Regex("AVG", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDAVG, regex)
            Tokens.Add(TokenType.KEYWDAVG)

            regex = new Regex("BUT NOT BOTH", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDBUTNOTBOTH, regex)
            Tokens.Add(TokenType.KEYWDBUTNOTBOTH)

            regex = new Regex("CIRCULAR", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDCIRCULAR, regex)
            Tokens.Add(TokenType.KEYWDCIRCULAR)

            regex = new Regex("COMBINATION", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDCOMBINATION, regex)
            Tokens.Add(TokenType.KEYWDCOMBINATION)

            regex = new Regex("COUNT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDCOUNT, regex)
            Tokens.Add(TokenType.KEYWDCOUNT)

            regex = new Regex("COUNT\(\*\)", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDCOUNTSTAR, regex)
            Tokens.Add(TokenType.KEYWDCOUNTSTAR)

            regex = new Regex("CREATE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDCREATE, regex)
            Tokens.Add(TokenType.KEYWDCREATE)

            regex = new Regex("CREATE CONCEPT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDCREATECONCEPT, regex)
            Tokens.Add(TokenType.KEYWDCREATECONCEPT)

            regex = new Regex("CONNECT TO MODEL", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDCONNECTTOMODEL, regex)
            Tokens.Add(TokenType.KEYWDCONNECTTOMODEL)

            regex = new Regex("DATABASE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATABASE, regex)
            Tokens.Add(TokenType.KEYWDDATABASE)

            regex = new Regex("DATE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATE, regex)
            Tokens.Add(TokenType.KEYWDDATE)

            regex = new Regex("DESC", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDESC, regex)
            Tokens.Add(TokenType.KEYWDDESC)

            regex = new Regex("CREATE ENTITYTTYPE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDCREATEENTITYTYPE, regex)
            Tokens.Add(TokenType.KEYWDCREATEENTITYTYPE)

            regex = new Regex("CREATE FACTTYPE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDCREATEFACTTYPE, regex)
            Tokens.Add(TokenType.KEYWDCREATEFACTTYPE)

            regex = new Regex("CREATE MODEL", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDCREATEMODEL, regex)
            Tokens.Add(TokenType.KEYWDCREATEMODEL)

            regex = new Regex("CREATE VALUETYPE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDCREATEVALUETYPE, regex)
            Tokens.Add(TokenType.KEYWDCREATEVALUETYPE)

            regex = new Regex("LogicalTrueFalse", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPELOGICALTRUEFALSE, regex)
            Tokens.Add(TokenType.KEYWDDATATYPELOGICALTRUEFALSE)

            regex = new Regex("LogicalYesNo", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPELOGICALYESNO, regex)
            Tokens.Add(TokenType.KEYWDDATATYPELOGICALYESNO)

            regex = new Regex("AutoCounter", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEAUTOCOUNTER, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEAUTOCOUNTER)

            regex = new Regex("Decimal", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEDECIMAL, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEDECIMAL)

            regex = new Regex("FloatCustomPrecision", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEFLOATCUSTOMPRECISION, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEFLOATCUSTOMPRECISION)

            regex = new Regex("FloatDoublePrecision", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEFLOATDOUBLEPRECISION, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEFLOATDOUBLEPRECISION)

            regex = new Regex("FloatSinglePrecistion", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEFLOATSINGLEPRECISION, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEFLOATSINGLEPRECISION)

            regex = new Regex("Money", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEMONEY, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEMONEY)

            regex = new Regex("SignedBigInteger", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPESIGNEDBIGINTEGER, regex)
            Tokens.Add(TokenType.KEYWDDATATYPESIGNEDBIGINTEGER)

            regex = new Regex("SignedInteger", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPESIGNEDINTEGER, regex)
            Tokens.Add(TokenType.KEYWDDATATYPESIGNEDINTEGER)

            regex = new Regex("SignedSmallInteger", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPESIGNEDSMALLINTEGER, regex)
            Tokens.Add(TokenType.KEYWDDATATYPESIGNEDSMALLINTEGER)

            regex = new Regex("UnsignedBigInteger", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEUNSIGNEDBIGINTEGER, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEUNSIGNEDBIGINTEGER)

            regex = new Regex("UnsignedInteger", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEUNSIGNEDINTEGER, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEUNSIGNEDINTEGER)

            regex = new Regex("UnsignedSmallInteger", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEUNSIGNEDSMALLINTEGER, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEUNSIGNEDSMALLINTEGER)

            regex = new Regex("UnsignedTinyInteger", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEUNSIGNEDTINYINTEGER, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEUNSIGNEDTINYINTEGER)

            regex = new Regex("ObjectID", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEOBJECTID, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEOBJECTID)

            regex = new Regex("RowID", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEROWID, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEROWID)

            regex = new Regex("RawDataFixedLength", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPERAWDATAFIXEDLENGTH, regex)
            Tokens.Add(TokenType.KEYWDDATATYPERAWDATAFIXEDLENGTH)

            regex = new Regex("RawDataLargeLength", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPERAWDATALARGELENGTH, regex)
            Tokens.Add(TokenType.KEYWDDATATYPERAWDATALARGELENGTH)

            regex = new Regex("RawDataOLEObject", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPERAWDATAOLEOBJECT, regex)
            Tokens.Add(TokenType.KEYWDDATATYPERAWDATAOLEOBJECT)

            regex = new Regex("RawDataPicture", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPERAWDATA, regex)
            Tokens.Add(TokenType.KEYWDDATATYPERAWDATA)

            regex = new Regex("VariableLength", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPERAWDATAVARIABLELENGTH, regex)
            Tokens.Add(TokenType.KEYWDDATATYPERAWDATAVARIABLELENGTH)

            regex = new Regex("AutoTimestamp", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEAUTOTIMESTAMP, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEAUTOTIMESTAMP)

            regex = new Regex("Date", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEDATE, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEDATE)

            regex = new Regex("DateTime", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEDATETIME, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEDATETIME)

            regex = new Regex("Time", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPETIME, regex)
            Tokens.Add(TokenType.KEYWDDATATYPETIME)

            regex = new Regex("StringFixedLength", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPESTRINGFIXEDLENGTH, regex)
            Tokens.Add(TokenType.KEYWDDATATYPESTRINGFIXEDLENGTH)

            regex = new Regex("StringLargeLength", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPESTRINGLARGELENGTH, regex)
            Tokens.Add(TokenType.KEYWDDATATYPESTRINGLARGELENGTH)

            regex = new Regex("StringVariableLength", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPESTRINGVARIABLELENGTH, regex)
            Tokens.Add(TokenType.KEYWDDATATYPESTRINGVARIABLELENGTH)

            regex = new Regex("TextFixedLength", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPETEXTFIXEDLENGTH, regex)
            Tokens.Add(TokenType.KEYWDDATATYPETEXTFIXEDLENGTH)

            regex = new Regex("TextLargeLength", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPETEXTLARGELENGTH, regex)
            Tokens.Add(TokenType.KEYWDDATATYPETEXTLARGELENGTH)

            regex = new Regex("TextVariableLength", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPETEXTVARIABLELENGTH, regex)
            Tokens.Add(TokenType.KEYWDDATATYPETEXTVARIABLELENGTH)

            regex = new Regex("DELETE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDELETE, regex)
            Tokens.Add(TokenType.KEYWDDELETE)

            regex = new Regex("DELETE ALL", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDELETEALL, regex)
            Tokens.Add(TokenType.KEYWDDELETEALL)

            regex = new Regex("DELETE FACT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDELETEFACT, regex)
            Tokens.Add(TokenType.KEYWDDELETEFACT)

            regex = new Regex("DESCRIBE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDESCRIBE, regex)
            Tokens.Add(TokenType.KEYWDDESCRIBE)

            regex = new Regex("DID", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDID, regex)
            Tokens.Add(TokenType.KEYWDDID)

            regex = new Regex("DISTINCT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDISTINCT, regex)
            Tokens.Add(TokenType.KEYWDDISTINCT)

            regex = new Regex("DOES", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDOES, regex)
            Tokens.Add(TokenType.KEYWDDOES)

            regex = new Regex("EACH", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDEACH, regex)
            Tokens.Add(TokenType.KEYWDEACH)

            regex = new Regex("EITHER", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDEITHER, regex)
            Tokens.Add(TokenType.KEYWDEITHER)

            regex = new Regex("ENTITY", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDENTITY, regex)
            Tokens.Add(TokenType.KEYWDENTITY)

            regex = new Regex("ENTITYTYPE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDENTITYTYPE, regex)
            Tokens.Add(TokenType.KEYWDENTITYTYPE)

            regex = new Regex("ENTITYTYPES", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDENTITYTYPES, regex)
            Tokens.Add(TokenType.KEYWDENTITYTYPES)

            regex = new Regex("ENUMERATE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDENUMERATE, regex)
            Tokens.Add(TokenType.KEYWDENUMERATE)

            regex = new Regex("EXISTS", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDEXISTS, regex)
            Tokens.Add(TokenType.KEYWDEXISTS)

            regex = new Regex("FACT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDFACT, regex)
            Tokens.Add(TokenType.KEYWDFACT)

            regex = new Regex("FACTTYPE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDFACTTYPE, regex)
            Tokens.Add(TokenType.KEYWDFACTTYPE)

            regex = new Regex("FACTTYPES", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDFACTTYPES, regex)
            Tokens.Add(TokenType.KEYWDFACTTYPES)

            regex = new Regex("FOR", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDFOR, regex)
            Tokens.Add(TokenType.KEYWDFOR)

            regex = new Regex("FOR EACH", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDFOREACH, regex)
            Tokens.Add(TokenType.KEYWDFOREACH)

            regex = new Regex("FROM", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDFROM, regex)
            Tokens.Add(TokenType.KEYWDFROM)

            regex = new Regex("GET", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDGET, regex)
            Tokens.Add(TokenType.KEYWDGET)

            regex = new Regex("GROUP BY", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDGROUPBY, regex)
            Tokens.Add(TokenType.KEYWDGROUPBY)

            regex = new Regex("HAVING", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDHAVING, regex)
            Tokens.Add(TokenType.KEYWDHAVING)

            regex = new Regex("IF AND ONLY IF", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDIFANDONLYIF, regex)
            Tokens.Add(TokenType.KEYWDIFANDONLYIF)

            regex = new Regex("IN", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDIN, regex)
            Tokens.Add(TokenType.KEYWDIN)

            regex = new Regex("INSERT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDINSERT, regex)
            Tokens.Add(TokenType.KEYWDINSERT)

            regex = new Regex("INTO", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDINTO, regex)
            Tokens.Add(TokenType.KEYWDINTO)

            regex = new Regex("IS", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDIS, regex)
            Tokens.Add(TokenType.KEYWDIS)

            regex = new Regex("IS A", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDISA, regex)
            Tokens.Add(TokenType.KEYWDISA)

            regex = new Regex("IS A KIND OF", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDISAKINDOF, regex)
            Tokens.Add(TokenType.KEYWDISAKINDOF)

            regex = new Regex("IS A VALUE TYPE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDISAVALUETYPE, regex)
            Tokens.Add(TokenType.KEYWDISAVALUETYPE)

            regex = new Regex("IS IDENTIFIED BY ITS", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDISIDENTIFIEDBYITS, regex)
            Tokens.Add(TokenType.KEYWDISIDENTIFIEDBYITS)

            regex = new Regex("IS NOT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDISNOT, regex)
            Tokens.Add(TokenType.KEYWDISNOT)

            regex = new Regex("IS WHERE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDISWHERE, regex)
            Tokens.Add(TokenType.KEYWDISWHERE)

            regex = new Regex("IS WRITTEN AS", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDISWRITTENAS, regex)
            Tokens.Add(TokenType.KEYWDISWRITTENAS)

            regex = new Regex("IT IS MANDATORY THAT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDITISMANDATORYTHAT, regex)
            Tokens.Add(TokenType.KEYWDITISMANDATORYTHAT)

            regex = new Regex("JOINING", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDJOINING, regex)
            Tokens.Add(TokenType.KEYWDJOINING)

            regex = new Regex("INDEX", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDINDEX, regex)
            Tokens.Add(TokenType.KEYWDINDEX)

            regex = new Regex("LANGUAGE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDLANGUAGE, regex)
            Tokens.Add(TokenType.KEYWDLANGUAGE)

            regex = new Regex("DFD", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDLANGUAGEDFD, regex)
            Tokens.Add(TokenType.KEYWDLANGUAGEDFD)

            regex = new Regex("ERD", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDLANGUAGEERD, regex)
            Tokens.Add(TokenType.KEYWDLANGUAGEERD)

            regex = new Regex("ETD", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDLANGUAGEETD, regex)
            Tokens.Add(TokenType.KEYWDLANGUAGEETD)

            regex = new Regex("ORM", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDLANGUAGEORM, regex)
            Tokens.Add(TokenType.KEYWDLANGUAGEORM)

            regex = new Regex("STD", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDLANGUAGESTD, regex)
            Tokens.Add(TokenType.KEYWDLANGUAGESTD)

            regex = new Regex("UCD", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDLANGUAGEUCD, regex)
            Tokens.Add(TokenType.KEYWDLANGUAGEUCD)

            regex = new Regex("LOCATION", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDLOCATION, regex)
            Tokens.Add(TokenType.KEYWDLOCATION)

            regex = new Regex("LIST", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDLIST, regex)
            Tokens.Add(TokenType.KEYWDLIST)

            regex = new Regex("MAX", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDMAX, regex)
            Tokens.Add(TokenType.KEYWDMAX)

            regex = new Regex("MATCH", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDMATCH, regex)
            Tokens.Add(TokenType.KEYWDMATCH)

            regex = new Regex("MIN", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDMIN, regex)
            Tokens.Add(TokenType.KEYWDMIN)

            regex = new Regex("MODEL", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDMODEL, regex)
            Tokens.Add(TokenType.KEYWDMODEL)

            regex = new Regex("MONTH", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDMONTH, regex)
            Tokens.Add(TokenType.KEYWDMONTH)

            regex = new Regex("MODELNOTES", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDMODELNOTES, regex)
            Tokens.Add(TokenType.KEYWDMODELNOTES)

            regex = new Regex("MODEL.DICTIONARY", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDMODELDICTIONARY, regex)
            Tokens.Add(TokenType.KEYWDMODELDICTIONARY)

            regex = new Regex("NO", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDNO, regex)
            Tokens.Add(TokenType.KEYWDNO)

            regex = new Regex("", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDNULL, regex)
            Tokens.Add(TokenType.KEYWDNULL)

            regex = new Regex("OBJECT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDOBJECT, regex)
            Tokens.Add(TokenType.KEYWDOBJECT)

            regex = new Regex("OCCURS AT LEAST ONE TIME IN EITHER", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDOCCURSATLEASTONETIME, regex)
            Tokens.Add(TokenType.KEYWDOCCURSATLEASTONETIME)

            regex = new Regex("OCCURS AT LEAST ONE TIME IN EACH OF", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDOCCURSATLEASTONETIMEINEACHOF, regex)
            Tokens.Add(TokenType.KEYWDOCCURSATLEASTONETIMEINEACHOF)

            regex = new Regex("OF", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDOF, regex)
            Tokens.Add(TokenType.KEYWDOF)

            regex = new Regex("ON", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDON, regex)
            Tokens.Add(TokenType.KEYWDON)

            regex = new Regex("ONE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDONE, regex)
            Tokens.Add(TokenType.KEYWDONE)

            regex = new Regex("ON PAGE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDONPAGE, regex)
            Tokens.Add(TokenType.KEYWDONPAGE)

            regex = new Regex("OPEN", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDOPEN, regex)
            Tokens.Add(TokenType.KEYWDOPEN)

            regex = new Regex("OR", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDOR, regex)
            Tokens.Add(TokenType.KEYWDOR)

            regex = new Regex("ORDER BY", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDORDERBY, regex)
            Tokens.Add(TokenType.KEYWDORDERBY)

            regex = new Regex("PAGE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDPAGE, regex)
            Tokens.Add(TokenType.KEYWDPAGE)

            regex = new Regex("PREDICATE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDPREDICATE, regex)
            Tokens.Add(TokenType.KEYWDPREDICATE)

            regex = new Regex("RETURN", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDRETURN, regex)
            Tokens.Add(TokenType.KEYWDRETURN)

            regex = new Regex("ROLE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDROLE, regex)
            Tokens.Add(TokenType.KEYWDROLE)

            regex = new Regex("SELECT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDSELECT, regex)
            Tokens.Add(TokenType.KEYWDSELECT)

            regex = new Regex("RESTRICTED TO", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDRESTRICTEDTO, regex)
            Tokens.Add(TokenType.KEYWDRESTRICTEDTO)

            regex = new Regex("ROLECONSTRAINTS", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDROLECONSTRAINTS, regex)
            Tokens.Add(TokenType.KEYWDROLECONSTRAINTS)

            regex = new Regex("SET", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDSET, regex)
            Tokens.Add(TokenType.KEYWDSET)

            regex = new Regex("SHORTEST PATH", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDSHORTESTPATH, regex)
            Tokens.Add(TokenType.KEYWDSHORTESTPATH)

            regex = new Regex("SHOW", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDSHOW, regex)
            Tokens.Add(TokenType.KEYWDSHOW)

            regex = new Regex("SHOW ME", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDSHOWME, regex)
            Tokens.Add(TokenType.KEYWDSHOWME)

            regex = new Regex("STAND ALONE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDSTANDALONE, regex)
            Tokens.Add(TokenType.KEYWDSTANDALONE)

            regex = new Regex("SUM", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDSUM, regex)
            Tokens.Add(TokenType.KEYWDSUM)

            regex = new Regex("SUPERTYPE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDSUPERTYPE, regex)
            Tokens.Add(TokenType.KEYWDSUPERTYPE)

            regex = new Regex("TIME", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDTIME, regex)
            Tokens.Add(TokenType.KEYWDTIME)

            regex = new Regex("THAT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDTHAT, regex)
            Tokens.Add(TokenType.KEYWDTHAT)

            regex = new Regex("TO", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDTO, regex)
            Tokens.Add(TokenType.KEYWDTO)

            regex = new Regex("TODAY", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDTODAY, regex)
            Tokens.Add(TokenType.KEYWDTODAY)

            regex = new Regex("TOLOWER", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDTOLOWER, regex)
            Tokens.Add(TokenType.KEYWDTOLOWER)

            regex = new Regex("TOUPPER", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDTOUPPER, regex)
            Tokens.Add(TokenType.KEYWDTOUPPER)

            regex = new Regex("TO PAGE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDTOPAGE, regex)
            Tokens.Add(TokenType.KEYWDTOPAGE)

            regex = new Regex("TYPE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDTYPE, regex)
            Tokens.Add(TokenType.KEYWDTYPE)

            regex = new Regex("UPDATE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDUPDATE, regex)
            Tokens.Add(TokenType.KEYWDUPDATE)

            regex = new Regex("VALUES", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDVALUES, regex)
            Tokens.Add(TokenType.KEYWDVALUES)

            regex = new Regex("VALUETYPE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDVALUETYPE, regex)
            Tokens.Add(TokenType.KEYWDVALUETYPE)

            regex = new Regex("VALUETYPES", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDVALUETYPES, regex)
            Tokens.Add(TokenType.KEYWDVALUETYPES)

            regex = new Regex("WHEN", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDWHEN, regex)
            Tokens.Add(TokenType.KEYWDWHEN)

            regex = new Regex("WHERE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDWHERE, regex)
            Tokens.Add(TokenType.KEYWDWHERE)

            regex = new Regex("WITH", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDWITH, regex)
            Tokens.Add(TokenType.KEYWDWITH)

            regex = new Regex("WHAT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDWHAT, regex)
            Tokens.Add(TokenType.KEYWDWHAT)

            regex = new Regex("WHERE ALSO", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDWHEREALSO, regex)
            Tokens.Add(TokenType.KEYWDWHEREALSO)

            regex = new Regex("WHICH", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDWHICH, regex)
            Tokens.Add(TokenType.KEYWDWHICH)

            regex = new Regex("WHO", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDWHO, regex)
            Tokens.Add(TokenType.KEYWDWHO)

            regex = new Regex("WRITTEN AS", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDWRITTENAS, regex)
            Tokens.Add(TokenType.KEYWDWRITTENAS)

            regex = new Regex("YEAR", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDYEAR, regex)
            Tokens.Add(TokenType.KEYWDYEAR)

            regex = new Regex("\+", RegexOptions.Compiled)
            Patterns.Add(TokenType.PLUS, regex)
            Tokens.Add(TokenType.PLUS)

            regex = new Regex("-", RegexOptions.Compiled)
            Patterns.Add(TokenType.MINUS, regex)
            Tokens.Add(TokenType.MINUS)

            regex = new Regex("/", RegexOptions.Compiled)
            Patterns.Add(TokenType.DIVIDE, regex)
            Tokens.Add(TokenType.DIVIDE)

            regex = new Regex("\*", RegexOptions.Compiled)
            Patterns.Add(TokenType.TIMES, regex)
            Tokens.Add(TokenType.TIMES)

            regex = new Regex("(\+|-|/|\*)", RegexOptions.Compiled)
            Patterns.Add(TokenType.EXPRESSIONSYMBOL, regex)
            Tokens.Add(TokenType.EXPRESSIONSYMBOL)

            regex = new Regex("<", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDLESSTHAN, regex)
            Tokens.Add(TokenType.KEYWDLESSTHAN)

            regex = new Regex(">", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDGREATERTHAN, regex)
            Tokens.Add(TokenType.KEYWDGREATERTHAN)

            regex = new Regex("\s+", RegexOptions.Compiled)
            Patterns.Add(TokenType.WHITESPACE, regex)
            Tokens.Add(TokenType.WHITESPACE)



        End Sub

        Public Sub Init(ByVal input As String)
            Me.Input = input
            StartPos = 0
            EndPos = 0
            CurrentLine = 0
            CurrentColumn = 0
            CurrentPosition = 0
            Skipped = New List(Of Token)()
            LookAheadToken = Nothing
        End Sub

        Public Function GetToken(ByVal type As TokenType) As Token
            Dim t As New Token(Me.StartPos, Me.EndPos)
            t.Type = type
            Return t
        End Function

        ''' <summary>
        ''' executes a lookahead of the next token
        ''' and will advance the scan on the input string
        ''' </summary>
        ''' <returns></returns>
        Public Function Scan(ByVal ParamArray expectedtokens As TokenType()) As Token
            Dim tok As Token = LookAhead(expectedtokens)
            ' temporarely retrieve the lookahead
            LookAheadToken = Nothing
            ' reset lookahead token, so scanning will continue
            StartPos = tok.EndPos
            EndPos = tok.EndPos
            ' set the tokenizer to the new scan position
            Return tok
        End Function

        ''' <summary>
        ''' returns token with longest best match
        ''' </summary>
        ''' <returns></returns>
        Public Function LookAhead(ByVal ParamArray expectedtokens As TokenType()) As Token
            Dim i As Integer
            Dim start As Integer = StartPos
            Dim tok As Token = Nothing
            Dim scantokens As List(Of TokenType)

            ' this prevents double scanning and matching
            ' increased performance
            If LookAheadToken IsNot Nothing AndAlso LookAheadToken.Type <> TokenType._UNDETERMINED_ AndAlso LookAheadToken.Type <> TokenType._NONE_ Then
                Return LookAheadToken
            End If

            If expectedtokens.Length = 0 Then
                scantokens = Tokens
            Else
                scantokens = New List(Of TokenType)(expectedtokens)
                scantokens.AddRange(SkipList)
            End If

            Do
                Dim len As Integer = -1
                Dim index As TokenType = Integer.MaxValue
                Dim m_input As String

                If start > Input.Length Then
                    tok = New Token(start, start)
                    tok.Type = TokenType._UNDETERMINED_
                    Exit Do
                End If

                m_input = Input.Substring(start)

                tok = New Token(start, EndPos)


                For i = 0 To scantokens.Count - 1
                    Dim r As Regex = Patterns(scantokens(i))
                    Dim m As Match = r.Match(m_input)
                    If m.Success AndAlso m.Index = 0 AndAlso ((m.Length > len) OrElse (scantokens(i) < index AndAlso m.Length = len)) Then
                        len = m.Length
                        index = scantokens(i)
                        Exit For
                    End If
                Next i

                If index >= 0 AndAlso len >= 0 Then
                    tok.EndPos = start + len
                    If tok.StartPos + len <= Input.Length Then
                        tok.Text = Input.Substring(tok.StartPos, len)
                    End If
                    tok.Type = index
                Else
                    If tok.StartPos < tok.EndPos - 1 Then
                        tok.Text = Input.Substring(tok.StartPos, 1)
                    End If
                End If

                If SkipList.Contains(tok.Type) Then
                    start = tok.EndPos
                    Skipped.Add(tok)
                Else
                    tok.Skipped = Skipped
                    Skipped = New List(Of Token)
                End If
            Loop While SkipList.Contains(tok.Type)

            LookAheadToken = tok
            Return tok
        End Function
    End Class
#End Region

#Region "Token"

    Public Enum TokenType

        'Non terminal tokens:
        _NONE_      = 0
        _UNDETERMINED_= 1

        'Non terminal tokens:
        COMPARITOR  = 2
        AddExpr     = 3
        MultExpr    = 4
        Atom        = 5
        FORMULA     = 6
        RESERVEDWORD= 7
        ADDITIONALMODELELEMENT= 8
        ADDITIONALCOLUMNNAME= 9
        ADDITIONALCOMPARISON= 10
        ADDITIONALQUOTEDIDENTIFIER= 11
        ADDITIONALVALUE= 12
        ADDOBJECTTYPESRELATEDTOMODELELEMENTTOPAGESTMT= 13
        ASCLAUSE    = 14
        BRACKTEDCOLMNLIST= 15
        COLUMNLIST  = 16
        COLUMNNAME  = 17
        COMPARISON  = 18
        COMPARISONLIST= 19
        COUNTRETURNCOLUMNCONCATENATIONSUB= 20
        COUNTRETURNCOLUMNCONCATENATION= 21
        COUNTRETURNCOLUMN= 22
        COUNTCLAUSE = 23
        DATATYPE    = 24
        DATATYPELENGTH= 25
        DATATYPEPRECISION= 26
        FACTENGINEFUNCTION= 27
        FACTPREDICATE= 28
        FACTTYPENAMESTR= 29
        FACTTYPEPREDICATE= 30
        FACTTYPESIMPLEPREDICATE= 31
        INSERTCOLUMNLIST= 32
        ISAVALUETYPECLAUSE= 33
        MATCHPREDICATE= 34
        MATCHFACTTYPEPREDICATE= 35
        MINMAXELEMENT= 36
        MODELELEMENT= 37
        MODELELEMENTPLURAL= 38
        MODELELEMENTSTR= 39
        MODELMODELELEMENT= 40
        NODESTMT    = 41
        NODE        = 42
        NODEMODIFIERFUNCTION= 43
        NODEPROPERTYIDENTIFICATION= 44
        NODEPROPERTYNAMEIDENTIFICATION= 45
        NODEIDENTIFICATION= 46
        NUMBER1     = 47
        NUMBER2     = 48
        ORDERBYCOLUMN= 49
        PREDICATECLAUSE= 50
        PROPERTYIDENTIFIER= 51
        QUOTEDIDENTIFIER= 52
        QUOTEDIDENTIFIERLIST= 53
        QUOTEDPROPERTYIDENTIFIERLIST= 54
        RECURSIVECLAUSE= 55
        REFERENCEMODECLAUSE= 56
        RETURNCOLUMN= 57
        RETURNCLAUSE= 58
        RETURNFACTTYPEPREDICATE= 59
        RETURNPREDICATE= 60
        ROLENAMESTR = 61
        SETCLAUSE   = 62
        VALUELIST   = 63
        VALUESTRING = 64
        ADDENTITYTYPESTMT= 65
        ADDFACTSTMT = 66
        ADDFACTTYPESTMT= 67
        ADDROLESTMT = 68
        ADDMODELELEMENTSTMT= 69
        ADDOBJECTTYPETOPAGESTMT= 70
        ADDVALUETYPESTMT= 71
        ASSERTSTMT  = 72
        BINARYFACTTYPEMANYTOONEDEFINITIONSTMT= 73
        CONNECTTOMODELSTMT= 74
        CONSTRAINTEITHEROREXTERNAL= 75
        CONSTRAINTEITHERORSUBTYPE= 76
        CONSTRAINTEITHEROR= 77
        CONSTRAINTEXTERNALUNIQUENESS= 78
        CONSTRAINTINCLUSIVEOR= 79
        CONSTRAINTEXTERNALSTMT= 80
        CONSTRAINTMANDATORY= 81
        CREATECONCEPTSTMT= 82
        CREATEDATABASESTMT= 83
        CREATEENTITYTYPESTMT= 84
        CREATEFACTTYPESTMT= 85
        CREATEMODELSTMT= 86
        CREATEMODELELEMENTSTMT= 87
        CREATEPAGESTMT= 88
        CREATESTMT  = 89
        CREATEVALUETYPESTMT= 90
        DATABASECREATECLAUSE= 91
        DATABASELOCATIONCLAUSE= 92
        DATABASETYPECLAUSE= 93
        DELETESTMT  = 94
        DELETEFROMCLAUSE= 95
        DELETEALLSTMT= 96
        DELETEFACTSTMT= 97
        DERIVATIONCLAUSE= 98
        DERIVATIONSUBCLAUSE= 99
        DERIVATIONFORMULA= 100
        DERIVEDFACTTYPESTMT= 101
        FACTREADING = 102
        DERIVATIONFACTREADING= 103
        DERIVATIONWHICHCLAUSE= 104
        DERIVATIONWHICHTHATCLAUSE= 105
        DESCRIBESTMT= 106
        DIDSELECTSTMT= 107
        ENTITYTYPEISIDENTIFIEDBYITSCLAUSE= 108
        ENUMERATESTMT= 109
        EXPRESSION  = 110
        EXPRESSIONPART= 111
        EXISTSSTMT  = 112
        EXTERNALUNIQUENESSCONSTRAINTSTMT= 113
        FACTTYPEISWHERESTMT= 114
        FACTTYPESTMT= 115
        FACTTYPEIDENTIFICATION= 116
        FACTTYPEPARTCLAUSE= 117
        BINARYFACTTYPECLAUSE= 118
        FACTTYPEPRODUCTION= 119
        FACTSTMT    = 120
        GETSUPERTYPESTMT= 121
        GROUPBYCLAUSE= 122
        HAVINGCLAUSE= 123
        INDIVIDUALIDENTIFIER= 124
        INMODELSTMT = 125
        INSERTSTMT  = 126
        ITISMANDATORYTHATSTMNT= 127
        LISTSTMT    = 128
        MATCHFACTTYPESTMT= 129
        MATCHSELECTSETFACTTYPESTMT= 130
        MATHCLAUSE  = 131
        MATCHSELECTSTMT= 132
        ONPAGESTMT  = 133
        OPENMODELSTMT= 134
        ORDERBYCLAUSE= 135
        PREDICATENODEPROPERTYIDENTIFICATION= 136
        SELECTSTMT  = 137
        SHOWSTMT    = 138
        SUBTYPECLAUSE= 139
        SUBTYPESTMT = 140
        TABLEIDENTIFICATION= 141
        UPDATESTMT  = 142
        VALUETYPEISWRITTENASSTMT= 143
        WHERESTMT   = 144
        WHICHTHATCLAUSE= 145
        WHICHCLAUSE = 146
        WITHCLAUSE  = 147
        QUERYBEGINNING= 148
        WHICHSELECTSTMT= 149
        ISSELECTSTMT= 150
        WHOSELECTSTMT= 151
        WITHPREDICATESTMT= 152
        WRITTENASCLAUSE= 153
        DERIVATIONSTMT= 154
        Start       = 155

        'Terminal tokens:
        BANG        = 156
        BROPEN      = 157
        BRCLOSE     = 158
        CARRET      = 159
        CLOSEPARENTHESIS= 160
        CLOSESQUAREBRACKET= 161
        COLON       = 162
        COLUMNNAMESTR= 163
        COMMA       = 164
        CONCATENATIONSYMBOL= 165
        CURLYBRACKETCLOSE= 166
        CURLYBRACKETOPEN= 167
        DATABASENAME= 168
        DATABASETYPE= 169
        DOUBLEQUOTE = 170
        EMAILADDRESS= 171
        EOF         = 172
        EQUALS      = 173
        FACTTYPENAME= 174
        FILELOCATIONNAME= 175
        FOLLOWINGREADINGTEXT= 176
        IDENTIFIER  = 177
        INCOMPARITOR= 178
        INDIVIDUALNAME= 179
        LIKECOMPARITOR= 180
        MATHFUNCTION= 181
        MODELNAME   = 182
        MODELELEMENTNAME= 183
        MODELELEMENTSUFFIX= 184
        MODELID     = 185
        NUMBER      = 186
        PAGENAME    = 187
        OPENPARENTHESIS= 188
        OPENSQUAREBRACKET= 189
        PERIOD      = 190
        PREBOUNDREADINGTEXT= 191
        POSTBOUNDREADINGTEXT= 192
        PREDICATE   = 193
        PREDICATESPACE= 194
        QUOTEDSTRING= 195
        REFERENCEMODE= 196
        ROLENAME    = 197
        SEMICOLON   = 198
        SINGLEQUOTE = 199
        SPACE       = 200
        STAR        = 201
        USERTABLENAME= 202
        WHERECLAUSECOLUMNNAMESTR= 203
        WHICHCLAUSEBROPEN= 204
        WHICHCLAUSEBRCLOSE= 205
        VALUE       = 206
        KEYWDA      = 207
        KEYWDADD    = 208
        KEYWDADDFACT= 209
        KEYWDADDFACTTYPE= 210
        KEYWDADDOBJECTTYPESRELATEDTO= 211
        KEYWDADDOBJECTTYPE= 212
        KEYWDAN     = 213
        KEYWDAND    = 214
        KEYWDANYFACTTYPE= 215
        KEYWDASC    = 216
        KEYWDASSERT = 217
        KEYWDAS     = 218
        KEYWDATMOSTONE= 219
        KEYWDAVG    = 220
        KEYWDBUTNOTBOTH= 221
        KEYWDCIRCULAR= 222
        KEYWDCOMBINATION= 223
        KEYWDCOUNT  = 224
        KEYWDCOUNTSTAR= 225
        KEYWDCREATE = 226
        KEYWDCREATECONCEPT= 227
        KEYWDCONNECTTOMODEL= 228
        KEYWDDATABASE= 229
        KEYWDDATE   = 230
        KEYWDDESC   = 231
        KEYWDCREATEENTITYTYPE= 232
        KEYWDCREATEFACTTYPE= 233
        KEYWDCREATEMODEL= 234
        KEYWDCREATEVALUETYPE= 235
        KEYWDDATATYPELOGICALTRUEFALSE= 236
        KEYWDDATATYPELOGICALYESNO= 237
        KEYWDDATATYPEAUTOCOUNTER= 238
        KEYWDDATATYPEDECIMAL= 239
        KEYWDDATATYPEFLOATCUSTOMPRECISION= 240
        KEYWDDATATYPEFLOATDOUBLEPRECISION= 241
        KEYWDDATATYPEFLOATSINGLEPRECISION= 242
        KEYWDDATATYPEMONEY= 243
        KEYWDDATATYPESIGNEDBIGINTEGER= 244
        KEYWDDATATYPESIGNEDINTEGER= 245
        KEYWDDATATYPESIGNEDSMALLINTEGER= 246
        KEYWDDATATYPEUNSIGNEDBIGINTEGER= 247
        KEYWDDATATYPEUNSIGNEDINTEGER= 248
        KEYWDDATATYPEUNSIGNEDSMALLINTEGER= 249
        KEYWDDATATYPEUNSIGNEDTINYINTEGER= 250
        KEYWDDATATYPEOBJECTID= 251
        KEYWDDATATYPEROWID= 252
        KEYWDDATATYPERAWDATAFIXEDLENGTH= 253
        KEYWDDATATYPERAWDATALARGELENGTH= 254
        KEYWDDATATYPERAWDATAOLEOBJECT= 255
        KEYWDDATATYPERAWDATA= 256
        KEYWDDATATYPERAWDATAVARIABLELENGTH= 257
        KEYWDDATATYPEAUTOTIMESTAMP= 258
        KEYWDDATATYPEDATE= 259
        KEYWDDATATYPEDATETIME= 260
        KEYWDDATATYPETIME= 261
        KEYWDDATATYPESTRINGFIXEDLENGTH= 262
        KEYWDDATATYPESTRINGLARGELENGTH= 263
        KEYWDDATATYPESTRINGVARIABLELENGTH= 264
        KEYWDDATATYPETEXTFIXEDLENGTH= 265
        KEYWDDATATYPETEXTLARGELENGTH= 266
        KEYWDDATATYPETEXTVARIABLELENGTH= 267
        KEYWDDELETE = 268
        KEYWDDELETEALL= 269
        KEYWDDELETEFACT= 270
        KEYWDDESCRIBE= 271
        KEYWDDID    = 272
        KEYWDDISTINCT= 273
        KEYWDDOES   = 274
        KEYWDEACH   = 275
        KEYWDEITHER = 276
        KEYWDENTITY = 277
        KEYWDENTITYTYPE= 278
        KEYWDENTITYTYPES= 279
        KEYWDENUMERATE= 280
        KEYWDEXISTS = 281
        KEYWDFACT   = 282
        KEYWDFACTTYPE= 283
        KEYWDFACTTYPES= 284
        KEYWDFOR    = 285
        KEYWDFOREACH= 286
        KEYWDFROM   = 287
        KEYWDGET    = 288
        KEYWDGROUPBY= 289
        KEYWDHAVING = 290
        KEYWDIFANDONLYIF= 291
        KEYWDIN     = 292
        KEYWDINSERT = 293
        KEYWDINTO   = 294
        KEYWDIS     = 295
        KEYWDISA    = 296
        KEYWDISAKINDOF= 297
        KEYWDISAVALUETYPE= 298
        KEYWDISIDENTIFIEDBYITS= 299
        KEYWDISNOT  = 300
        KEYWDISWHERE= 301
        KEYWDISWRITTENAS= 302
        KEYWDITISMANDATORYTHAT= 303
        KEYWDJOINING= 304
        KEYWDINDEX  = 305
        KEYWDLANGUAGE= 306
        KEYWDLANGUAGEDFD= 307
        KEYWDLANGUAGEERD= 308
        KEYWDLANGUAGEETD= 309
        KEYWDLANGUAGEORM= 310
        KEYWDLANGUAGESTD= 311
        KEYWDLANGUAGEUCD= 312
        KEYWDLOCATION= 313
        KEYWDLIST   = 314
        KEYWDMAX    = 315
        KEYWDMATCH  = 316
        KEYWDMIN    = 317
        KEYWDMODEL  = 318
        KEYWDMONTH  = 319
        KEYWDMODELNOTES= 320
        KEYWDMODELDICTIONARY= 321
        KEYWDNO     = 322
        KEYWDNULL   = 323
        KEYWDOBJECT = 324
        KEYWDOCCURSATLEASTONETIME= 325
        KEYWDOCCURSATLEASTONETIMEINEACHOF= 326
        KEYWDOF     = 327
        KEYWDON     = 328
        KEYWDONE    = 329
        KEYWDONPAGE = 330
        KEYWDOPEN   = 331
        KEYWDOR     = 332
        KEYWDORDERBY= 333
        KEYWDPAGE   = 334
        KEYWDPREDICATE= 335
        KEYWDRETURN = 336
        KEYWDROLE   = 337
        KEYWDSELECT = 338
        KEYWDRESTRICTEDTO= 339
        KEYWDROLECONSTRAINTS= 340
        KEYWDSET    = 341
        KEYWDSHORTESTPATH= 342
        KEYWDSHOW   = 343
        KEYWDSHOWME = 344
        KEYWDSTANDALONE= 345
        KEYWDSUM    = 346
        KEYWDSUPERTYPE= 347
        KEYWDTIME   = 348
        KEYWDTHAT   = 349
        KEYWDTO     = 350
        KEYWDTODAY  = 351
        KEYWDTOLOWER= 352
        KEYWDTOUPPER= 353
        KEYWDTOPAGE = 354
        KEYWDTYPE   = 355
        KEYWDUPDATE = 356
        KEYWDVALUES = 357
        KEYWDVALUETYPE= 358
        KEYWDVALUETYPES= 359
        KEYWDWHEN   = 360
        KEYWDWHERE  = 361
        KEYWDWITH   = 362
        KEYWDWHAT   = 363
        KEYWDWHEREALSO= 364
        KEYWDWHICH  = 365
        KEYWDWHO    = 366
        KEYWDWRITTENAS= 367
        KEYWDYEAR   = 368
        PLUS        = 369
        MINUS       = 370
        DIVIDE      = 371
        TIMES       = 372
        EXPRESSIONSYMBOL= 373
        KEYWDLESSTHAN= 374
        KEYWDGREATERTHAN= 375
        WHITESPACE  = 376
    End Enum

    <Serializable()>
    Public Class Token 
        Implements ICloneable

        Private m_startPos As Integer
        Private m_endPos As Integer
        Private m_text As String
        Private m_value As Object

        ' contains all prior skipped symbols
        Private m_skipped As List(Of Token)


        Public Property StartPos() As Integer
            Get
                Return m_startPos
            End Get
            Set(ByVal value As Integer)
                m_startPos = value
            End Set
        End Property

        Public Property EndPos() As Integer
            Get
                Return m_endPos
            End Get
            Set(ByVal value As Integer)
                m_endPos = value
            End Set
        End Property

        Public ReadOnly Property Length() As Integer
            Get
                Return m_endPos - m_startPos
            End Get
        End Property

        Public Property Text() As String
            Get
                Return m_text
            End Get
            Set(ByVal value As String)
                m_text = value
            End Set
        End Property

        Public Property Skipped() As List(Of Token)
            Get
                Return m_skipped
            End Get
            Set(ByVal value As List(Of Token))
                m_skipped = value
            End Set
        End Property

        Public Property Value() As Object
            Get
                Return m_value
            End Get
            Set(ByVal value As Object)
                Me.m_value = value
            End Set
        End Property

        <XmlAttribute()>
        Public Type As TokenType

        Public Sub New()
            Me.New(0, 0)
        End Sub

        Public Sub New(ByVal start As Integer, ByVal endPos As Integer)
            Type = TokenType._UNDETERMINED_
            m_startPos = start
            m_endPos = endPos
            Text = ""
            ' must initialize with empty string, may cause null reference exceptions otherwise
            Value = Nothing
        End Sub

        Public Sub UpdateRange(ByVal token As Token)
            If token.StartPos < m_startPos Then
                m_startPos = token.StartPos
            End If
            If token.EndPos > m_endPos Then
                m_endPos = token.EndPos
            End If
        End Sub

        Public Overloads Overrides Function ToString() As String
            If Text <> Nothing Then
                Return Type.ToString() + " '" + Text + "'"
            Else
                Return Type.ToString()
            End If
        End Function

        Public Function Clone() As Object Implements ICloneable.Clone
            Dim lrToken As New Token
            Dim lrSkippedToken As Token
            With Me
                lrToken.m_startPos = .m_startPos
                lrToken.m_endPos = .m_endPos
                lrToken.m_text = .m_text
                lrToken.m_value = .m_value
                lrToken.Type = .Type

                ' contains all prior skipped symbols
                If .m_skipped IsNot Nothing Then
                    lrToken.m_skipped = New List(Of Token)
                    For Each lrSkippedToken In .m_skipped
                        lrToken.m_skipped.Add(lrSkippedToken.Clone)
                    Next
                End If
            End With

            Return lrToken
        End Function

    End Class
#End Region
End Namespace
