' Generated by TinyPG v1.3 available at www.codeproject.com

Imports System
Imports System.Collections.Generic
Imports System.Text.RegularExpressions
Imports System.Xml.Serialization


Namespace FEQL
#Region "Scanner"

    Partial Public Class Scanner
        Public Input As String
        Public StartPos As Integer = 0
        Public EndPos As Integer = 0
        Public CurrentLine As Integer
        Public CurrentColumn As Integer
        Public CurrentPosition As Integer
        Public Skipped As List(Of Token) ' tokens that were skipped
        Public Patterns As Dictionary(Of TokenType, Regex)

        Private LookAheadToken As Token
        Private Tokens As List(Of TokenType)
        Private SkipList As List(Of TokenType) ' tokens to be skipped

        Public Sub New()
            Dim regex As Regex
            Patterns = New Dictionary(Of TokenType, Regex)()
            Tokens = New List(Of TokenType)()
            LookAheadToken = Nothing
            Skipped = New List(Of Token)()

            SkipList = New List(Of TokenType)()
            SkipList.Add(TokenType.WHITESPACE)

            regex = new Regex("\(+", RegexOptions.Compiled)
            Patterns.Add(TokenType.BROPEN, regex)
            Tokens.Add(TokenType.BROPEN)

            regex = new Regex("\)+", RegexOptions.Compiled)
            Patterns.Add(TokenType.BRCLOSE, regex)
            Tokens.Add(TokenType.BRCLOSE)

            regex = new Regex(":", RegexOptions.Compiled)
            Patterns.Add(TokenType.COLON, regex)
            Tokens.Add(TokenType.COLON)

            regex = new Regex("[aA-zZ0-9]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.COLUMNNAMESTR, regex)
            Tokens.Add(TokenType.COLUMNNAMESTR)

            regex = new Regex(",", RegexOptions.Compiled)
            Patterns.Add(TokenType.COMMA, regex)
            Tokens.Add(TokenType.COMMA)

            regex = new Regex("\}+", RegexOptions.Compiled)
            Patterns.Add(TokenType.CURLYBRACKETCLOSE, regex)
            Tokens.Add(TokenType.CURLYBRACKETCLOSE)

            regex = new Regex("\{+", RegexOptions.Compiled)
            Patterns.Add(TokenType.CURLYBRACKETOPEN, regex)
            Tokens.Add(TokenType.CURLYBRACKETOPEN)

            regex = new Regex("""", RegexOptions.Compiled)
            Patterns.Add(TokenType.DOUBLEQUOTE, regex)
            Tokens.Add(TokenType.DOUBLEQUOTE)

            regex = new Regex("^$", RegexOptions.Compiled)
            Patterns.Add(TokenType.EOF, regex)
            Tokens.Add(TokenType.EOF)

            regex = new Regex("=", RegexOptions.Compiled)
            Patterns.Add(TokenType.EQUALS, regex)
            Tokens.Add(TokenType.EQUALS)

            regex = new Regex("[aA-zZ]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.FACTTYPENAME, regex)
            Tokens.Add(TokenType.FACTTYPENAME)

            regex = new Regex("[aA-zZ0-9 \-]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.IDENTIFIER, regex)
            Tokens.Add(TokenType.IDENTIFIER)

            regex = new Regex("<=|<|=|>=|>", RegexOptions.Compiled)
            Patterns.Add(TokenType.MATHFUNCTION, regex)
            Tokens.Add(TokenType.MATHFUNCTION)

            regex = new Regex("\*|/", RegexOptions.Compiled)
            Patterns.Add(TokenType.MULTDIV, regex)
            Tokens.Add(TokenType.MULTDIV)

            regex = new Regex("[aA-zZ]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.MODELNAME, regex)
            Tokens.Add(TokenType.MODELNAME)

            regex = new Regex("(([A-Z]+[a-z]+)+[_|\s]?)+", RegexOptions.Compiled)
            Patterns.Add(TokenType.MODELELEMENTNAME, regex)
            Tokens.Add(TokenType.MODELELEMENTNAME)

            regex = new Regex("([0-9])+", RegexOptions.Compiled)
            Patterns.Add(TokenType.MODELELEMENTSUFFIX, regex)
            Tokens.Add(TokenType.MODELELEMENTSUFFIX)

            regex = new Regex("[aA-zZ0-9\-]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.MODELID, regex)
            Tokens.Add(TokenType.MODELID)

            regex = new Regex("[0-9]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.NUMBER, regex)
            Tokens.Add(TokenType.NUMBER)

            regex = new Regex("[aA-zZ0-9\s\-]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.PAGENAME, regex)
            Tokens.Add(TokenType.PAGENAME)

            regex = new Regex("(\+|-)", RegexOptions.Compiled)
            Patterns.Add(TokenType.PLUSMINUS, regex)
            Tokens.Add(TokenType.PLUSMINUS)

            regex = new Regex("[a-z]+\-", RegexOptions.Compiled)
            Patterns.Add(TokenType.PREBOUNDREADINGTEXT, regex)
            Tokens.Add(TokenType.PREBOUNDREADINGTEXT)

            regex = new Regex("\-[a-z]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.POSTBOUNDREADINGTEXT, regex)
            Tokens.Add(TokenType.POSTBOUNDREADINGTEXT)

            regex = new Regex("(?!([a-z]+\-))(?!([a-z\s]+$)^$?)([a-z]+[^\-])", RegexOptions.Compiled)
            Patterns.Add(TokenType.PREDICATE, regex)
            Tokens.Add(TokenType.PREDICATE)

            regex = new Regex("[\s]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.PREDICATESPACE, regex)
            Tokens.Add(TokenType.PREDICATESPACE)

            regex = new Regex("[aA-zZ]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.REFERENCEMODE, regex)
            Tokens.Add(TokenType.REFERENCEMODE)

            regex = new Regex("[a-z]+\-?", RegexOptions.Compiled)
            Patterns.Add(TokenType.ROLENAME, regex)
            Tokens.Add(TokenType.ROLENAME)

            regex = new Regex("'", RegexOptions.Compiled)
            Patterns.Add(TokenType.SINGLEQUOTE, regex)
            Tokens.Add(TokenType.SINGLEQUOTE)

            regex = new Regex("\*", RegexOptions.Compiled)
            Patterns.Add(TokenType.STAR, regex)
            Tokens.Add(TokenType.STAR)

            regex = new Regex("\s", RegexOptions.Compiled)
            Patterns.Add(TokenType.SPACE, regex)
            Tokens.Add(TokenType.SPACE)

            regex = new Regex("[aA-zZ0-9]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.USERTABLENAME, regex)
            Tokens.Add(TokenType.USERTABLENAME)

            regex = new Regex("[aA-zZ0-9]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.WHERECLAUSECOLUMNNAMESTR, regex)
            Tokens.Add(TokenType.WHERECLAUSECOLUMNNAMESTR)

            regex = new Regex("[aA-zZ0-9\-\s+\#\*\?]*", RegexOptions.Compiled)
            Patterns.Add(TokenType.VALUE, regex)
            Tokens.Add(TokenType.VALUE)

            regex = new Regex("A", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDA, regex)
            Tokens.Add(TokenType.KEYWDA)

            regex = new Regex("AN", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDAN, regex)
            Tokens.Add(TokenType.KEYWDAN)

            regex = new Regex("AND", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDAND, regex)
            Tokens.Add(TokenType.KEYWDAND)

            regex = new Regex("ADD", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDADD, regex)
            Tokens.Add(TokenType.KEYWDADD)

            regex = new Regex("ADD FACT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDADDFACT, regex)
            Tokens.Add(TokenType.KEYWDADDFACT)

            regex = new Regex("ADD FACTTYPE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDADDFACTTYPE, regex)
            Tokens.Add(TokenType.KEYWDADDFACTTYPE)

            regex = new Regex("ASSERT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDASSERT, regex)
            Tokens.Add(TokenType.KEYWDASSERT)

            regex = new Regex("AT MOST ONE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDATMOSTONE, regex)
            Tokens.Add(TokenType.KEYWDATMOSTONE)

            regex = new Regex("BUT NOT BOTH", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDBUTNOTBOTH, regex)
            Tokens.Add(TokenType.KEYWDBUTNOTBOTH)

            regex = new Regex("COMBINATION", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDCOMBINATION, regex)
            Tokens.Add(TokenType.KEYWDCOMBINATION)

            regex = new Regex("COUNT\(\*\)", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDCOUNTSTAR, regex)
            Tokens.Add(TokenType.KEYWDCOUNTSTAR)

            regex = new Regex("CREATE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDCREATE, regex)
            Tokens.Add(TokenType.KEYWDCREATE)

            regex = new Regex("CREATE CONCEPT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDCREATECONCEPT, regex)
            Tokens.Add(TokenType.KEYWDCREATECONCEPT)

            regex = new Regex("CREATE ENTITYTTYPE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDCREATEENTITYTYPE, regex)
            Tokens.Add(TokenType.KEYWDCREATEENTITYTYPE)

            regex = new Regex("CREATE FACTTYPE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDCREATEFACTTYPE, regex)
            Tokens.Add(TokenType.KEYWDCREATEFACTTYPE)

            regex = new Regex("CREATE MODEL", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDCREATEMODEL, regex)
            Tokens.Add(TokenType.KEYWDCREATEMODEL)

            regex = new Regex("CREATE VALUETYPE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDCREATEVALUETYPE, regex)
            Tokens.Add(TokenType.KEYWDCREATEVALUETYPE)

            regex = new Regex("LogicalTrueFalse", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPELOGICALTRUEFALSE, regex)
            Tokens.Add(TokenType.KEYWDDATATYPELOGICALTRUEFALSE)

            regex = new Regex("LogicalYesNo", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPELOGICALYESNO, regex)
            Tokens.Add(TokenType.KEYWDDATATYPELOGICALYESNO)

            regex = new Regex("AutoCounter", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEAUTOCOUNTER, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEAUTOCOUNTER)

            regex = new Regex("Decimal", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEDECIMAL, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEDECIMAL)

            regex = new Regex("FloatCustomPrecision", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEFLOATCUSTOMPRECISION, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEFLOATCUSTOMPRECISION)

            regex = new Regex("FloatDoublePrecision", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEFLOATDOUBLEPRECISION, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEFLOATDOUBLEPRECISION)

            regex = new Regex("FloatSinglePrecistion", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEFLOATSINGLEPRECISION, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEFLOATSINGLEPRECISION)

            regex = new Regex("Money", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEMONEY, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEMONEY)

            regex = new Regex("SignedBigInteger", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPESIGNEDBIGINTEGER, regex)
            Tokens.Add(TokenType.KEYWDDATATYPESIGNEDBIGINTEGER)

            regex = new Regex("SignedInteger", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPESIGNEDINTEGER, regex)
            Tokens.Add(TokenType.KEYWDDATATYPESIGNEDINTEGER)

            regex = new Regex("SignedSmallInteger", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPESIGNEDSMALLINTEGER, regex)
            Tokens.Add(TokenType.KEYWDDATATYPESIGNEDSMALLINTEGER)

            regex = new Regex("UnsignedBigInteger", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEUNSIGNEDBIGINTEGER, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEUNSIGNEDBIGINTEGER)

            regex = new Regex("UnsignedInteger", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEUNSIGNEDINTEGER, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEUNSIGNEDINTEGER)

            regex = new Regex("UnsignedSmallInteger", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEUNSIGNEDSMALLINTEGER, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEUNSIGNEDSMALLINTEGER)

            regex = new Regex("UnsignedTinyInteger", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEUNSIGNEDTINYINTEGER, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEUNSIGNEDTINYINTEGER)

            regex = new Regex("ObjectID", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEOBJECTID, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEOBJECTID)

            regex = new Regex("RowID", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEROWID, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEROWID)

            regex = new Regex("RawDataFixedLength", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPERAWDATAFIXEDLENGTH, regex)
            Tokens.Add(TokenType.KEYWDDATATYPERAWDATAFIXEDLENGTH)

            regex = new Regex("RawDataLargeLength", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPERAWDATALARGELENGTH, regex)
            Tokens.Add(TokenType.KEYWDDATATYPERAWDATALARGELENGTH)

            regex = new Regex("RawDataOLEObject", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPERAWDATAOLEOBJECT, regex)
            Tokens.Add(TokenType.KEYWDDATATYPERAWDATAOLEOBJECT)

            regex = new Regex("RawDataPicture", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPERAWDATA, regex)
            Tokens.Add(TokenType.KEYWDDATATYPERAWDATA)

            regex = new Regex("VariableLength", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPERAWDATAVARIABLELENGTH, regex)
            Tokens.Add(TokenType.KEYWDDATATYPERAWDATAVARIABLELENGTH)

            regex = new Regex("AutoTimestamp", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEAUTOTIMESTAMP, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEAUTOTIMESTAMP)

            regex = new Regex("Date", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEDATE, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEDATE)

            regex = new Regex("DateTime", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEDATETIME, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEDATETIME)

            regex = new Regex("Time", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPETIME, regex)
            Tokens.Add(TokenType.KEYWDDATATYPETIME)

            regex = new Regex("StringFixedLength", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPESTRINGFIXEDLENGTH, regex)
            Tokens.Add(TokenType.KEYWDDATATYPESTRINGFIXEDLENGTH)

            regex = new Regex("StringLargeLength", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPESTRINGLARGELENGTH, regex)
            Tokens.Add(TokenType.KEYWDDATATYPESTRINGLARGELENGTH)

            regex = new Regex("StringVariableLength", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPESTRINGVARIABLELENGTH, regex)
            Tokens.Add(TokenType.KEYWDDATATYPESTRINGVARIABLELENGTH)

            regex = new Regex("DELETE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDELETE, regex)
            Tokens.Add(TokenType.KEYWDDELETE)

            regex = new Regex("DELETE ALL", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDELETEALL, regex)
            Tokens.Add(TokenType.KEYWDDELETEALL)

            regex = new Regex("DELETE FACT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDELETEFACT, regex)
            Tokens.Add(TokenType.KEYWDDELETEFACT)

            regex = new Regex("DESCRIBE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDESCRIBE, regex)
            Tokens.Add(TokenType.KEYWDDESCRIBE)

            regex = new Regex("DISTINCT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDISTINCT, regex)
            Tokens.Add(TokenType.KEYWDDISTINCT)

            regex = new Regex("EACH", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDEACH, regex)
            Tokens.Add(TokenType.KEYWDEACH)

            regex = new Regex("EITHER", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDEITHER, regex)
            Tokens.Add(TokenType.KEYWDEITHER)

            regex = new Regex("ENTITY", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDENTITY, regex)
            Tokens.Add(TokenType.KEYWDENTITY)

            regex = new Regex("ENTITYTYPE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDENTITYTYPE, regex)
            Tokens.Add(TokenType.KEYWDENTITYTYPE)

            regex = new Regex("ENTITYTYPES", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDENTITYTYPES, regex)
            Tokens.Add(TokenType.KEYWDENTITYTYPES)

            regex = new Regex("ENUMERATE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDENUMERATE, regex)
            Tokens.Add(TokenType.KEYWDENUMERATE)

            regex = new Regex("EXISTS", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDEXISTS, regex)
            Tokens.Add(TokenType.KEYWDEXISTS)

            regex = new Regex("FACT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDFACT, regex)
            Tokens.Add(TokenType.KEYWDFACT)

            regex = new Regex("FACTTYPE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDFACTTYPE, regex)
            Tokens.Add(TokenType.KEYWDFACTTYPE)

            regex = new Regex("FACTTYPES", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDFACTTYPES, regex)
            Tokens.Add(TokenType.KEYWDFACTTYPES)

            regex = new Regex("FOR", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDFOR, regex)
            Tokens.Add(TokenType.KEYWDFOR)

            regex = new Regex("FOR EACH", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDFOREACH, regex)
            Tokens.Add(TokenType.KEYWDFOREACH)

            regex = new Regex("FROM", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDFROM, regex)
            Tokens.Add(TokenType.KEYWDFROM)

            regex = new Regex("GET", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDGET, regex)
            Tokens.Add(TokenType.KEYWDGET)

            regex = new Regex("IF AND ONLY IF", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDIFANDONLYIF, regex)
            Tokens.Add(TokenType.KEYWDIFANDONLYIF)

            regex = new Regex("IN", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDIN, regex)
            Tokens.Add(TokenType.KEYWDIN)

            regex = new Regex("INSERT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDINSERT, regex)
            Tokens.Add(TokenType.KEYWDINSERT)

            regex = new Regex("INTO", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDINTO, regex)
            Tokens.Add(TokenType.KEYWDINTO)

            regex = new Regex("IS", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDIS, regex)
            Tokens.Add(TokenType.KEYWDIS)

            regex = new Regex("IS A", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDISA, regex)
            Tokens.Add(TokenType.KEYWDISA)

            regex = new Regex("IS IDENTIFIED BY ITS", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDISIDENTIFIEDBYITS, regex)
            Tokens.Add(TokenType.KEYWDISIDENTIFIEDBYITS)

            regex = new Regex("IS NOT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDISNOT, regex)
            Tokens.Add(TokenType.KEYWDISNOT)

            regex = new Regex("IS WHERE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDISWHERE, regex)
            Tokens.Add(TokenType.KEYWDISWHERE)

            regex = new Regex("IS WRITTEN AS", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDISWRITTENAS, regex)
            Tokens.Add(TokenType.KEYWDISWRITTENAS)

            regex = new Regex("IT IS MANDATORY THAT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDITISMANDATORYTHAT, regex)
            Tokens.Add(TokenType.KEYWDITISMANDATORYTHAT)

            regex = new Regex("JOINING", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDJOINING, regex)
            Tokens.Add(TokenType.KEYWDJOINING)

            regex = new Regex("INDEX", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDINDEX, regex)
            Tokens.Add(TokenType.KEYWDINDEX)

            regex = new Regex("LANGUAGE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDLANGUAGE, regex)
            Tokens.Add(TokenType.KEYWDLANGUAGE)

            regex = new Regex("DFD", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDLANGUAGEDFD, regex)
            Tokens.Add(TokenType.KEYWDLANGUAGEDFD)

            regex = new Regex("ERD", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDLANGUAGEERD, regex)
            Tokens.Add(TokenType.KEYWDLANGUAGEERD)

            regex = new Regex("ETD", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDLANGUAGEETD, regex)
            Tokens.Add(TokenType.KEYWDLANGUAGEETD)

            regex = new Regex("ORM", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDLANGUAGEORM, regex)
            Tokens.Add(TokenType.KEYWDLANGUAGEORM)

            regex = new Regex("STD", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDLANGUAGESTD, regex)
            Tokens.Add(TokenType.KEYWDLANGUAGESTD)

            regex = new Regex("UCD", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDLANGUAGEUCD, regex)
            Tokens.Add(TokenType.KEYWDLANGUAGEUCD)

            regex = new Regex("LIST", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDLIST, regex)
            Tokens.Add(TokenType.KEYWDLIST)

            regex = new Regex("MATCH", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDMATCH, regex)
            Tokens.Add(TokenType.KEYWDMATCH)

            regex = new Regex("MODEL", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDMODEL, regex)
            Tokens.Add(TokenType.KEYWDMODEL)

            regex = new Regex("MODELNOTES", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDMODELNOTES, regex)
            Tokens.Add(TokenType.KEYWDMODELNOTES)

            regex = new Regex("MODEL.DICTIONARY", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDMODELDICTIONARY, regex)
            Tokens.Add(TokenType.KEYWDMODELDICTIONARY)

            regex = new Regex("", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDNULL, regex)
            Tokens.Add(TokenType.KEYWDNULL)

            regex = new Regex("OBJECT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDOBJECT, regex)
            Tokens.Add(TokenType.KEYWDOBJECT)

            regex = new Regex("OCCURS AT LEAST ONE TIME IN EITHER", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDOCCURSATLEASTONETIME, regex)
            Tokens.Add(TokenType.KEYWDOCCURSATLEASTONETIME)

            regex = new Regex("OCCURS AT LEAST ONE TIME IN EACH OF", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDOCCURSATLEASTONETIMEINEACHOF, regex)
            Tokens.Add(TokenType.KEYWDOCCURSATLEASTONETIMEINEACHOF)

            regex = new Regex("OF", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDOF, regex)
            Tokens.Add(TokenType.KEYWDOF)

            regex = new Regex("ON", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDON, regex)
            Tokens.Add(TokenType.KEYWDON)

            regex = new Regex("ONE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDONE, regex)
            Tokens.Add(TokenType.KEYWDONE)

            regex = new Regex("ON PAGE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDONPAGE, regex)
            Tokens.Add(TokenType.KEYWDONPAGE)

            regex = new Regex("OPEN", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDOPEN, regex)
            Tokens.Add(TokenType.KEYWDOPEN)

            regex = new Regex("OR", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDOR, regex)
            Tokens.Add(TokenType.KEYWDOR)

            regex = new Regex("PAGE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDPAGE, regex)
            Tokens.Add(TokenType.KEYWDPAGE)

            regex = new Regex("PREDICATE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDPREDICATE, regex)
            Tokens.Add(TokenType.KEYWDPREDICATE)

            regex = new Regex("RETURN", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDRETURN, regex)
            Tokens.Add(TokenType.KEYWDRETURN)

            regex = new Regex("ROLE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDROLE, regex)
            Tokens.Add(TokenType.KEYWDROLE)

            regex = new Regex("SELECT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDSELECT, regex)
            Tokens.Add(TokenType.KEYWDSELECT)

            regex = new Regex("RESTRICTED TO", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDRESTRICTEDTO, regex)
            Tokens.Add(TokenType.KEYWDRESTRICTEDTO)

            regex = new Regex("ROLECONSTRAINTS", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDROLECONSTRAINTS, regex)
            Tokens.Add(TokenType.KEYWDROLECONSTRAINTS)

            regex = new Regex("SET", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDSET, regex)
            Tokens.Add(TokenType.KEYWDSET)

            regex = new Regex("SUPERTYPE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDSUPERTYPE, regex)
            Tokens.Add(TokenType.KEYWDSUPERTYPE)

            regex = new Regex("THAT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDTHAT, regex)
            Tokens.Add(TokenType.KEYWDTHAT)

            regex = new Regex("TO", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDTO, regex)
            Tokens.Add(TokenType.KEYWDTO)

            regex = new Regex("UPDATE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDUPDATE, regex)
            Tokens.Add(TokenType.KEYWDUPDATE)

            regex = new Regex("VALUES", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDVALUES, regex)
            Tokens.Add(TokenType.KEYWDVALUES)

            regex = new Regex("VALUETYPE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDVALUETYPE, regex)
            Tokens.Add(TokenType.KEYWDVALUETYPE)

            regex = new Regex("VALUETYPES", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDVALUETYPES, regex)
            Tokens.Add(TokenType.KEYWDVALUETYPES)

            regex = new Regex("WHEN", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDWHEN, regex)
            Tokens.Add(TokenType.KEYWDWHEN)

            regex = new Regex("WHERE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDWHERE, regex)
            Tokens.Add(TokenType.KEYWDWHERE)

            regex = new Regex("WITH", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDWITH, regex)
            Tokens.Add(TokenType.KEYWDWITH)

            regex = new Regex("WHAT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDWHAT, regex)
            Tokens.Add(TokenType.KEYWDWHAT)

            regex = new Regex("WHICH", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDWHICH, regex)
            Tokens.Add(TokenType.KEYWDWHICH)

            regex = new Regex("\s+", RegexOptions.Compiled)
            Patterns.Add(TokenType.WHITESPACE, regex)
            Tokens.Add(TokenType.WHITESPACE)



        End Sub

        Public Sub Init(ByVal input As String)
            Me.Input = input
            StartPos = 0
            EndPos = 0
            CurrentLine = 0
            CurrentColumn = 0
            CurrentPosition = 0
            Skipped = New List(Of Token)()
            LookAheadToken = Nothing
        End Sub

        Public Function GetToken(ByVal type As TokenType) As Token
            Dim t As New Token(Me.StartPos, Me.EndPos)
            t.Type = type
            Return t
        End Function

        ''' <summary>
        ''' executes a lookahead of the next token
        ''' and will advance the scan on the input string
        ''' </summary>
        ''' <returns></returns>
        Public Function Scan(ByVal ParamArray expectedtokens As TokenType()) As Token
            Dim tok As Token = LookAhead(expectedtokens)
            ' temporarely retrieve the lookahead
            LookAheadToken = Nothing
            ' reset lookahead token, so scanning will continue
            StartPos = tok.EndPos
            EndPos = tok.EndPos
            ' set the tokenizer to the new scan position
            Return tok
        End Function

        ''' <summary>
        ''' returns token with longest best match
        ''' </summary>
        ''' <returns></returns>
        Public Function LookAhead(ByVal ParamArray expectedtokens As TokenType()) As Token
            Dim i As Integer
            Dim start As Integer = StartPos
            Dim tok As Token = Nothing
            Dim scantokens As List(Of TokenType)

            ' this prevents double scanning and matching
            ' increased performance
            If LookAheadToken IsNot Nothing AndAlso LookAheadToken.Type <> TokenType._UNDETERMINED_ AndAlso LookAheadToken.Type <> TokenType._NONE_ Then
                Return LookAheadToken
            End If

            If expectedtokens.Length = 0 Then
                scantokens = Tokens
            Else
                scantokens = New List(Of TokenType)(expectedtokens)
                scantokens.AddRange(SkipList)
            End If

            Do
                Dim len As Integer = -1
                Dim index As TokenType = Integer.MaxValue
                Dim m_input As String

                If start > Input.Length Then
                    tok = New Token(start, start)
                    tok.Type = TokenType._UNDETERMINED_
                    Exit Do
                End If

                m_input = Input.Substring(start)

                tok = New Token(start, EndPos)


                For i = 0 To scantokens.Count - 1
                    Dim r As Regex = Patterns(scantokens(i))
                    Dim m As Match = r.Match(m_input)
                    If m.Success AndAlso m.Index = 0 AndAlso ((m.Length > len) OrElse (scantokens(i) < index AndAlso m.Length = len)) Then
                        len = m.Length
                        index = scantokens(i)
                        Exit For
                    End If
                Next i

                If index >= 0 AndAlso len >= 0 Then
                    tok.EndPos = start + len
                    If tok.StartPos + len <= Input.Length Then
                        tok.Text = Input.Substring(tok.StartPos, len)
                    End If
                    tok.Type = index
                Else
                    If tok.StartPos < tok.EndPos - 1 Then
                        tok.Text = Input.Substring(tok.StartPos, 1)
                    End If
                End If

                If SkipList.Contains(tok.Type) Then
                    start = tok.EndPos
                    Skipped.Add(tok)
                Else
                    tok.Skipped = Skipped
                    Skipped = New List(Of Token)
                End If
            Loop While SkipList.Contains(tok.Type)

            LookAheadToken = tok
            Return tok
        End Function
    End Class
#End Region

#Region "Token"

    Public Enum TokenType

        'Non terminal tokens:
        _NONE_      = 0
        _UNDETERMINED_= 1

        'Non terminal tokens:
        Atom        = 2
        ADDITIONALMODELELEMENT= 3
        ADDITIONALCOLUMNNAME= 4
        ADDITIONALCOMPARISON= 5
        ADDITIONALQUOTEDIDENTIFIER= 6
        ADDITIONALVALUE= 7
        BRACKTEDCOLMNLIST= 8
        COLUMNLIST  = 9
        COLUMNNAME  = 10
        COMPARISON  = 11
        COMPARISONLIST= 12
        DATATYPE    = 13
        DATATYPELENGTH= 14
        DATATYPEPRECISION= 15
        FACTPREDICATE= 16
        FACTREADING = 17
        FACTTYPENAMESTR= 18
        FACTTYPEPREDICATE= 19
        FACTTYPESIMPLEPREDICATE= 20
        INSERTCOLUMNLIST= 21
        MATCHPREDICATE= 22
        MATCHFACTTYPEPREDICATE= 23
        MODELELEMENT= 24
        MODELELEMENTPLURAL= 25
        MODELELEMENTSTR= 26
        MODELMODELELEMENT= 27
        NODESTMT    = 28
        NODEPROPERTYIDENTIFICATION= 29
        NODEIDENTIFICATION= 30
        PREDICATECLAUSE= 31
        QUOTEDIDENTIFIER= 32
        QUOTEDIDENTIFIERLIST= 33
        REFERENCEMODECLAUSE= 34
        RETURNCLAUSE= 35
        RETURNFACTTYPEPREDICATE= 36
        RETURNPREDICATE= 37
        ROLENAMESTR = 38
        SETCLAUSE   = 39
        VALUELIST   = 40
        VALUESTRING = 41
        ADDENTITYTYPESTMT= 42
        ADDFACTSTMT = 43
        ADDFACTTYPESTMT= 44
        ADDROLESTMT = 45
        ADDMODELELEMENTSTMT= 46
        ADDVALUETYPESTMT= 47
        ASSERTSTMT  = 48
        BINARYFACTTYPEMANYTOONEDEFINITIONSTMT= 49
        CONSTRAINTEITHEROREXTERNAL= 50
        CONSTRAINTEITHERORSUBTYPE= 51
        CONSTRAINTEITHEROR= 52
        CONSTRAINTEXTERNALUNIQUENESS= 53
        CONSTRAINTINCLUSIVEOR= 54
        CONSTRAINTEXTERNALSTMT= 55
        CONSTRAINTMANDATORY= 56
        CREATECONCEPTSTMT= 57
        CREATEENTITYTYPESTMT= 58
        CREATEFACTTYPESTMT= 59
        CREATEMODELSTMT= 60
        CREATEMODELELEMENTSTMT= 61
        CREATESTMT  = 62
        CREATEVALUETYPESTMT= 63
        DELETESTMT  = 64
        DELETEFROMCLAUSE= 65
        DELETEALLSTMT= 66
        DELETEFACTSTMT= 67
        DERIVEDFACTTYPESTMT= 68
        ENUMERATESTMT= 69
        DESCRIBESTMT= 70
        EXISTSSTMT  = 71
        EXTERNALUNIQUENESSCONSTRAINTSTMT= 72
        FACTTYPEISWHERESTMT= 73
        FACTTYPESTMT= 74
        FACTTYPEIDENTIFICATION= 75
        FACTTYPEPARTCLAUSE= 76
        BINARYFACTTYPECLAUSE= 77
        FACTTYPEPRODUCTION= 78
        FACTSTMT    = 79
        GETSUPERTYPESTMT= 80
        INMODELSTMT = 81
        INSERTSTMT  = 82
        ITISMANDATORYTHATSTMNT= 83
        LISTSTMT    = 84
        MATCHFACTTYPESTMT= 85
        MATCHSELECTSETFACTTYPESTMT= 86
        MATHCLAUSE  = 87
        MATCHSELECTSTMT= 88
        ONPAGESTMT  = 89
        OPENMODELSTMT= 90
        SELECTSTMT  = 91
        SUBTYPESTMT = 92
        TABLEIDENTIFICATION= 93
        UPDATESTMT  = 94
        VALUETYPEISWRITTENASSTMT= 95
        WHERESTMT   = 96
        WHICHTHATCLAUSE= 97
        WHICHCLAUSE = 98
        WITHCLAUSE  = 99
        WHICHSELECTSTMT= 100
        WITHPREDICATESTMT= 101
        Start       = 102

        'Terminal tokens:
        BROPEN      = 103
        BRCLOSE     = 104
        COLON       = 105
        COLUMNNAMESTR= 106
        COMMA       = 107
        CURLYBRACKETCLOSE= 108
        CURLYBRACKETOPEN= 109
        DOUBLEQUOTE = 110
        EOF         = 111
        EQUALS      = 112
        FACTTYPENAME= 113
        IDENTIFIER  = 114
        MATHFUNCTION= 115
        MULTDIV     = 116
        MODELNAME   = 117
        MODELELEMENTNAME= 118
        MODELELEMENTSUFFIX= 119
        MODELID     = 120
        NUMBER      = 121
        PAGENAME    = 122
        PLUSMINUS   = 123
        PREBOUNDREADINGTEXT= 124
        POSTBOUNDREADINGTEXT= 125
        PREDICATE   = 126
        PREDICATESPACE= 127
        REFERENCEMODE= 128
        ROLENAME    = 129
        SINGLEQUOTE = 130
        STAR        = 131
        SPACE       = 132
        USERTABLENAME= 133
        WHERECLAUSECOLUMNNAMESTR= 134
        VALUE       = 135
        KEYWDA      = 136
        KEYWDAN     = 137
        KEYWDAND    = 138
        KEYWDADD    = 139
        KEYWDADDFACT= 140
        KEYWDADDFACTTYPE= 141
        KEYWDASSERT = 142
        KEYWDATMOSTONE= 143
        KEYWDBUTNOTBOTH= 144
        KEYWDCOMBINATION= 145
        KEYWDCOUNTSTAR= 146
        KEYWDCREATE = 147
        KEYWDCREATECONCEPT= 148
        KEYWDCREATEENTITYTYPE= 149
        KEYWDCREATEFACTTYPE= 150
        KEYWDCREATEMODEL= 151
        KEYWDCREATEVALUETYPE= 152
        KEYWDDATATYPELOGICALTRUEFALSE= 153
        KEYWDDATATYPELOGICALYESNO= 154
        KEYWDDATATYPEAUTOCOUNTER= 155
        KEYWDDATATYPEDECIMAL= 156
        KEYWDDATATYPEFLOATCUSTOMPRECISION= 157
        KEYWDDATATYPEFLOATDOUBLEPRECISION= 158
        KEYWDDATATYPEFLOATSINGLEPRECISION= 159
        KEYWDDATATYPEMONEY= 160
        KEYWDDATATYPESIGNEDBIGINTEGER= 161
        KEYWDDATATYPESIGNEDINTEGER= 162
        KEYWDDATATYPESIGNEDSMALLINTEGER= 163
        KEYWDDATATYPEUNSIGNEDBIGINTEGER= 164
        KEYWDDATATYPEUNSIGNEDINTEGER= 165
        KEYWDDATATYPEUNSIGNEDSMALLINTEGER= 166
        KEYWDDATATYPEUNSIGNEDTINYINTEGER= 167
        KEYWDDATATYPEOBJECTID= 168
        KEYWDDATATYPEROWID= 169
        KEYWDDATATYPERAWDATAFIXEDLENGTH= 170
        KEYWDDATATYPERAWDATALARGELENGTH= 171
        KEYWDDATATYPERAWDATAOLEOBJECT= 172
        KEYWDDATATYPERAWDATA= 173
        KEYWDDATATYPERAWDATAVARIABLELENGTH= 174
        KEYWDDATATYPEAUTOTIMESTAMP= 175
        KEYWDDATATYPEDATE= 176
        KEYWDDATATYPEDATETIME= 177
        KEYWDDATATYPETIME= 178
        KEYWDDATATYPESTRINGFIXEDLENGTH= 179
        KEYWDDATATYPESTRINGLARGELENGTH= 180
        KEYWDDATATYPESTRINGVARIABLELENGTH= 181
        KEYWDDELETE = 182
        KEYWDDELETEALL= 183
        KEYWDDELETEFACT= 184
        KEYWDDESCRIBE= 185
        KEYWDDISTINCT= 186
        KEYWDEACH   = 187
        KEYWDEITHER = 188
        KEYWDENTITY = 189
        KEYWDENTITYTYPE= 190
        KEYWDENTITYTYPES= 191
        KEYWDENUMERATE= 192
        KEYWDEXISTS = 193
        KEYWDFACT   = 194
        KEYWDFACTTYPE= 195
        KEYWDFACTTYPES= 196
        KEYWDFOR    = 197
        KEYWDFOREACH= 198
        KEYWDFROM   = 199
        KEYWDGET    = 200
        KEYWDIFANDONLYIF= 201
        KEYWDIN     = 202
        KEYWDINSERT = 203
        KEYWDINTO   = 204
        KEYWDIS     = 205
        KEYWDISA    = 206
        KEYWDISIDENTIFIEDBYITS= 207
        KEYWDISNOT  = 208
        KEYWDISWHERE= 209
        KEYWDISWRITTENAS= 210
        KEYWDITISMANDATORYTHAT= 211
        KEYWDJOINING= 212
        KEYWDINDEX  = 213
        KEYWDLANGUAGE= 214
        KEYWDLANGUAGEDFD= 215
        KEYWDLANGUAGEERD= 216
        KEYWDLANGUAGEETD= 217
        KEYWDLANGUAGEORM= 218
        KEYWDLANGUAGESTD= 219
        KEYWDLANGUAGEUCD= 220
        KEYWDLIST   = 221
        KEYWDMATCH  = 222
        KEYWDMODEL  = 223
        KEYWDMODELNOTES= 224
        KEYWDMODELDICTIONARY= 225
        KEYWDNULL   = 226
        KEYWDOBJECT = 227
        KEYWDOCCURSATLEASTONETIME= 228
        KEYWDOCCURSATLEASTONETIMEINEACHOF= 229
        KEYWDOF     = 230
        KEYWDON     = 231
        KEYWDONE    = 232
        KEYWDONPAGE = 233
        KEYWDOPEN   = 234
        KEYWDOR     = 235
        KEYWDPAGE   = 236
        KEYWDPREDICATE= 237
        KEYWDRETURN = 238
        KEYWDROLE   = 239
        KEYWDSELECT = 240
        KEYWDRESTRICTEDTO= 241
        KEYWDROLECONSTRAINTS= 242
        KEYWDSET    = 243
        KEYWDSUPERTYPE= 244
        KEYWDTHAT   = 245
        KEYWDTO     = 246
        KEYWDUPDATE = 247
        KEYWDVALUES = 248
        KEYWDVALUETYPE= 249
        KEYWDVALUETYPES= 250
        KEYWDWHEN   = 251
        KEYWDWHERE  = 252
        KEYWDWITH   = 253
        KEYWDWHAT   = 254
        KEYWDWHICH  = 255
        WHITESPACE  = 256
    End Enum

    <Serializable()> _
    Public Class Token 
        Private m_startPos As Integer
        Private m_endPos As Integer
        Private m_text As String
        Private m_value As Object

        ' contains all prior skipped symbols
        Private m_skipped As List(Of Token)


        Public Property StartPos() As Integer
            Get
                Return m_startPos
            End Get
            Set(ByVal value As Integer)
                m_startPos = value
            End Set
        End Property

        Public Property EndPos() As Integer
            Get
                Return m_endPos
            End Get
            Set(ByVal value As Integer)
                m_endPos = value
            End Set
        End Property

        Public ReadOnly Property Length() As Integer
            Get
                Return m_endPos - m_startPos
            End Get
        End Property

        Public Property Text() As String
            Get
                Return m_text
            End Get
            Set(ByVal value As String)
                m_text = value
            End Set
        End Property

        Public Property Skipped() As List(Of Token)
            Get
                Return m_skipped
            End Get
            Set(ByVal value As List(Of Token))
                m_skipped = value
            End Set
        End Property

        Public Property Value() As Object
            Get
                Return m_value
            End Get
            Set(ByVal value As Object)
                Me.m_value = value
            End Set
        End Property

        <XmlAttribute()> _
        Public Type As TokenType

        Public Sub New()
            Me.New(0, 0)
        End Sub

        Public Sub New(ByVal start As Integer, ByVal endPos As Integer)
            Type = TokenType._UNDETERMINED_
            m_startPos = start
            m_endPos = endPos
            Text = ""
            ' must initialize with empty string, may cause null reference exceptions otherwise
            Value = Nothing
        End Sub

        Public Sub UpdateRange(ByVal token As Token)
            If token.StartPos < m_startPos Then
                m_startPos = token.StartPos
            End If
            If token.EndPos > m_endPos Then
                m_endPos = token.EndPos
            End If
        End Sub

        Public Overloads Overrides Function ToString() As String
            If Text <> Nothing Then
                Return Type.ToString() + " '" + Text + "'"
            Else
                Return Type.ToString()
            End If
        End Function
    End Class
#End Region
End Namespace
