' Generated by TinyPG v1.3 available at www.codeproject.com

Imports System
Imports System.Collections.Generic
Imports System.Text.RegularExpressions
Imports System.Xml.Serialization


Namespace FEQL
#Region "Scanner"

    Partial Public Class Scanner
        Public Input As String
        Public StartPos As Integer = 0
        Public EndPos As Integer = 0
        Public CurrentLine As Integer
        Public CurrentColumn As Integer
        Public CurrentPosition As Integer
        Public Skipped As List(Of Token) ' tokens that were skipped
        Public Patterns As Dictionary(Of TokenType, Regex)

        Private LookAheadToken As Token
        Private Tokens As List(Of TokenType)
        Private SkipList As List(Of TokenType) ' tokens to be skipped

        Public Sub New()
            Dim regex As Regex
            Patterns = New Dictionary(Of TokenType, Regex)()
            Tokens = New List(Of TokenType)()
            LookAheadToken = Nothing
            Skipped = New List(Of Token)()

            SkipList = New List(Of TokenType)()
            SkipList.Add(TokenType.WHITESPACE)

            regex = new Regex("\(+", RegexOptions.Compiled)
            Patterns.Add(TokenType.BROPEN, regex)
            Tokens.Add(TokenType.BROPEN)

            regex = new Regex("\)+", RegexOptions.Compiled)
            Patterns.Add(TokenType.BRCLOSE, regex)
            Tokens.Add(TokenType.BRCLOSE)

            regex = new Regex("\^", RegexOptions.Compiled)
            Patterns.Add(TokenType.CARRET, regex)
            Tokens.Add(TokenType.CARRET)

            regex = new Regex(":", RegexOptions.Compiled)
            Patterns.Add(TokenType.COLON, regex)
            Tokens.Add(TokenType.COLON)

            regex = new Regex("[aA-zZ0-9]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.COLUMNNAMESTR, regex)
            Tokens.Add(TokenType.COLUMNNAMESTR)

            regex = new Regex(",", RegexOptions.Compiled)
            Patterns.Add(TokenType.COMMA, regex)
            Tokens.Add(TokenType.COMMA)

            regex = new Regex("\}+", RegexOptions.Compiled)
            Patterns.Add(TokenType.CURLYBRACKETCLOSE, regex)
            Tokens.Add(TokenType.CURLYBRACKETCLOSE)

            regex = new Regex("\{+", RegexOptions.Compiled)
            Patterns.Add(TokenType.CURLYBRACKETOPEN, regex)
            Tokens.Add(TokenType.CURLYBRACKETOPEN)

            regex = new Regex("""", RegexOptions.Compiled)
            Patterns.Add(TokenType.DOUBLEQUOTE, regex)
            Tokens.Add(TokenType.DOUBLEQUOTE)

            regex = new Regex("^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})", RegexOptions.Compiled)
            Patterns.Add(TokenType.EMAILADDRESS, regex)
            Tokens.Add(TokenType.EMAILADDRESS)

            regex = new Regex("^$", RegexOptions.Compiled)
            Patterns.Add(TokenType.EOF, regex)
            Tokens.Add(TokenType.EOF)

            regex = new Regex("=", RegexOptions.Compiled)
            Patterns.Add(TokenType.EQUALS, regex)
            Tokens.Add(TokenType.EQUALS)

            regex = new Regex("[aA-zZ]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.FACTTYPENAME, regex)
            Tokens.Add(TokenType.FACTTYPENAME)

            regex = new Regex("([a-z]+[\s]?)+$", RegexOptions.Compiled)
            Patterns.Add(TokenType.FOLLOWINGREADINGTEXT, regex)
            Tokens.Add(TokenType.FOLLOWINGREADINGTEXT)

            regex = new Regex("[aA-zZ0-9 \-]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.IDENTIFIER, regex)
            Tokens.Add(TokenType.IDENTIFIER)

            regex = new Regex("<=|<|=|>=|>", RegexOptions.Compiled)
            Patterns.Add(TokenType.MATHFUNCTION, regex)
            Tokens.Add(TokenType.MATHFUNCTION)

            regex = new Regex("[aA-zZ]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.MODELNAME, regex)
            Tokens.Add(TokenType.MODELNAME)

            regex = new Regex("(([A-Z0-9][a-z0-9]+)+[_|\s]?)+", RegexOptions.Compiled)
            Patterns.Add(TokenType.MODELELEMENTNAME, regex)
            Tokens.Add(TokenType.MODELELEMENTNAME)

            regex = new Regex("([0-9])+", RegexOptions.Compiled)
            Patterns.Add(TokenType.MODELELEMENTSUFFIX, regex)
            Tokens.Add(TokenType.MODELELEMENTSUFFIX)

            regex = new Regex("[aA-zZ0-9\-]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.MODELID, regex)
            Tokens.Add(TokenType.MODELID)

            regex = new Regex("[0-9]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.NUMBER, regex)
            Tokens.Add(TokenType.NUMBER)

            regex = new Regex("[aA-zZ0-9\s\-]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.PAGENAME, regex)
            Tokens.Add(TokenType.PAGENAME)

            regex = new Regex("[a-z]+\-", RegexOptions.Compiled)
            Patterns.Add(TokenType.PREBOUNDREADINGTEXT, regex)
            Tokens.Add(TokenType.PREBOUNDREADINGTEXT)

            regex = new Regex("\-[a-z]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.POSTBOUNDREADINGTEXT, regex)
            Tokens.Add(TokenType.POSTBOUNDREADINGTEXT)

            regex = new Regex("(?!([a-z]+\-))(?!([a-z\s]+$)^$?)([a-z]+[^\-])", RegexOptions.Compiled)
            Patterns.Add(TokenType.PREDICATE, regex)
            Tokens.Add(TokenType.PREDICATE)

            regex = new Regex("[\s]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.PREDICATESPACE, regex)
            Tokens.Add(TokenType.PREDICATESPACE)

            regex = new Regex("[aA-zZ]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.REFERENCEMODE, regex)
            Tokens.Add(TokenType.REFERENCEMODE)

            regex = new Regex("[a-z]+\-?", RegexOptions.Compiled)
            Patterns.Add(TokenType.ROLENAME, regex)
            Tokens.Add(TokenType.ROLENAME)

            regex = new Regex("'", RegexOptions.Compiled)
            Patterns.Add(TokenType.SINGLEQUOTE, regex)
            Tokens.Add(TokenType.SINGLEQUOTE)

            regex = new Regex("\s", RegexOptions.Compiled)
            Patterns.Add(TokenType.SPACE, regex)
            Tokens.Add(TokenType.SPACE)

            regex = new Regex("\*", RegexOptions.Compiled)
            Patterns.Add(TokenType.STAR, regex)
            Tokens.Add(TokenType.STAR)

            regex = new Regex("[aA-zZ0-9]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.USERTABLENAME, regex)
            Tokens.Add(TokenType.USERTABLENAME)

            regex = new Regex("[aA-zZ0-9]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.WHERECLAUSECOLUMNNAMESTR, regex)
            Tokens.Add(TokenType.WHERECLAUSECOLUMNNAMESTR)

            regex = new Regex("[aA-zZ0-9\-\s+\#\*\?]*", RegexOptions.Compiled)
            Patterns.Add(TokenType.VALUE, regex)
            Tokens.Add(TokenType.VALUE)

            regex = New Regex("A ", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDA, regex)
            Tokens.Add(TokenType.KEYWDA)

            regex = New Regex("AN ", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDAN, regex)
            Tokens.Add(TokenType.KEYWDAN)

            regex = New Regex("AND", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDAND, regex)
            Tokens.Add(TokenType.KEYWDAND)

            regex = New Regex("ADD", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDADD, regex)
            Tokens.Add(TokenType.KEYWDADD)

            regex = New Regex("ADD FACT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDADDFACT, regex)
            Tokens.Add(TokenType.KEYWDADDFACT)

            regex = New Regex("ADD FACTTYPE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDADDFACTTYPE, regex)
            Tokens.Add(TokenType.KEYWDADDFACTTYPE)

            regex = New Regex("ASSERT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDASSERT, regex)
            Tokens.Add(TokenType.KEYWDASSERT)

            regex = New Regex("AT MOST ONE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDATMOSTONE, regex)
            Tokens.Add(TokenType.KEYWDATMOSTONE)

            regex = New Regex("BUT NOT BOTH", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDBUTNOTBOTH, regex)
            Tokens.Add(TokenType.KEYWDBUTNOTBOTH)

            regex = New Regex("COMBINATION", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDCOMBINATION, regex)
            Tokens.Add(TokenType.KEYWDCOMBINATION)

            regex = New Regex("COUNT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDCOUNT, regex)
            Tokens.Add(TokenType.KEYWDCOUNT)

            regex = New Regex("COUNT\(\*\)", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDCOUNTSTAR, regex)
            Tokens.Add(TokenType.KEYWDCOUNTSTAR)

            regex = New Regex("CREATE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDCREATE, regex)
            Tokens.Add(TokenType.KEYWDCREATE)

            regex = New Regex("CREATE CONCEPT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDCREATECONCEPT, regex)
            Tokens.Add(TokenType.KEYWDCREATECONCEPT)

            regex = New Regex("CREATE ENTITYTTYPE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDCREATEENTITYTYPE, regex)
            Tokens.Add(TokenType.KEYWDCREATEENTITYTYPE)

            regex = New Regex("CREATE FACTTYPE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDCREATEFACTTYPE, regex)
            Tokens.Add(TokenType.KEYWDCREATEFACTTYPE)

            regex = New Regex("CREATE MODEL", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDCREATEMODEL, regex)
            Tokens.Add(TokenType.KEYWDCREATEMODEL)

            regex = New Regex("CREATE VALUETYPE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDCREATEVALUETYPE, regex)
            Tokens.Add(TokenType.KEYWDCREATEVALUETYPE)

            regex = New Regex("LogicalTrueFalse", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPELOGICALTRUEFALSE, regex)
            Tokens.Add(TokenType.KEYWDDATATYPELOGICALTRUEFALSE)

            regex = New Regex("LogicalYesNo", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPELOGICALYESNO, regex)
            Tokens.Add(TokenType.KEYWDDATATYPELOGICALYESNO)

            regex = New Regex("AutoCounter", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEAUTOCOUNTER, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEAUTOCOUNTER)

            regex = New Regex("Decimal", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEDECIMAL, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEDECIMAL)

            regex = New Regex("FloatCustomPrecision", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEFLOATCUSTOMPRECISION, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEFLOATCUSTOMPRECISION)

            regex = New Regex("FloatDoublePrecision", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEFLOATDOUBLEPRECISION, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEFLOATDOUBLEPRECISION)

            regex = New Regex("FloatSinglePrecistion", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEFLOATSINGLEPRECISION, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEFLOATSINGLEPRECISION)

            regex = New Regex("Money", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEMONEY, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEMONEY)

            regex = New Regex("SignedBigInteger", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPESIGNEDBIGINTEGER, regex)
            Tokens.Add(TokenType.KEYWDDATATYPESIGNEDBIGINTEGER)

            regex = New Regex("SignedInteger", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPESIGNEDINTEGER, regex)
            Tokens.Add(TokenType.KEYWDDATATYPESIGNEDINTEGER)

            regex = New Regex("SignedSmallInteger", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPESIGNEDSMALLINTEGER, regex)
            Tokens.Add(TokenType.KEYWDDATATYPESIGNEDSMALLINTEGER)

            regex = New Regex("UnsignedBigInteger", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEUNSIGNEDBIGINTEGER, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEUNSIGNEDBIGINTEGER)

            regex = New Regex("UnsignedInteger", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEUNSIGNEDINTEGER, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEUNSIGNEDINTEGER)

            regex = New Regex("UnsignedSmallInteger", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEUNSIGNEDSMALLINTEGER, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEUNSIGNEDSMALLINTEGER)

            regex = New Regex("UnsignedTinyInteger", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEUNSIGNEDTINYINTEGER, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEUNSIGNEDTINYINTEGER)

            regex = New Regex("ObjectID", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEOBJECTID, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEOBJECTID)

            regex = New Regex("RowID", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEROWID, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEROWID)

            regex = New Regex("RawDataFixedLength", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPERAWDATAFIXEDLENGTH, regex)
            Tokens.Add(TokenType.KEYWDDATATYPERAWDATAFIXEDLENGTH)

            regex = New Regex("RawDataLargeLength", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPERAWDATALARGELENGTH, regex)
            Tokens.Add(TokenType.KEYWDDATATYPERAWDATALARGELENGTH)

            regex = New Regex("RawDataOLEObject", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPERAWDATAOLEOBJECT, regex)
            Tokens.Add(TokenType.KEYWDDATATYPERAWDATAOLEOBJECT)

            regex = New Regex("RawDataPicture", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPERAWDATA, regex)
            Tokens.Add(TokenType.KEYWDDATATYPERAWDATA)

            regex = New Regex("VariableLength", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPERAWDATAVARIABLELENGTH, regex)
            Tokens.Add(TokenType.KEYWDDATATYPERAWDATAVARIABLELENGTH)

            regex = New Regex("AutoTimestamp", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEAUTOTIMESTAMP, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEAUTOTIMESTAMP)

            regex = New Regex("Date", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEDATE, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEDATE)

            regex = New Regex("DateTime", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEDATETIME, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEDATETIME)

            regex = New Regex("Time", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPETIME, regex)
            Tokens.Add(TokenType.KEYWDDATATYPETIME)

            regex = New Regex("StringFixedLength", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPESTRINGFIXEDLENGTH, regex)
            Tokens.Add(TokenType.KEYWDDATATYPESTRINGFIXEDLENGTH)

            regex = New Regex("StringLargeLength", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPESTRINGLARGELENGTH, regex)
            Tokens.Add(TokenType.KEYWDDATATYPESTRINGLARGELENGTH)

            regex = New Regex("StringVariableLength", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPESTRINGVARIABLELENGTH, regex)
            Tokens.Add(TokenType.KEYWDDATATYPESTRINGVARIABLELENGTH)

            regex = New Regex("DELETE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDELETE, regex)
            Tokens.Add(TokenType.KEYWDDELETE)

            regex = New Regex("DELETE ALL", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDELETEALL, regex)
            Tokens.Add(TokenType.KEYWDDELETEALL)

            regex = New Regex("DELETE FACT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDELETEFACT, regex)
            Tokens.Add(TokenType.KEYWDDELETEFACT)

            regex = New Regex("DESCRIBE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDESCRIBE, regex)
            Tokens.Add(TokenType.KEYWDDESCRIBE)

            regex = New Regex("DID", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDID, regex)
            Tokens.Add(TokenType.KEYWDDID)

            regex = New Regex("DISTINCT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDISTINCT, regex)
            Tokens.Add(TokenType.KEYWDDISTINCT)

            regex = New Regex("EACH", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDEACH, regex)
            Tokens.Add(TokenType.KEYWDEACH)

            regex = New Regex("EITHER", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDEITHER, regex)
            Tokens.Add(TokenType.KEYWDEITHER)

            regex = New Regex("ENTITY", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDENTITY, regex)
            Tokens.Add(TokenType.KEYWDENTITY)

            regex = New Regex("ENTITYTYPE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDENTITYTYPE, regex)
            Tokens.Add(TokenType.KEYWDENTITYTYPE)

            regex = New Regex("ENTITYTYPES", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDENTITYTYPES, regex)
            Tokens.Add(TokenType.KEYWDENTITYTYPES)

            regex = New Regex("ENUMERATE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDENUMERATE, regex)
            Tokens.Add(TokenType.KEYWDENUMERATE)

            regex = New Regex("EXISTS", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDEXISTS, regex)
            Tokens.Add(TokenType.KEYWDEXISTS)

            regex = New Regex("FACT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDFACT, regex)
            Tokens.Add(TokenType.KEYWDFACT)

            regex = New Regex("FACTTYPE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDFACTTYPE, regex)
            Tokens.Add(TokenType.KEYWDFACTTYPE)

            regex = New Regex("FACTTYPES", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDFACTTYPES, regex)
            Tokens.Add(TokenType.KEYWDFACTTYPES)

            regex = New Regex("FOR", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDFOR, regex)
            Tokens.Add(TokenType.KEYWDFOR)

            regex = New Regex("FOR EACH", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDFOREACH, regex)
            Tokens.Add(TokenType.KEYWDFOREACH)

            regex = New Regex("FROM", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDFROM, regex)
            Tokens.Add(TokenType.KEYWDFROM)

            regex = New Regex("GET", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDGET, regex)
            Tokens.Add(TokenType.KEYWDGET)

            regex = New Regex("IF AND ONLY IF", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDIFANDONLYIF, regex)
            Tokens.Add(TokenType.KEYWDIFANDONLYIF)

            regex = New Regex("IN", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDIN, regex)
            Tokens.Add(TokenType.KEYWDIN)

            regex = New Regex("INSERT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDINSERT, regex)
            Tokens.Add(TokenType.KEYWDINSERT)

            regex = New Regex("INTO", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDINTO, regex)
            Tokens.Add(TokenType.KEYWDINTO)

            regex = New Regex("IS", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDIS, regex)
            Tokens.Add(TokenType.KEYWDIS)

            regex = New Regex("IS A", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDISA, regex)
            Tokens.Add(TokenType.KEYWDISA)

            regex = New Regex("IS A KIND OF", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDISAKINDOF, regex)
            Tokens.Add(TokenType.KEYWDISAKINDOF)

            regex = New Regex("IS IDENTIFIED BY ITS", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDISIDENTIFIEDBYITS, regex)
            Tokens.Add(TokenType.KEYWDISIDENTIFIEDBYITS)

            regex = New Regex("IS NOT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDISNOT, regex)
            Tokens.Add(TokenType.KEYWDISNOT)

            regex = New Regex("IS WHERE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDISWHERE, regex)
            Tokens.Add(TokenType.KEYWDISWHERE)

            regex = New Regex("IS WRITTEN AS", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDISWRITTENAS, regex)
            Tokens.Add(TokenType.KEYWDISWRITTENAS)

            regex = New Regex("IT IS MANDATORY THAT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDITISMANDATORYTHAT, regex)
            Tokens.Add(TokenType.KEYWDITISMANDATORYTHAT)

            regex = New Regex("JOINING", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDJOINING, regex)
            Tokens.Add(TokenType.KEYWDJOINING)

            regex = New Regex("INDEX", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDINDEX, regex)
            Tokens.Add(TokenType.KEYWDINDEX)

            regex = New Regex("LANGUAGE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDLANGUAGE, regex)
            Tokens.Add(TokenType.KEYWDLANGUAGE)

            regex = New Regex("DFD", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDLANGUAGEDFD, regex)
            Tokens.Add(TokenType.KEYWDLANGUAGEDFD)

            regex = New Regex("ERD", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDLANGUAGEERD, regex)
            Tokens.Add(TokenType.KEYWDLANGUAGEERD)

            regex = New Regex("ETD", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDLANGUAGEETD, regex)
            Tokens.Add(TokenType.KEYWDLANGUAGEETD)

            regex = New Regex("ORM", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDLANGUAGEORM, regex)
            Tokens.Add(TokenType.KEYWDLANGUAGEORM)

            regex = New Regex("STD", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDLANGUAGESTD, regex)
            Tokens.Add(TokenType.KEYWDLANGUAGESTD)

            regex = New Regex("UCD", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDLANGUAGEUCD, regex)
            Tokens.Add(TokenType.KEYWDLANGUAGEUCD)

            regex = New Regex("LIST", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDLIST, regex)
            Tokens.Add(TokenType.KEYWDLIST)

            regex = New Regex("MATCH", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDMATCH, regex)
            Tokens.Add(TokenType.KEYWDMATCH)

            regex = New Regex("MODEL", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDMODEL, regex)
            Tokens.Add(TokenType.KEYWDMODEL)

            regex = New Regex("MODELNOTES", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDMODELNOTES, regex)
            Tokens.Add(TokenType.KEYWDMODELNOTES)

            regex = New Regex("MODEL.DICTIONARY", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDMODELDICTIONARY, regex)
            Tokens.Add(TokenType.KEYWDMODELDICTIONARY)

            regex = New Regex("", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDNULL, regex)
            Tokens.Add(TokenType.KEYWDNULL)

            regex = New Regex("OBJECT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDOBJECT, regex)
            Tokens.Add(TokenType.KEYWDOBJECT)

            regex = New Regex("OCCURS AT LEAST ONE TIME IN EITHER", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDOCCURSATLEASTONETIME, regex)
            Tokens.Add(TokenType.KEYWDOCCURSATLEASTONETIME)

            regex = New Regex("OCCURS AT LEAST ONE TIME IN EACH OF", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDOCCURSATLEASTONETIMEINEACHOF, regex)
            Tokens.Add(TokenType.KEYWDOCCURSATLEASTONETIMEINEACHOF)

            regex = New Regex("OF", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDOF, regex)
            Tokens.Add(TokenType.KEYWDOF)

            regex = New Regex("ON", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDON, regex)
            Tokens.Add(TokenType.KEYWDON)

            regex = New Regex("ONE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDONE, regex)
            Tokens.Add(TokenType.KEYWDONE)

            regex = New Regex("ON PAGE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDONPAGE, regex)
            Tokens.Add(TokenType.KEYWDONPAGE)

            regex = New Regex("OPEN", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDOPEN, regex)
            Tokens.Add(TokenType.KEYWDOPEN)

            regex = New Regex("OR", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDOR, regex)
            Tokens.Add(TokenType.KEYWDOR)

            regex = New Regex("PAGE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDPAGE, regex)
            Tokens.Add(TokenType.KEYWDPAGE)

            regex = New Regex("PREDICATE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDPREDICATE, regex)
            Tokens.Add(TokenType.KEYWDPREDICATE)

            regex = New Regex("RETURN", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDRETURN, regex)
            Tokens.Add(TokenType.KEYWDRETURN)

            regex = New Regex("ROLE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDROLE, regex)
            Tokens.Add(TokenType.KEYWDROLE)

            regex = New Regex("SELECT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDSELECT, regex)
            Tokens.Add(TokenType.KEYWDSELECT)

            regex = New Regex("RESTRICTED TO", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDRESTRICTEDTO, regex)
            Tokens.Add(TokenType.KEYWDRESTRICTEDTO)

            regex = New Regex("ROLECONSTRAINTS", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDROLECONSTRAINTS, regex)
            Tokens.Add(TokenType.KEYWDROLECONSTRAINTS)

            regex = New Regex("SET", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDSET, regex)
            Tokens.Add(TokenType.KEYWDSET)

            regex = New Regex("SHOW", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDSHOW, regex)
            Tokens.Add(TokenType.KEYWDSHOW)

            regex = New Regex("SUPERTYPE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDSUPERTYPE, regex)
            Tokens.Add(TokenType.KEYWDSUPERTYPE)

            regex = New Regex("THAT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDTHAT, regex)
            Tokens.Add(TokenType.KEYWDTHAT)

            regex = New Regex("TO", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDTO, regex)
            Tokens.Add(TokenType.KEYWDTO)

            regex = New Regex("UPDATE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDUPDATE, regex)
            Tokens.Add(TokenType.KEYWDUPDATE)

            regex = New Regex("VALUES", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDVALUES, regex)
            Tokens.Add(TokenType.KEYWDVALUES)

            regex = New Regex("VALUETYPE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDVALUETYPE, regex)
            Tokens.Add(TokenType.KEYWDVALUETYPE)

            regex = New Regex("VALUETYPES", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDVALUETYPES, regex)
            Tokens.Add(TokenType.KEYWDVALUETYPES)

            regex = New Regex("WHEN", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDWHEN, regex)
            Tokens.Add(TokenType.KEYWDWHEN)

            regex = New Regex("WHERE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDWHERE, regex)
            Tokens.Add(TokenType.KEYWDWHERE)

            regex = New Regex("WITH", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDWITH, regex)
            Tokens.Add(TokenType.KEYWDWITH)

            regex = New Regex("WHAT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDWHAT, regex)
            Tokens.Add(TokenType.KEYWDWHAT)

            regex = New Regex("WHICH", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDWHICH, regex)
            Tokens.Add(TokenType.KEYWDWHICH)

            regex = New Regex("WRITTEN AS", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDWRITTENAS, regex)
            Tokens.Add(TokenType.KEYWDWRITTENAS)

            regex = New Regex("\+", RegexOptions.Compiled)
            Patterns.Add(TokenType.PLUS, regex)
            Tokens.Add(TokenType.PLUS)

            regex = New Regex("-", RegexOptions.Compiled)
            Patterns.Add(TokenType.MINUS, regex)
            Tokens.Add(TokenType.MINUS)

            regex = New Regex("/", RegexOptions.Compiled)
            Patterns.Add(TokenType.DIVIDE, regex)
            Tokens.Add(TokenType.DIVIDE)

            regex = New Regex("\*", RegexOptions.Compiled)
            Patterns.Add(TokenType.TIMES, regex)
            Tokens.Add(TokenType.TIMES)

            regex = New Regex("(\+|-|/|\*)", RegexOptions.Compiled)
            Patterns.Add(TokenType.EXPRESSIONSYMBOL, regex)
            Tokens.Add(TokenType.EXPRESSIONSYMBOL)

            regex = New Regex("\s+", RegexOptions.Compiled)
            Patterns.Add(TokenType.WHITESPACE, regex)
            Tokens.Add(TokenType.WHITESPACE)



        End Sub

        Public Sub Init(ByVal input As String)
            Me.Input = input
            StartPos = 0
            EndPos = 0
            CurrentLine = 0
            CurrentColumn = 0
            CurrentPosition = 0
            Skipped = New List(Of Token)()
            LookAheadToken = Nothing
        End Sub

        Public Function GetToken(ByVal type As TokenType) As Token
            Dim t As New Token(Me.StartPos, Me.EndPos)
            t.Type = type
            Return t
        End Function

        ''' <summary>
        ''' executes a lookahead of the next token
        ''' and will advance the scan on the input string
        ''' </summary>
        ''' <returns></returns>
        Public Function Scan(ByVal ParamArray expectedtokens As TokenType()) As Token
            Dim tok As Token = LookAhead(expectedtokens)
            ' temporarely retrieve the lookahead
            LookAheadToken = Nothing
            ' reset lookahead token, so scanning will continue
            StartPos = tok.EndPos
            EndPos = tok.EndPos
            ' set the tokenizer to the new scan position
            Return tok
        End Function

        ''' <summary>
        ''' returns token with longest best match
        ''' </summary>
        ''' <returns></returns>
        Public Function LookAhead(ByVal ParamArray expectedtokens As TokenType()) As Token
            Dim i As Integer
            Dim start As Integer = StartPos
            Dim tok As Token = Nothing
            Dim scantokens As List(Of TokenType)

            ' this prevents double scanning and matching
            ' increased performance
            If LookAheadToken IsNot Nothing AndAlso LookAheadToken.Type <> TokenType._UNDETERMINED_ AndAlso LookAheadToken.Type <> TokenType._NONE_ Then
                Return LookAheadToken
            End If

            If expectedtokens.Length = 0 Then
                scantokens = Tokens
            Else
                scantokens = New List(Of TokenType)(expectedtokens)
                scantokens.AddRange(SkipList)
            End If

            Do
                Dim len As Integer = -1
                Dim index As TokenType = Integer.MaxValue
                Dim m_input As String

                If start > Input.Length Then
                    tok = New Token(start, start)
                    tok.Type = TokenType._UNDETERMINED_
                    Exit Do
                End If

                m_input = Input.Substring(start)

                tok = New Token(start, EndPos)


                For i = 0 To scantokens.Count - 1
                    Dim r As Regex = Patterns(scantokens(i))
                    Dim m As Match = r.Match(m_input)
                    If m.Success AndAlso m.Index = 0 AndAlso ((m.Length > len) OrElse (scantokens(i) < index AndAlso m.Length = len)) Then
                        len = m.Length
                        index = scantokens(i)
                        Exit For
                    End If
                Next i

                If index >= 0 AndAlso len >= 0 Then
                    tok.EndPos = start + len
                    If tok.StartPos + len <= Input.Length Then
                        tok.Text = Input.Substring(tok.StartPos, len)
                    End If
                    tok.Type = index
                Else
                    If tok.StartPos < tok.EndPos - 1 Then
                        tok.Text = Input.Substring(tok.StartPos, 1)
                    End If
                End If

                If SkipList.Contains(tok.Type) Then
                    start = tok.EndPos
                    Skipped.Add(tok)
                Else
                    tok.Skipped = Skipped
                    Skipped = New List(Of Token)
                End If
            Loop While SkipList.Contains(tok.Type)

            LookAheadToken = tok
            Return tok
        End Function
    End Class
#End Region

#Region "Token"

    Public Enum TokenType

        'Non terminal tokens:
        _NONE_      = 0
        _UNDETERMINED_= 1

        'Non terminal tokens:
        Atom        = 2
        ADDITIONALMODELELEMENT= 3
        ADDITIONALCOLUMNNAME= 4
        ADDITIONALCOMPARISON= 5
        ADDITIONALQUOTEDIDENTIFIER= 6
        ADDITIONALVALUE= 7
        BRACKTEDCOLMNLIST= 8
        COLUMNLIST  = 9
        COLUMNNAME  = 10
        COMPARISON  = 11
        COMPARISONLIST= 12
        DATATYPE    = 13
        DATATYPELENGTH= 14
        DATATYPEPRECISION= 15
        FACTPREDICATE= 16
        FACTREADING = 17
        FACTTYPENAMESTR= 18
        FACTTYPEPREDICATE= 19
        FACTTYPESIMPLEPREDICATE= 20
        INSERTCOLUMNLIST= 21
        MATCHPREDICATE= 22
        MATCHFACTTYPEPREDICATE= 23
        MODELELEMENT= 24
        MODELELEMENTPLURAL= 25
        MODELELEMENTSTR= 26
        MODELMODELELEMENT= 27
        NODESTMT    = 28
        NODE        = 29
        NODEPROPERTYIDENTIFICATION= 30
        NODEIDENTIFICATION= 31
        PREDICATECLAUSE= 32
        QUOTEDIDENTIFIER= 33
        QUOTEDIDENTIFIERLIST= 34
        REFERENCEMODECLAUSE= 35
        RETURNCLAUSE= 36
        RETURNFACTTYPEPREDICATE= 37
        RETURNPREDICATE= 38
        ROLENAMESTR = 39
        SETCLAUSE   = 40
        VALUELIST   = 41
        VALUESTRING = 42
        ADDENTITYTYPESTMT= 43
        ADDFACTSTMT = 44
        ADDFACTTYPESTMT= 45
        ADDROLESTMT = 46
        ADDMODELELEMENTSTMT= 47
        ADDVALUETYPESTMT= 48
        ASSERTSTMT  = 49
        BINARYFACTTYPEMANYTOONEDEFINITIONSTMT= 50
        CONSTRAINTEITHEROREXTERNAL= 51
        CONSTRAINTEITHERORSUBTYPE= 52
        CONSTRAINTEITHEROR= 53
        CONSTRAINTEXTERNALUNIQUENESS= 54
        CONSTRAINTINCLUSIVEOR= 55
        CONSTRAINTEXTERNALSTMT= 56
        CONSTRAINTMANDATORY= 57
        CREATECONCEPTSTMT= 58
        CREATEENTITYTYPESTMT= 59
        CREATEFACTTYPESTMT= 60
        CREATEMODELSTMT= 61
        CREATEMODELELEMENTSTMT= 62
        CREATESTMT  = 63
        CREATEVALUETYPESTMT= 64
        DELETESTMT  = 65
        DELETEFROMCLAUSE= 66
        DELETEALLSTMT= 67
        DELETEFACTSTMT= 68
        DERIVATIONSUBCLAUSE= 69
        DERIVATIONCLAUSE= 70
        DERIVEDFACTTYPESTMT= 71
        DESCRIBESTMT= 72
        DIDSELECTSTMT= 73
        ENTITYTYPEISIDENTIFIEDBYITSCLAUSE= 74
        ENUMERATESTMT= 75
        EXPRESSION  = 76
        EXISTSSTMT  = 77
        EXTERNALUNIQUENESSCONSTRAINTSTMT= 78
        FACTTYPEISWHERESTMT= 79
        FACTTYPESTMT= 80
        FACTTYPEIDENTIFICATION= 81
        FACTTYPEPARTCLAUSE= 82
        BINARYFACTTYPECLAUSE= 83
        FACTTYPEPRODUCTION= 84
        FACTSTMT    = 85
        GETSUPERTYPESTMT= 86
        INDIVIDUALIDENTIFIER= 87
        INMODELSTMT = 88
        INSERTSTMT  = 89
        ITISMANDATORYTHATSTMNT= 90
        LISTSTMT    = 91
        MATCHFACTTYPESTMT= 92
        MATCHSELECTSETFACTTYPESTMT= 93
        MATHCLAUSE  = 94
        MATCHSELECTSTMT= 95
        ONPAGESTMT  = 96
        OPENMODELSTMT= 97
        PREDICATENODEPROPERTYIDENTIFICATION= 98
        SELECTSTMT  = 99
        SHOWSTMT    = 100
        SUBTYPECLAUSE= 101
        SUBTYPESTMT = 102
        TABLEIDENTIFICATION= 103
        UPDATESTMT  = 104
        VALUETYPEISWRITTENASSTMT= 105
        WHERESTMT   = 106
        WHICHTHATCLAUSE= 107
        WHICHCLAUSE = 108
        WITHCLAUSE  = 109
        WHICHSELECTSTMT= 110
        WITHPREDICATESTMT= 111
        WRITTENASCLAUSE= 112
        Start       = 113

        'Terminal tokens:
        BROPEN      = 114
        BRCLOSE     = 115
        CARRET      = 116
        COLON       = 117
        COLUMNNAMESTR= 118
        COMMA       = 119
        CURLYBRACKETCLOSE= 120
        CURLYBRACKETOPEN= 121
        DOUBLEQUOTE = 122
        EMAILADDRESS= 123
        EOF         = 124
        EQUALS      = 125
        FACTTYPENAME= 126
        FOLLOWINGREADINGTEXT= 127
        IDENTIFIER  = 128
        MATHFUNCTION= 129
        MODELNAME   = 130
        MODELELEMENTNAME= 131
        MODELELEMENTSUFFIX= 132
        MODELID     = 133
        NUMBER      = 134
        PAGENAME    = 135
        PREBOUNDREADINGTEXT= 136
        POSTBOUNDREADINGTEXT= 137
        PREDICATE   = 138
        PREDICATESPACE= 139
        REFERENCEMODE= 140
        ROLENAME    = 141
        SINGLEQUOTE = 142
        SPACE       = 143
        STAR        = 144
        USERTABLENAME= 145
        WHERECLAUSECOLUMNNAMESTR= 146
        VALUE       = 147
        KEYWDA      = 148
        KEYWDAN     = 149
        KEYWDAND    = 150
        KEYWDADD    = 151
        KEYWDADDFACT= 152
        KEYWDADDFACTTYPE= 153
        KEYWDASSERT = 154
        KEYWDATMOSTONE= 155
        KEYWDBUTNOTBOTH= 156
        KEYWDCOMBINATION= 157
        KEYWDCOUNT  = 158
        KEYWDCOUNTSTAR= 159
        KEYWDCREATE = 160
        KEYWDCREATECONCEPT= 161
        KEYWDCREATEENTITYTYPE= 162
        KEYWDCREATEFACTTYPE= 163
        KEYWDCREATEMODEL= 164
        KEYWDCREATEVALUETYPE= 165
        KEYWDDATATYPELOGICALTRUEFALSE= 166
        KEYWDDATATYPELOGICALYESNO= 167
        KEYWDDATATYPEAUTOCOUNTER= 168
        KEYWDDATATYPEDECIMAL= 169
        KEYWDDATATYPEFLOATCUSTOMPRECISION= 170
        KEYWDDATATYPEFLOATDOUBLEPRECISION= 171
        KEYWDDATATYPEFLOATSINGLEPRECISION= 172
        KEYWDDATATYPEMONEY= 173
        KEYWDDATATYPESIGNEDBIGINTEGER= 174
        KEYWDDATATYPESIGNEDINTEGER= 175
        KEYWDDATATYPESIGNEDSMALLINTEGER= 176
        KEYWDDATATYPEUNSIGNEDBIGINTEGER= 177
        KEYWDDATATYPEUNSIGNEDINTEGER= 178
        KEYWDDATATYPEUNSIGNEDSMALLINTEGER= 179
        KEYWDDATATYPEUNSIGNEDTINYINTEGER= 180
        KEYWDDATATYPEOBJECTID= 181
        KEYWDDATATYPEROWID= 182
        KEYWDDATATYPERAWDATAFIXEDLENGTH= 183
        KEYWDDATATYPERAWDATALARGELENGTH= 184
        KEYWDDATATYPERAWDATAOLEOBJECT= 185
        KEYWDDATATYPERAWDATA= 186
        KEYWDDATATYPERAWDATAVARIABLELENGTH= 187
        KEYWDDATATYPEAUTOTIMESTAMP= 188
        KEYWDDATATYPEDATE= 189
        KEYWDDATATYPEDATETIME= 190
        KEYWDDATATYPETIME= 191
        KEYWDDATATYPESTRINGFIXEDLENGTH= 192
        KEYWDDATATYPESTRINGLARGELENGTH= 193
        KEYWDDATATYPESTRINGVARIABLELENGTH= 194
        KEYWDDELETE = 195
        KEYWDDELETEALL= 196
        KEYWDDELETEFACT= 197
        KEYWDDESCRIBE= 198
        KEYWDDID    = 199
        KEYWDDISTINCT= 200
        KEYWDEACH   = 201
        KEYWDEITHER = 202
        KEYWDENTITY = 203
        KEYWDENTITYTYPE= 204
        KEYWDENTITYTYPES= 205
        KEYWDENUMERATE= 206
        KEYWDEXISTS = 207
        KEYWDFACT   = 208
        KEYWDFACTTYPE= 209
        KEYWDFACTTYPES= 210
        KEYWDFOR    = 211
        KEYWDFOREACH= 212
        KEYWDFROM   = 213
        KEYWDGET    = 214
        KEYWDIFANDONLYIF= 215
        KEYWDIN     = 216
        KEYWDINSERT = 217
        KEYWDINTO   = 218
        KEYWDIS     = 219
        KEYWDISA    = 220
        KEYWDISAKINDOF= 221
        KEYWDISIDENTIFIEDBYITS= 222
        KEYWDISNOT  = 223
        KEYWDISWHERE= 224
        KEYWDISWRITTENAS= 225
        KEYWDITISMANDATORYTHAT= 226
        KEYWDJOINING= 227
        KEYWDINDEX  = 228
        KEYWDLANGUAGE= 229
        KEYWDLANGUAGEDFD= 230
        KEYWDLANGUAGEERD= 231
        KEYWDLANGUAGEETD= 232
        KEYWDLANGUAGEORM= 233
        KEYWDLANGUAGESTD= 234
        KEYWDLANGUAGEUCD= 235
        KEYWDLIST   = 236
        KEYWDMATCH  = 237
        KEYWDMODEL  = 238
        KEYWDMODELNOTES= 239
        KEYWDMODELDICTIONARY= 240
        KEYWDNULL   = 241
        KEYWDOBJECT = 242
        KEYWDOCCURSATLEASTONETIME= 243
        KEYWDOCCURSATLEASTONETIMEINEACHOF= 244
        KEYWDOF     = 245
        KEYWDON     = 246
        KEYWDONE    = 247
        KEYWDONPAGE = 248
        KEYWDOPEN   = 249
        KEYWDOR     = 250
        KEYWDPAGE   = 251
        KEYWDPREDICATE= 252
        KEYWDRETURN = 253
        KEYWDROLE   = 254
        KEYWDSELECT = 255
        KEYWDRESTRICTEDTO= 256
        KEYWDROLECONSTRAINTS= 257
        KEYWDSET    = 258
        KEYWDSHOW   = 259
        KEYWDSUPERTYPE= 260
        KEYWDTHAT   = 261
        KEYWDTO     = 262
        KEYWDUPDATE = 263
        KEYWDVALUES = 264
        KEYWDVALUETYPE= 265
        KEYWDVALUETYPES= 266
        KEYWDWHEN   = 267
        KEYWDWHERE  = 268
        KEYWDWITH   = 269
        KEYWDWHAT   = 270
        KEYWDWHICH  = 271
        KEYWDWRITTENAS= 272
        PLUS        = 273
        MINUS       = 274
        DIVIDE      = 275
        TIMES       = 276
        EXPRESSIONSYMBOL= 277
        WHITESPACE  = 278
    End Enum

    <Serializable()> _
    Public Class Token 
        Private m_startPos As Integer
        Private m_endPos As Integer
        Private m_text As String
        Private m_value As Object

        ' contains all prior skipped symbols
        Private m_skipped As List(Of Token)


        Public Property StartPos() As Integer
            Get
                Return m_startPos
            End Get
            Set(ByVal value As Integer)
                m_startPos = value
            End Set
        End Property

        Public Property EndPos() As Integer
            Get
                Return m_endPos
            End Get
            Set(ByVal value As Integer)
                m_endPos = value
            End Set
        End Property

        Public ReadOnly Property Length() As Integer
            Get
                Return m_endPos - m_startPos
            End Get
        End Property

        Public Property Text() As String
            Get
                Return m_text
            End Get
            Set(ByVal value As String)
                m_text = value
            End Set
        End Property

        Public Property Skipped() As List(Of Token)
            Get
                Return m_skipped
            End Get
            Set(ByVal value As List(Of Token))
                m_skipped = value
            End Set
        End Property

        Public Property Value() As Object
            Get
                Return m_value
            End Get
            Set(ByVal value As Object)
                Me.m_value = value
            End Set
        End Property

        <XmlAttribute()> _
        Public Type As TokenType

        Public Sub New()
            Me.New(0, 0)
        End Sub

        Public Sub New(ByVal start As Integer, ByVal endPos As Integer)
            Type = TokenType._UNDETERMINED_
            m_startPos = start
            m_endPos = endPos
            Text = ""
            ' must initialize with empty string, may cause null reference exceptions otherwise
            Value = Nothing
        End Sub

        Public Sub UpdateRange(ByVal token As Token)
            If token.StartPos < m_startPos Then
                m_startPos = token.StartPos
            End If
            If token.EndPos > m_endPos Then
                m_endPos = token.EndPos
            End If
        End Sub

        Public Overloads Overrides Function ToString() As String
            If Text <> Nothing Then
                Return Type.ToString() + " '" + Text + "'"
            Else
                Return Type.ToString()
            End If
        End Function
    End Class
#End Region
End Namespace
