' Generated by TinyPG v1.3 available at www.codeproject.com

Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Text
Imports System.Xml.Serialization


Namespace VAQL
#Region "ParseTree"
    <Serializable()>
    Public Class ParseErrors
        Inherits List(Of ParseError)

        Public Sub New()
        End Sub

    End Class

    <Serializable()>
    Public Class ParseError 
        Implements ICloneable

        Private m_message As String
        Private m_code As Integer
        Private m_line As Integer
        Private m_col As Integer
        Private m_pos As Integer
        Private m_length As Integer
        Private m_expected_token As String = ""

        Public ReadOnly Property Code() As Integer
            Get
                Return m_code
            End Get
        End Property

        Public ReadOnly Property Line() As Integer
            Get
                Return m_line
            End Get
        End Property

        Public ReadOnly Property Column() As Integer
            Get
                Return m_col
            End Get
        End Property

        Public ReadOnly Property Position() As Integer
            Get
                Return m_pos
            End Get
        End Property

        Public ReadOnly Property Length() As Integer
            Get
                Return m_length
            End Get
        End Property

        Public ReadOnly Property Message() As String
            Get
                Return m_message
            End Get
        End Property

        Public Property ExpectedToken As String
            Get
                Return Me.m_expected_token
            End Get
            Set(ByVal value As String)
                Me.m_expected_token = value
            End Set
        End Property

        ''' <summary>
        ''' Parameterless constructor.
        ''' </summary>
        Public Sub New()
        End Sub

        Public Sub New(ByVal message As Integer,
                       ByVal code As Integer)

        End Sub

        Public Sub New(ByVal message As String,
                       ByVal code As Integer,
                       ByVal line As Integer,
                       ByVal col As Integer,
                       ByVal pos As Integer,
                       ByVal length As Integer,
                       Optional ByVal asExpectedToken As String = "")
            m_message = message
            m_code = code
            m_line = line
            m_col = col
            m_pos = pos
            m_length = length
            m_expected_token = asExpectedToken
        End Sub

        Public Sub New(ByVal message As String, ByVal code As Integer, ByVal node As ParseNode)
            Me.New(message, code, 0, node.Token.StartPos, node.Token.StartPos, node.Token.Length)
        End Sub

        Public Function Clone() As Object Implements ICloneable.Clone

            Dim lrParseError As New ParseError

            With Me
                lrParseError.m_message = .m_message
                lrParseError.m_code = .m_code
                lrParseError.m_line = .m_line
                lrParseError.m_col = .m_col
                lrParseError.m_pos = .m_pos
                lrParseError.m_length = .m_length
                lrParseError.m_expected_token = m_expected_token
            End With

            Return lrParseError

        End Function
    End Class

    ' rootlevel of the node tree
    <Serializable()> _
    Partial Public Class ParseTree
        Inherits ParseNode

        Public Errors As ParseErrors
        Public Optionals As ParseErrors

        Public Skipped As List(Of Token)

        Public Sub New()
            MyBase.New(New Token(), "ParseTree")
            Token.Type = TokenType.Start
            Token.Text = "Root"
            Skipped = New List(Of Token)()
            Errors = New ParseErrors()
            Optionals = New ParseErrors()
        End Sub

        Public Function MaxDistance() As Integer

            Dim lrNode As ParseNode = Nothing
            Dim liMaxDistance As Integer = 0
            Dim liTempMaxDistance As Integer = 0

            For Each lrNode In Me.Nodes.ToArray
                liTempMaxDistance = lrNode.MaxDistance()
                If liTempMaxDistance > liMaxDistance Then
                    liMaxDistance = liTempMaxDistance
                End If
            Next

            Return liMaxDistance

        End Function

        Public Function PrintTree() As String
    Dim sb As New StringBuilder()
            Dim indent As Integer = 0
            PrintNode(sb, Me, indent)
            Return sb.ToString()
        End Function

        Private Sub PrintNode(ByVal sb As StringBuilder, ByVal node As ParseNode, ByVal indent As Integer)

            Dim space As String = "".PadLeft(indent, " "c)

            sb.Append(space)
            sb.AppendLine(node.Text)

            For Each n As ParseNode In node.Nodes
                PrintNode(sb, n, indent + 2)
            Next
        End Sub

        ''' <summary>
        ''' this is the entry point for executing and evaluating the parse tree.
        ''' </summary>
        ''' <param name="paramlist">additional optional input parameters</param>
        ''' <returns>the output of the evaluation function</returns>
        Public Overloads Function Eval(ByVal ParamArray paramlist As Object()) As Object
        Return Nodes(0).Eval(Me, paramlist)
        End Function

        Public Overloads Function Clone(Optional ByVal abLeaveOptionals As Boolean = False) As Object
            Dim lrTree As New ParseTree
            Dim lrParseError As ParseError
            Dim lrToken As Token
            Dim lrNode As ParseNode

            With Me
                Try
                    For Each lrNode In .Nodes.ToArray
                        lrTree.m_nodes.Add(lrNode.Clone)
                    Next

                    lrTree.Errors = New ParseErrors
                    Try
                        For Each lrParseError In .Errors
                            lrTree.Errors.Add(lrParseError.Clone)
                        Next
                    Catch ex As Exception
                        'Move on
                    End Try

                    Try
                        For Each lrParseError In .Optionals
                            lrTree.Optionals.Add(lrParseError.Clone)
                        Next
                    Catch ex As Exception
                        'Move on
                    End Try


                    lrTree.Skipped = New List(Of Token)
                    For Each lrToken In .Skipped.ToArray
                        lrTree.Skipped.Add(lrToken.Clone)
                    Next

                    lrTree.GUID = .GUID
                    lrTree.Text = .Text

                    If .Parent IsNot Nothing Then
                        lrTree.Parent = .Parent.Clone
                    End If

                    lrTree.Token = .Token.Clone

                Catch ex As Exception
                    'Not much we can do here
                End Try
            End With

            Return lrTree

        End Function
    End Class
#End Region

#Region "ParseNode"
    <Serializable()>
    Partial Public Class ParseNode 
        Implements ICloneable
        Implements IEquatable(Of ParseNode)
        Protected m_text As String
        Protected m_nodes As List(Of ParseNode)
        Protected GUID As String = System.Guid.NewGuid.ToString
        

        Public ReadOnly Property Nodes() As List(Of ParseNode)
            Get
                Return m_nodes
            End Get
        End Property

        
        <XMLIgnore()>
        Public Parent As ParseNode
        Public Token As Token
        ' the token/rule
        <XmlIgnore()>
        Public Property Text() As String
            ' text to display in parse tree 
            Get
                Return m_text
            End Get
            Set(ByVal value As String)
                m_text = value
            End Set
        End Property

        Public Sub New()

        End Sub

        Public Overridable Function CreateNode(ByVal token As Token, ByVal text As String) As ParseNode
            Dim node As New ParseNode(token, text)
            node.Parent = Me
            Return node
        End Function

        Protected Sub New(ByVal token As Token, ByVal text As String)
            Me.Token = token
            m_text = text
            m_nodes = New List(Of ParseNode)()
        End Sub

        Public Function MaxDistance() As Integer

            Dim lrNode As ParseNode = Nothing
            Dim liTempMaxDistance As Integer = 0
            Dim liMaxDistance As Integer = Me.Token.EndPos

            For Each lrNode In Me.Nodes.ToArray
                liTempMaxDistance = lrNode.MaxDistance()
                If liTempMaxDistance > liMaxDistance Then
                    liMaxDistance = liTempMaxDistance
                End If
            Next

            Return liMaxDistance

        End Function

        Protected Function GetValue(ByVal tree As ParseTree, ByVal type As TokenType, ByVal index As Integer) As Object
            Return GetValueByRef(tree, type, index)
        End Function

        Protected Function GetValueByRef(ByVal tree As ParseTree, ByVal type As TokenType, ByRef index As Integer) As Object
            Dim o As Object = Nothing
            If index < 0 Then
                Return o
            End If

            ' left to right
            For Each node As ParseNode In Nodes
                If node.Token.Type = type Then
                    System.Math.Max(System.Threading.Interlocked.Decrement(index), index + 1)
                    If index < 0 Then
                        o = node.Eval(tree)
                        Exit For
                    End If
                End If
            Next
            Return o
        End Function

        ''' <summary>
        ''' this implements the evaluation functionality, cannot be used directly
        ''' </summary>
        ''' <param name="tree">the parsetree itself</param>
        ''' <param name="paramlist">optional input parameters</param>
        ''' <returns>a partial result of the evaluation</returns>
        Friend Function Eval(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Dim Value As Object = Nothing

            Select Case Token.Type
                Case TokenType.ADDITIONALVALUE
                    Value = EvalADDITIONALVALUE(tree, paramlist)
                    Exit Select
                Case TokenType.VALUELIST
                    Value = EvalVALUELIST(tree, paramlist)
                    Exit Select
                Case TokenType.VALUESTRING
                    Value = EvalVALUESTRING(tree, paramlist)
                    Exit Select
                Case TokenType.NATURALLANGUAGEPROMPT
                    Value = EvalNATURALLANGUAGEPROMPT(tree, paramlist)
                    Exit Select
                Case TokenType.ADDITIONALVALUECONSTRAINTVALUE
                    Value = EvalADDITIONALVALUECONSTRAINTVALUE(tree, paramlist)
                    Exit Select
                Case TokenType.BINARYFACTTYPEANYNUMBEROFCLAUSE
                    Value = EvalBINARYFACTTYPEANYNUMBEROFCLAUSE(tree, paramlist)
                    Exit Select
                Case TokenType.BINARYFACTTYPEATLEASTONECLAUSE
                    Value = EvalBINARYFACTTYPEATLEASTONECLAUSE(tree, paramlist)
                    Exit Select
                Case TokenType.BINARYFACTTYPEATMOSTONECLAUSE
                    Value = EvalBINARYFACTTYPEATMOSTONECLAUSE(tree, paramlist)
                    Exit Select
                Case TokenType.BINARYFACTTYPEMANYTOONEDEFINITIONCLAUSE
                    Value = EvalBINARYFACTTYPEMANYTOONEDEFINITIONCLAUSE(tree, paramlist)
                    Exit Select
                Case TokenType.BINARYPREDICATECLAUSE
                    Value = EvalBINARYPREDICATECLAUSE(tree, paramlist)
                    Exit Select
                Case TokenType.DATATYPE
                    Value = EvalDATATYPE(tree, paramlist)
                    Exit Select
                Case TokenType.DATATYPELENGTH
                    Value = EvalDATATYPELENGTH(tree, paramlist)
                    Exit Select
                Case TokenType.DATATYPEPRECISION
                    Value = EvalDATATYPEPRECISION(tree, paramlist)
                    Exit Select
                Case TokenType.ENTITYTYPEISIDENTIFIEDBYITSCLAUSE
                    Value = EvalENTITYTYPEISIDENTIFIEDBYITSCLAUSE(tree, paramlist)
                    Exit Select
                Case TokenType.ENTITYTYPEIDENTIFIEDBYITSCLAUSE
                    Value = EvalENTITYTYPEIDENTIFIEDBYITSCLAUSE(tree, paramlist)
                    Exit Select
                Case TokenType.FACTCLAUSE
                    Value = EvalFACTCLAUSE(tree, paramlist)
                    Exit Select
                Case TokenType.FACTTYPECLAUSE
                    Value = EvalFACTTYPECLAUSE(tree, paramlist)
                    Exit Select
                Case TokenType.FRONTREADINGTEXTCLAUSE
                    Value = EvalFRONTREADINGTEXTCLAUSE(tree, paramlist)
                    Exit Select
                Case TokenType.IDENTIFIERMODELELEMENT
                    Value = EvalIDENTIFIERMODELELEMENT(tree, paramlist)
                    Exit Select
                Case TokenType.ISACONCEPTCLAUSE
                    Value = EvalISACONCEPTCLAUSE(tree, paramlist)
                    Exit Select
                Case TokenType.ISANENTITYTYPECLAUSE
                    Value = EvalISANENTITYTYPECLAUSE(tree, paramlist)
                    Exit Select
                Case TokenType.ISAVALUETYPECLAUSE
                    Value = EvalISAVALUETYPECLAUSE(tree, paramlist)
                    Exit Select
                Case TokenType.ISWHERECLAUSE
                    Value = EvalISWHERECLAUSE(tree, paramlist)
                    Exit Select
                Case TokenType.MODELELEMENT
                    Value = EvalMODELELEMENT(tree, paramlist)
                    Exit Select
                Case TokenType.MODELELEMENTTYPE
                    Value = EvalMODELELEMENTTYPE(tree, paramlist)
                    Exit Select
                Case TokenType.OBJECTIFIEDFACTTYPEISIDENTIFIEDBYITSCLAUSE
                    Value = EvalOBJECTIFIEDFACTTYPEISIDENTIFIEDBYITSCLAUSE(tree, paramlist)
                    Exit Select
                Case TokenType.PREDICATECLAUSE
                    Value = EvalPREDICATECLAUSE(tree, paramlist)
                    Exit Select
                Case TokenType.QUOTEDMODELELEMENTNAME
                    Value = EvalQUOTEDMODELELEMENTNAME(tree, paramlist)
                    Exit Select
                Case TokenType.UNARYPREDICATECLAUSE
                    Value = EvalUNARYPREDICATECLAUSE(tree, paramlist)
                    Exit Select
                Case TokenType.VALUECONSTRAINTCLAUSE
                    Value = EvalVALUECONSTRAINTCLAUSE(tree, paramlist)
                    Exit Select
                Case TokenType.VALUECONSTRAINTVALUELIST
                    Value = EvalVALUECONSTRAINTVALUELIST(tree, paramlist)
                    Exit Select
                Case TokenType.VALUETYPEISWRITTENASCLAUSE
                    Value = EvalVALUETYPEISWRITTENASCLAUSE(tree, paramlist)
                    Exit Select
                Case TokenType.VALUETYPEWRITTENASCLAUSE
                    Value = EvalVALUETYPEWRITTENASCLAUSE(tree, paramlist)
                    Exit Select
                Case TokenType.ADDOBJECTTYPESRELATEDTOMODELELEMENTTOPAGESTMT
                    Value = EvalADDOBJECTTYPESRELATEDTOMODELELEMENTTOPAGESTMT(tree, paramlist)
                    Exit Select
                Case TokenType.ADDOBJECTTYPETOPAGESTMT
                    Value = EvalADDOBJECTTYPETOPAGESTMT(tree, paramlist)
                    Exit Select
                Case TokenType.CREATEPAGESTMT
                    Value = EvalCREATEPAGESTMT(tree, paramlist)
                    Exit Select
                Case TokenType.CREATESTMT
                    Value = EvalCREATESTMT(tree, paramlist)
                    Exit Select
                Case TokenType.FACTSTMT
                    Value = EvalFACTSTMT(tree, paramlist)
                    Exit Select
                Case TokenType.FACTTYPEIDENTIFICATION
                    Value = EvalFACTTYPEIDENTIFICATION(tree, paramlist)
                    Exit Select
                Case TokenType.FACTTYPESTMT
                    Value = EvalFACTTYPESTMT(tree, paramlist)
                    Exit Select
                Case TokenType.FACTREADINGSTMT
                    Value = EvalFACTREADINGSTMT(tree, paramlist)
                    Exit Select
                Case TokenType.MODELELEMENTLEADINGSTMT
                    Value = EvalMODELELEMENTLEADINGSTMT(tree, paramlist)
                    Exit Select
                Case TokenType.BASEPRODUCTION
                    Value = EvalBASEPRODUCTION(tree, paramlist)
                    Exit Select
                Case TokenType.Start
                    Value = EvalStart(tree, paramlist)
                    Exit Select

                Case Else
                    Value = Token.Text
                    Exit Select
            End Select
            Return Value
        End Function

        Public Function Equals(other As ParseNode) As Boolean Implements IEquatable(Of ParseNode).Equals
            Return Me.GUID = other.GUID
        End Function

        Public Function Clone() As Object Implements ICloneable.Clone
            Dim lrParseNode As New ParseNode
            Dim lrSubParseNode As ParseNode

            With Me
                lrParseNode.m_text = .m_text
                lrParseNode.m_nodes = New List(Of ParseNode)
                For Each lrSubParseNode In .m_nodes
                    lrParseNode.m_nodes.Add(lrSubParseNode.Clone)
                Next
                lrParseNode.Token = .Token.Clone
                lrParseNode.GUID = .GUID
            End With
            Return lrParseNode
        End Function

                Protected Overridable Function EvalADDITIONALVALUE(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalVALUELIST(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalVALUESTRING(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalNATURALLANGUAGEPROMPT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalADDITIONALVALUECONSTRAINTVALUE(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalBINARYFACTTYPEANYNUMBEROFCLAUSE(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalBINARYFACTTYPEATLEASTONECLAUSE(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalBINARYFACTTYPEATMOSTONECLAUSE(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalBINARYFACTTYPEMANYTOONEDEFINITIONCLAUSE(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalBINARYPREDICATECLAUSE(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalDATATYPE(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalDATATYPELENGTH(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalDATATYPEPRECISION(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalENTITYTYPEISIDENTIFIEDBYITSCLAUSE(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalENTITYTYPEIDENTIFIEDBYITSCLAUSE(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalFACTCLAUSE(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalFACTTYPECLAUSE(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalFRONTREADINGTEXTCLAUSE(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalIDENTIFIERMODELELEMENT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalISACONCEPTCLAUSE(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalISANENTITYTYPECLAUSE(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalISAVALUETYPECLAUSE(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalISWHERECLAUSE(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalMODELELEMENT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalMODELELEMENTTYPE(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalOBJECTIFIEDFACTTYPEISIDENTIFIEDBYITSCLAUSE(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalPREDICATECLAUSE(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalQUOTEDMODELELEMENTNAME(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalUNARYPREDICATECLAUSE(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalVALUECONSTRAINTCLAUSE(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalVALUECONSTRAINTVALUELIST(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalVALUETYPEISWRITTENASCLAUSE(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalVALUETYPEWRITTENASCLAUSE(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalADDOBJECTTYPESRELATEDTOMODELELEMENTTOPAGESTMT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalADDOBJECTTYPETOPAGESTMT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalCREATEPAGESTMT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalCREATESTMT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalFACTSTMT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalFACTTYPEIDENTIFICATION(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalFACTTYPESTMT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalFACTREADINGSTMT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalMODELELEMENTLEADINGSTMT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalBASEPRODUCTION(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalStart(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Return "Could not interpret input; no semantics implemented."
        End Function



    End Class
#End Region
End Namespace

