' Generated by TinyPG v1.3 available at www.codeproject.com

Imports System
Imports System.Collections.Generic
Imports System.Text.RegularExpressions
Imports System.Xml.Serialization


Namespace VAQL
#Region "Scanner"

    Partial Public Class Scanner
        Public Input As String
        Public StartPos As Integer = 0
        Public EndPos As Integer = 0
        Public CurrentLine As Integer
        Public CurrentColumn As Integer
        Public CurrentPosition As Integer
        Public Skipped As List(Of Token) ' tokens that were skipped
        Public Patterns As Dictionary(Of TokenType, Regex)

        Private LookAheadToken As Token
        Private Tokens As List(Of TokenType)
        Private SkipList As List(Of TokenType) ' tokens to be skipped

        Public Sub New()
            Dim regex As Regex
            Patterns = New Dictionary(Of TokenType, Regex)()
            Tokens = New List(Of TokenType)()
            LookAheadToken = Nothing
            Skipped = New List(Of Token)()

            SkipList = New List(Of TokenType)()
            SkipList.Add(TokenType.WHITESPACE)

            regex = new Regex("\(+", RegexOptions.Compiled)
            Patterns.Add(TokenType.BROPEN, regex)
            Tokens.Add(TokenType.BROPEN)

            regex = new Regex("\)+", RegexOptions.Compiled)
            Patterns.Add(TokenType.BRCLOSE, regex)
            Tokens.Add(TokenType.BRCLOSE)

            regex = new Regex(":", RegexOptions.Compiled)
            Patterns.Add(TokenType.COLON, regex)
            Tokens.Add(TokenType.COLON)

            regex = new Regex("[aA-zZ0-9]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.COLUMNNAMESTR, regex)
            Tokens.Add(TokenType.COLUMNNAMESTR)

            regex = new Regex(",", RegexOptions.Compiled)
            Patterns.Add(TokenType.COMMA, regex)
            Tokens.Add(TokenType.COMMA)

            regex = new Regex("\}+", RegexOptions.Compiled)
            Patterns.Add(TokenType.CURLYBRACKETCLOSE, regex)
            Tokens.Add(TokenType.CURLYBRACKETCLOSE)

            regex = new Regex("\{+", RegexOptions.Compiled)
            Patterns.Add(TokenType.CURLYBRACKETOPEN, regex)
            Tokens.Add(TokenType.CURLYBRACKETOPEN)

            regex = new Regex("""", RegexOptions.Compiled)
            Patterns.Add(TokenType.DOUBLEQUOTE, regex)
            Tokens.Add(TokenType.DOUBLEQUOTE)

            regex = new Regex("^$", RegexOptions.Compiled)
            Patterns.Add(TokenType.EOF, regex)
            Tokens.Add(TokenType.EOF)

            regex = new Regex("=", RegexOptions.Compiled)
            Patterns.Add(TokenType.EQUALS, regex)
            Tokens.Add(TokenType.EQUALS)

            regex = new Regex("[aA-zZ]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.FACTTYPENAME, regex)
            Tokens.Add(TokenType.FACTTYPENAME)

            regex = new Regex("[a-z|\s]+$", RegexOptions.Compiled)
            Patterns.Add(TokenType.FOLLOWINGREADINGTEXT, regex)
            Tokens.Add(TokenType.FOLLOWINGREADINGTEXT)

            regex = new Regex("(?>[a-z]+)[^\-]", RegexOptions.Compiled)
            Patterns.Add(TokenType.FRONTREADINGTEXT, regex)
            Tokens.Add(TokenType.FRONTREADINGTEXT)

            regex = new Regex("[aA-zZ0-9]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.ID, regex)
            Tokens.Add(TokenType.ID)

            regex = new Regex("\*|/", RegexOptions.Compiled)
            Patterns.Add(TokenType.MULTDIV, regex)
            Tokens.Add(TokenType.MULTDIV)

            regex = new Regex("[aA-zZ]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.MODELNAME, regex)
            Tokens.Add(TokenType.MODELNAME)

            regex = new Regex("(([A-Z][a-z]+)+[\s]?)+", RegexOptions.Compiled)
            Patterns.Add(TokenType.MODELELEMENTNAME, regex)
            Tokens.Add(TokenType.MODELELEMENTNAME)

            regex = new Regex("[aA-zZ0-9\-]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.MODELID, regex)
            Tokens.Add(TokenType.MODELID)

            regex = new Regex("[0-9]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.NUMBER, regex)
            Tokens.Add(TokenType.NUMBER)

            regex = new Regex("[aA-zZ0-9\s\-]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.PAGENAME, regex)
            Tokens.Add(TokenType.PAGENAME)

            regex = new Regex("(\+|-)", RegexOptions.Compiled)
            Patterns.Add(TokenType.PLUSMINUS, regex)
            Tokens.Add(TokenType.PLUSMINUS)

            regex = new Regex("\-[a-z]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.POSTBOUNDREADINGTEXT, regex)
            Tokens.Add(TokenType.POSTBOUNDREADINGTEXT)

            regex = new Regex("[a-z]+\-", RegexOptions.Compiled)
            Patterns.Add(TokenType.PREBOUNDREADINGTEXT, regex)
            Tokens.Add(TokenType.PREBOUNDREADINGTEXT)

            regex = new Regex("(?!([a-z]+\-))(?!([a-z\s]+$))([a-z]+[^\-])", RegexOptions.Compiled)
            Patterns.Add(TokenType.PREDICATEPART, regex)
            Tokens.Add(TokenType.PREDICATEPART)

            regex = new Regex("[\s]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.PREDICATESPACE, regex)
            Tokens.Add(TokenType.PREDICATESPACE)

            regex = new Regex("[A-Z][aA-zZ]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.REFERENCEMODE, regex)
            Tokens.Add(TokenType.REFERENCEMODE)

            regex = new Regex("[a-z]+\-?", RegexOptions.Compiled)
            Patterns.Add(TokenType.ROLENAME, regex)
            Tokens.Add(TokenType.ROLENAME)

            regex = new Regex("'", RegexOptions.Compiled)
            Patterns.Add(TokenType.SINGLEQUOTE, regex)
            Tokens.Add(TokenType.SINGLEQUOTE)

            regex = new Regex("\*", RegexOptions.Compiled)
            Patterns.Add(TokenType.STAR, regex)
            Tokens.Add(TokenType.STAR)

            regex = new Regex("\s", RegexOptions.Compiled)
            Patterns.Add(TokenType.SPACE, regex)
            Tokens.Add(TokenType.SPACE)

            regex = new Regex("((?>[a-z])+[\s]?)+$", RegexOptions.Compiled)
            Patterns.Add(TokenType.UNARYPREDICATEPART, regex)
            Tokens.Add(TokenType.UNARYPREDICATEPART)

            regex = new Regex("[aA-zZ0-9]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.USERTABLENAME, regex)
            Tokens.Add(TokenType.USERTABLENAME)

            regex = new Regex("[aA-zZ0-9]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.WHERECLAUSECOLUMNNAMESTR, regex)
            Tokens.Add(TokenType.WHERECLAUSECOLUMNNAMESTR)

            regex = new Regex("[aA-zZ0-9\-\s+\#\*\?]*", RegexOptions.Compiled)
            Patterns.Add(TokenType.VALUE, regex)
            Tokens.Add(TokenType.VALUE)

            regex = new Regex("AT MOST ONE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDATMOSTONE, regex)
            Tokens.Add(TokenType.KEYWDATMOSTONE)

            regex = new Regex("LogicalTrueFalse", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPELOGICALTRUEFALSE, regex)
            Tokens.Add(TokenType.KEYWDDATATYPELOGICALTRUEFALSE)

            regex = new Regex("LogicalYesNo", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPELOGICALYESNO, regex)
            Tokens.Add(TokenType.KEYWDDATATYPELOGICALYESNO)

            regex = new Regex("AutoCounter", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEAUTOCOUNTER, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEAUTOCOUNTER)

            regex = new Regex("Decimal", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEDECIMAL, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEDECIMAL)

            regex = new Regex("FloatCustomPrecision", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEFLOATCUSTOMPRECISION, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEFLOATCUSTOMPRECISION)

            regex = new Regex("FloatDoublePrecision", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEFLOATDOUBLEPRECISION, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEFLOATDOUBLEPRECISION)

            regex = new Regex("FloatSinglePrecision", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEFLOATSINGLEPRECISION, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEFLOATSINGLEPRECISION)

            regex = new Regex("Money", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEMONEY, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEMONEY)

            regex = new Regex("SignedBigInteger", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPESIGNEDBIGINTEGER, regex)
            Tokens.Add(TokenType.KEYWDDATATYPESIGNEDBIGINTEGER)

            regex = new Regex("SignedInteger", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPESIGNEDINTEGER, regex)
            Tokens.Add(TokenType.KEYWDDATATYPESIGNEDINTEGER)

            regex = new Regex("SignedSmallInteger", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPESIGNEDSMALLINTEGER, regex)
            Tokens.Add(TokenType.KEYWDDATATYPESIGNEDSMALLINTEGER)

            regex = new Regex("UnsignedBigInteger", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEUNSIGNEDBIGINTEGER, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEUNSIGNEDBIGINTEGER)

            regex = new Regex("UnsignedInteger", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEUNSIGNEDINTEGER, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEUNSIGNEDINTEGER)

            regex = new Regex("UnsignedSmallInteger", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEUNSIGNEDSMALLINTEGER, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEUNSIGNEDSMALLINTEGER)

            regex = new Regex("UnsignedTinyInteger", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEUNSIGNEDTINYINTEGER, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEUNSIGNEDTINYINTEGER)

            regex = new Regex("ObjectID", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEOBJECTID, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEOBJECTID)

            regex = new Regex("RowID", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEROWID, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEROWID)

            regex = new Regex("RawDataFixedLength", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPERAWDATAFIXEDLENGTH, regex)
            Tokens.Add(TokenType.KEYWDDATATYPERAWDATAFIXEDLENGTH)

            regex = new Regex("RawDataLargeLength", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPERAWDATALARGELENGTH, regex)
            Tokens.Add(TokenType.KEYWDDATATYPERAWDATALARGELENGTH)

            regex = new Regex("RawDataOLEObject", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPERAWDATAOLEOBJECT, regex)
            Tokens.Add(TokenType.KEYWDDATATYPERAWDATAOLEOBJECT)

            regex = new Regex("RawDataPicture", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPERAWDATA, regex)
            Tokens.Add(TokenType.KEYWDDATATYPERAWDATA)

            regex = new Regex("VariableLength", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPERAWDATAVARIABLELENGTH, regex)
            Tokens.Add(TokenType.KEYWDDATATYPERAWDATAVARIABLELENGTH)

            regex = new Regex("AutoTimestamp", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEAUTOTIMESTAMP, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEAUTOTIMESTAMP)

            regex = new Regex("Date", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEDATE, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEDATE)

            regex = new Regex("DateTime", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPEDATETIME, regex)
            Tokens.Add(TokenType.KEYWDDATATYPEDATETIME)

            regex = new Regex("Time", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPETIME, regex)
            Tokens.Add(TokenType.KEYWDDATATYPETIME)

            regex = new Regex("StringFixedLength", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPESTRINGFIXEDLENGTH, regex)
            Tokens.Add(TokenType.KEYWDDATATYPESTRINGFIXEDLENGTH)

            regex = new Regex("StringLargeLength", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPESTRINGLARGELENGTH, regex)
            Tokens.Add(TokenType.KEYWDDATATYPESTRINGLARGELENGTH)

            regex = new Regex("StringVariableLength", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDATATYPESTRINGVARIABLELENGTH, regex)
            Tokens.Add(TokenType.KEYWDDATATYPESTRINGVARIABLELENGTH)

            regex = new Regex("IS A CONCEPT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDISACONCEPT, regex)
            Tokens.Add(TokenType.KEYWDISACONCEPT)

            regex = new Regex("IS AN ENTITY TYPE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDISANENTITYTYPE, regex)
            Tokens.Add(TokenType.KEYWDISANENTITYTYPE)

            regex = new Regex("IS IDENTIFIED BY ITS", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDISIDENTIFIEDBYITS, regex)
            Tokens.Add(TokenType.KEYWDISIDENTIFIEDBYITS)

            regex = new Regex("IS WRITTEN AS", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDISWRITTENAS, regex)
            Tokens.Add(TokenType.KEYWDISWRITTENAS)

            regex = new Regex("NL:", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDNL, regex)
            Tokens.Add(TokenType.KEYWDNL)

            regex = new Regex("ONE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDONE, regex)
            Tokens.Add(TokenType.KEYWDONE)

            regex = new Regex("READING", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDREADING, regex)
            Tokens.Add(TokenType.KEYWDREADING)

            regex = new Regex("\s+", RegexOptions.Compiled)
            Patterns.Add(TokenType.WHITESPACE, regex)
            Tokens.Add(TokenType.WHITESPACE)



        End Sub

        Public Sub Init(ByVal input As String)
            Me.Input = input
            StartPos = 0
            EndPos = 0
            CurrentLine = 0
            CurrentColumn = 0
            CurrentPosition = 0
            Skipped = New List(Of Token)()
            LookAheadToken = Nothing
        End Sub

        Public Function GetToken(ByVal type As TokenType) As Token
            Dim t As New Token(Me.StartPos, Me.EndPos)
            t.Type = type
            Return t
        End Function

        ''' <summary>
        ''' executes a lookahead of the next token
        ''' and will advance the scan on the input string
        ''' </summary>
        ''' <returns></returns>
        Public Function Scan(ByVal ParamArray expectedtokens As TokenType()) As Token
            Dim tok As Token = LookAhead(expectedtokens)
            ' temporarely retrieve the lookahead
            LookAheadToken = Nothing
            ' reset lookahead token, so scanning will continue
            StartPos = tok.EndPos
            EndPos = tok.EndPos
            ' set the tokenizer to the new scan position
            Return tok
        End Function

        ''' <summary>
        ''' returns token with longest best match
        ''' </summary>
        ''' <returns></returns>
        Public Function LookAhead(ByVal ParamArray expectedtokens As TokenType()) As Token
            Dim i As Integer
            Dim start As Integer = StartPos
            Dim tok As Token = Nothing
            Dim scantokens As List(Of TokenType)

            ' this prevents double scanning and matching
            ' increased performance
            If LookAheadToken IsNot Nothing AndAlso LookAheadToken.Type <> TokenType._UNDETERMINED_ AndAlso LookAheadToken.Type <> TokenType._NONE_ Then
                Return LookAheadToken
            End If

            If expectedtokens.Length = 0 Then
                scantokens = Tokens
            Else
                scantokens = New List(Of TokenType)(expectedtokens)
                scantokens.AddRange(SkipList)
            End If

            Do
                Dim len As Integer = -1
                Dim index As TokenType = Integer.MaxValue
                Dim m_input As String

                If start > Input.Length Then
                    tok = New Token(start, start)
                    tok.Type = TokenType._UNDETERMINED_
                    Exit Do
                End If

                m_input = Input.Substring(start)

                tok = New Token(start, EndPos)


                For i = 0 To scantokens.Count - 1
                    Dim r As Regex = Patterns(scantokens(i))
                    Dim m As Match = r.Match(m_input)
                    If m.Success AndAlso m.Index = 0 AndAlso ((m.Length > len) OrElse (scantokens(i) < index AndAlso m.Length = len)) Then
                        len = m.Length
                        index = scantokens(i)
                        Exit For
                    End If
                Next i

                If index >= 0 AndAlso len >= 0 Then
                    tok.EndPos = start + len
                    If tok.StartPos + len <= Input.Length Then
                        tok.Text = Input.Substring(tok.StartPos, len)
                    End If
                    tok.Type = index
                Else
                    If tok.StartPos < tok.EndPos - 1 Then
                        tok.Text = Input.Substring(tok.StartPos, 1)
                    End If
                End If

                If SkipList.Contains(tok.Type) Then
                    start = tok.EndPos
                    Skipped.Add(tok)
                Else
                    tok.Skipped = Skipped
                    Skipped = New List(Of Token)
                End If
            Loop While SkipList.Contains(tok.Type)

            LookAheadToken = tok
            Return tok
        End Function
    End Class
#End Region

#Region "Token"

    Public Enum TokenType

        'Non terminal tokens:
        _NONE_      = 0
        _UNDETERMINED_= 1

        'Non terminal tokens:
        NATURALLANGUAGEPROMPT= 2
        BINARYFACTTYPEATMOSTONECLAUSE= 3
        BINARYFACTTYPEMANYTOONEDEFINITIONCLAUSE= 4
        BINARYPREDICATECLAUSE= 5
        DATATYPE    = 6
        DATATYPELENGTH= 7
        DATATYPEPRECISION= 8
        ENTITYTYPEISIDENTIFIEDBYITSCLAUSE= 9
        FACTTYPECLAUSE= 10
        FRONTREADINGTEXTCLAUSE= 11
        ISACONCEPTCLAUSE= 12
        ISANENTITYTYPECLAUSE= 13
        MODELELEMENT= 14
        PREDICATECLAUSE= 15
        UNARYPREDICATECLAUSE= 16
        VALUETYPEISWRITTENASCLAUSE= 17
        FACTREADINGSTMT= 18
        MODELELEMENTLEADINGSTMT= 19
        BASEPRODUCTION= 20
        Start       = 21

        'Terminal tokens:
        BROPEN      = 22
        BRCLOSE     = 23
        COLON       = 24
        COLUMNNAMESTR= 25
        COMMA       = 26
        CURLYBRACKETCLOSE= 27
        CURLYBRACKETOPEN= 28
        DOUBLEQUOTE = 29
        EOF         = 30
        EQUALS      = 31
        FACTTYPENAME= 32
        FOLLOWINGREADINGTEXT= 33
        FRONTREADINGTEXT= 34
        ID          = 35
        MULTDIV     = 36
        MODELNAME   = 37
        MODELELEMENTNAME= 38
        MODELID     = 39
        NUMBER      = 40
        PAGENAME    = 41
        PLUSMINUS   = 42
        POSTBOUNDREADINGTEXT= 43
        PREBOUNDREADINGTEXT= 44
        PREDICATEPART= 45
        PREDICATESPACE= 46
        REFERENCEMODE= 47
        ROLENAME    = 48
        SINGLEQUOTE = 49
        STAR        = 50
        SPACE       = 51
        UNARYPREDICATEPART= 52
        USERTABLENAME= 53
        WHERECLAUSECOLUMNNAMESTR= 54
        VALUE       = 55
        KEYWDATMOSTONE= 56
        KEYWDDATATYPELOGICALTRUEFALSE= 57
        KEYWDDATATYPELOGICALYESNO= 58
        KEYWDDATATYPEAUTOCOUNTER= 59
        KEYWDDATATYPEDECIMAL= 60
        KEYWDDATATYPEFLOATCUSTOMPRECISION= 61
        KEYWDDATATYPEFLOATDOUBLEPRECISION= 62
        KEYWDDATATYPEFLOATSINGLEPRECISION= 63
        KEYWDDATATYPEMONEY= 64
        KEYWDDATATYPESIGNEDBIGINTEGER= 65
        KEYWDDATATYPESIGNEDINTEGER= 66
        KEYWDDATATYPESIGNEDSMALLINTEGER= 67
        KEYWDDATATYPEUNSIGNEDBIGINTEGER= 68
        KEYWDDATATYPEUNSIGNEDINTEGER= 69
        KEYWDDATATYPEUNSIGNEDSMALLINTEGER= 70
        KEYWDDATATYPEUNSIGNEDTINYINTEGER= 71
        KEYWDDATATYPEOBJECTID= 72
        KEYWDDATATYPEROWID= 73
        KEYWDDATATYPERAWDATAFIXEDLENGTH= 74
        KEYWDDATATYPERAWDATALARGELENGTH= 75
        KEYWDDATATYPERAWDATAOLEOBJECT= 76
        KEYWDDATATYPERAWDATA= 77
        KEYWDDATATYPERAWDATAVARIABLELENGTH= 78
        KEYWDDATATYPEAUTOTIMESTAMP= 79
        KEYWDDATATYPEDATE= 80
        KEYWDDATATYPEDATETIME= 81
        KEYWDDATATYPETIME= 82
        KEYWDDATATYPESTRINGFIXEDLENGTH= 83
        KEYWDDATATYPESTRINGLARGELENGTH= 84
        KEYWDDATATYPESTRINGVARIABLELENGTH= 85
        KEYWDISACONCEPT= 86
        KEYWDISANENTITYTYPE= 87
        KEYWDISIDENTIFIEDBYITS= 88
        KEYWDISWRITTENAS= 89
        KEYWDNL     = 90
        KEYWDONE    = 91
        KEYWDREADING= 92
        WHITESPACE  = 93
    End Enum

    <Serializable()> _
    Public Class Token 
        Private m_startPos As Integer
        Private m_endPos As Integer
        Private m_text As String
        Private m_value As Object

        ' contains all prior skipped symbols
        Private m_skipped As List(Of Token)


        Public Property StartPos() As Integer
            Get
                Return m_startPos
            End Get
            Set(ByVal value As Integer)
                m_startPos = value
            End Set
        End Property

        Public Property EndPos() As Integer
            Get
                Return m_endPos
            End Get
            Set(ByVal value As Integer)
                m_endPos = value
            End Set
        End Property

        Public ReadOnly Property Length() As Integer
            Get
                Return m_endPos - m_startPos
            End Get
        End Property

        Public Property Text() As String
            Get
                Return m_text
            End Get
            Set(ByVal value As String)
                m_text = value
            End Set
        End Property

        Public Property Skipped() As List(Of Token)
            Get
                Return m_skipped
            End Get
            Set(ByVal value As List(Of Token))
                m_skipped = value
            End Set
        End Property

        Public Property Value() As Object
            Get
                Return m_value
            End Get
            Set(ByVal value As Object)
                Me.m_value = value
            End Set
        End Property

        <XmlAttribute()> _
        Public Type As TokenType

        Public Sub New()
            Me.New(0, 0)
        End Sub

        Public Sub New(ByVal start As Integer, ByVal endPos As Integer)
            Type = TokenType._UNDETERMINED_
            m_startPos = start
            m_endPos = endPos
            Text = ""
            ' must initialize with empty string, may cause null reference exceptions otherwise
            Value = Nothing
        End Sub

        Public Sub UpdateRange(ByVal token As Token)
            If token.StartPos < m_startPos Then
                m_startPos = token.StartPos
            End If
            If token.EndPos > m_endPos Then
                m_endPos = token.EndPos
            End If
        End Sub

        Public Overloads Overrides Function ToString() As String
            If Text <> Nothing Then
                Return Type.ToString() + " '" + Text + "'"
            Else
                Return Type.ToString()
            End If
        End Function
    End Class
#End Region
End Namespace
