Public Module publicConstantsFBM

    <Serializable()>
    Public Enum pcenumLanguage
        ORMModel = 1
        UMLUseCaseDiagram = 2
        BusinessRulesNaturalLanguage = 3 'English (see Italian below...may need to change this. We ClassBrain for more information about natural language processing).
        ZNotation = 4
        FlowChart = 6
        DataFlowDiagram = 8
        EntityRelationshipDiagram = 9
        PropertyGraphSchema = 22
        StateTransitionDiagram = 10
        BPMNChoreographDiagram = 11
        CMML = 12 'Used for cloning UML.Process objects to UCD.Process objects etc.
        BPMNConversationDiagram = 13
        BPMNCollaborationDiagram = 14
        BPMNProcessDigram = 15
        GenericDiagram = 16 'Just stores the XML generated by Mindfusion Diagram.
        StructureChart = 17 'Stores the XML generated by Mindfusion Diagram.
    End Enum

    <Serializable()>
    Public Enum pcenumConceptInstanceFlag
        EntityTypeHideReferenceMode = 1
    End Enum

    <Serializable()>
    Public Enum pcenumJoinPathError
        None
        CircularPathFound
        AmbiguousJoinPath
        RidiculousDepth
        DoubledBackToExistingArgumentRole
        DoubledBackToCoveredRole
    End Enum

    Public Enum pcenumModelFixType
        AddCoreModel
        ColumnOrdinalPositionsResetWhereOutOfSynchronousOrder
        ColumnsWhereActiveRoleIsNothingTryAndFix
        ColumnsWhereActiveRoleIsNothingRemoveTheColumn
        ColumnsWhereNoLongerPartOfSupertypeHierarchyRemoveColumn
        DuplicateFactsRemoveDuplicates
        InternalUniquenessConstraintsWhereLevelNumbersAreNotCorrect
        ObjectifyingEntitTypeIdsNotTheSameAsObjectifiedFactType
        ObjectifiedFactTypesWithNoCorrespondingRDSTable
        RemoveFactTypeInstancesFromPageWhereFactTypeIntanceHasRoleInstanceThatJoinsNothing
        RolesWithoutJoinedORMObject
        RDSColumnsThatShouldBeMandatoryMakeMandatory
        RDSColumnsWithoutActiveRoles
        RDSRelationsMissing
        RDSRelationsInvalidActiveRoleOnOriginColumns
        RDSRelationsThatHaveNoOriginColumnsRemoveRelation
        RDSRelationsThatHaveOriginTableButNoDestinationTableAndViceVersa
        RDSRelationsThatHaveWrongResponsibleFactType
        RDSRelationsThatHaveZeroOriginColumnsAndZeroDestinationColumns
        RDSRelationsWhereOriginColumnCountNotEqualDestinationColumnCount
        RDSRelationsWhereMultiplicityCardinalitiesDoNotMatchResponsibleFactTypeInternalUniquenessConstraints
        RDSRelationsWhereOriginColumnHasWrongTable
        RDSTablesAndPGSNodesThatAreMissingRelationsAddTheRelations 'Missing Relations
        RDSTablesWithMissingBooleanColumns
        RDSTablesWithMoreThanOneRelationForTheSameFactTypeJoinPruneExtraRelations
        RDSTablesWithNoColumnsRemoveThoseTables
        RDSTablesWithSimpleReferenceSchemeAndMultiplePrimaryKeyColumns
        RDSTablesWhereColumnAppearsTwiceForSameFactType
        RDSTablesWhereTheNumberOfPrimaryKeyColumnsDoesNotMatchTheNumberOfRolesInThePreferredIdentifierFixThat
        SubtypeRelationshipWithNoFactType
    End Enum

    Public Enum pcenumDerivationSyntaxType
        FactEngine = 1
        nORMa = 2
    End Enum

End Module
