' Generated by TinyPG v1.3 available at www.codeproject.com

Imports System
Imports System.Collections.Generic
Imports System.Text
Imports System.Xml.Serialization


Namespace TinyPG
#Region "ParseTree"
    <Serializable()> _
    Public Class ParseErrors
        Inherits List(Of ParseError)

        Public Sub New()

        End Sub
    End Class

    <Serializable()> _
    Public Class ParseError 
        Private m_message As String
        Private m_code As Integer
        Private m_line As Integer
        Private m_col As Integer
        Private m_pos As Integer
        Private m_length As Integer
        Private m_expected_token As String = ""

        Public ReadOnly Property Code() As Integer
            Get
                Return m_code
            End Get
        End Property

        Public ReadOnly Property Line() As Integer
            Get
                Return m_line
            End Get
        End Property

        Public ReadOnly Property Column() As Integer
            Get
                Return m_col
            End Get
        End Property

        Public ReadOnly Property Position() As Integer
            Get
                Return m_pos
            End Get
        End Property

        Public ReadOnly Property Length() As Integer
            Get
                Return m_length
            End Get
        End Property

        Public ReadOnly Property Message() As String
            Get
                Return m_message
            End Get
        End Property

        Public Property ExpectedToken as String
            Get
                Return me.m_expected_token
            End Get
            Set(ByVal value As String)
                me.m_expected_token = value
            End Set
        End Property

        Public Sub New(ByVal message As String, ByVal code As Integer, ByVal node As ParseNode)
            Me.New(message, code, 0, node.Token.StartPos, node.Token.StartPos, node.Token.Length)
        End Sub

        Public Sub New(ByVal message As String, ByVal code As Integer, ByVal line As Integer, ByVal col As Integer, ByVal pos As Integer, ByVal length As Integer, Optional ByVal asExpectedToken as String = "")
            m_message = message
            m_code = code
            m_line = line
            m_col = col
            m_pos = pos
            m_length = length
	    m_expected_token = asExpectedToken
        End Sub
    End Class

    ' rootlevel of the node tree
    <Serializable()> _
    Partial Public Class ParseTree
        Inherits ParseNode

        Public Errors As ParseErrors
	Public Optionals As ParseErrors

        Public Skipped As List(Of Token)

        Public Sub New()
            MyBase.New(New Token(), "ParseTree")
            Token.Type = TokenType.Start
            Token.Text = "Root"
            Skipped = New List(Of Token)()
            Errors = New ParseErrors()
	    Optionals = New ParseErrors()
        End Sub

        Public Function PrintTree() As String
    Dim sb As New StringBuilder()
    Dim indent As Integer = 0
            PrintNode(sb, Me, indent)
            Return sb.ToString()
        End Function

    Private Sub PrintNode(ByVal sb As StringBuilder, ByVal node As ParseNode, ByVal indent As Integer)

        Dim space As String = "".PadLeft(indent, " "c)

        sb.Append(space)
        sb.AppendLine(node.Text)

        For Each n As ParseNode In node.Nodes
            PrintNode(sb, n, indent + 2)
        Next
    End Sub

    ''' <summary>
    ''' this is the entry point for executing and evaluating the parse tree.
    ''' </summary>
    ''' <param name="paramlist">additional optional input parameters</param>
    ''' <returns>the output of the evaluation function</returns>
    Public Overloads Function Eval(ByVal ParamArray paramlist As Object()) As Object
        Return Nodes(0).Eval(Me, paramlist)
    End Function
    End Class
#End Region

#Region "ParseNode"
    <Serializable()> _
    Partial Public Class ParseNode 
        Protected m_text As String
        Protected m_nodes As List(Of ParseNode)
        

        Public ReadOnly Property Nodes() As List(Of ParseNode)
            Get
                Return m_nodes
            End Get
        End Property

        
        <XMLIgnore()> _
        Public Parent As ParseNode
        Public Token As Token
        ' the token/rule
        <XmlIgnore()> _
        Public Property Text() As String
            ' text to display in parse tree 
            Get
                Return m_text
            End Get
            Set(ByVal value As String)
                m_text = value
            End Set
        End Property

	Public Sub New()

	End Sub 

        Public Overridable Function CreateNode(ByVal token As Token, ByVal text As String) As ParseNode
            Dim node As New ParseNode(token, text)
            node.Parent = Me
            Return node
        End Function

        Protected Sub New(ByVal token As Token, ByVal text As String)
            Me.Token = token
            m_text = text
            m_nodes = New List(Of ParseNode)()
        End Sub

        Protected Function GetValue(ByVal tree As ParseTree, ByVal type As TokenType, ByVal index As Integer) As Object
            Return GetValueByRef(tree, type, index)
        End Function

        Protected Function GetValueByRef(ByVal tree As ParseTree, ByVal type As TokenType, ByRef index As Integer) As Object
            Dim o As Object = Nothing
            If index < 0 Then
                Return o
            End If

            ' left to right
            For Each node As ParseNode In nodes
                If node.Token.Type = type Then
                    System.Math.Max(System.Threading.Interlocked.Decrement(index), index + 1)
                    If index < 0 Then
                        o = node.Eval(tree)
                        Exit For
                    End If
                End If
            Next
            Return o
        End Function

        ''' <summary>
        ''' this implements the evaluation functionality, cannot be used directly
        ''' </summary>
        ''' <param name="tree">the parsetree itself</param>
        ''' <param name="paramlist">optional input parameters</param>
        ''' <returns>a partial result of the evaluation</returns>
        Friend Function Eval(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Dim Value As Object = Nothing

            Select Case Token.Type
                Case TokenType.Atom
                    Value = EvalAtom(tree, paramlist)
                    Exit Select
                Case TokenType.ADDITIONALMODELELEMENT
                    Value = EvalADDITIONALMODELELEMENT(tree, paramlist)
                    Exit Select
                Case TokenType.ADDITIONALCOLUMNNAME
                    Value = EvalADDITIONALCOLUMNNAME(tree, paramlist)
                    Exit Select
                Case TokenType.ADDITIONALCOMPARISON
                    Value = EvalADDITIONALCOMPARISON(tree, paramlist)
                    Exit Select
                Case TokenType.ADDITIONALVALUE
                    Value = EvalADDITIONALVALUE(tree, paramlist)
                    Exit Select
                Case TokenType.BRACKTEDCOLMNLIST
                    Value = EvalBRACKTEDCOLMNLIST(tree, paramlist)
                    Exit Select
                Case TokenType.COLUMNLIST
                    Value = EvalCOLUMNLIST(tree, paramlist)
                    Exit Select
                Case TokenType.COLUMNNAME
                    Value = EvalCOLUMNNAME(tree, paramlist)
                    Exit Select
                Case TokenType.COMPARISON
                    Value = EvalCOMPARISON(tree, paramlist)
                    Exit Select
                Case TokenType.COMPARISONLIST
                    Value = EvalCOMPARISONLIST(tree, paramlist)
                    Exit Select
                Case TokenType.FACTREADING
                    Value = EvalFACTREADING(tree, paramlist)
                    Exit Select
                Case TokenType.FACTTYPENAMESTR
                    Value = EvalFACTTYPENAMESTR(tree, paramlist)
                    Exit Select
                Case TokenType.INSERTCOLUMNLIST
                    Value = EvalINSERTCOLUMNLIST(tree, paramlist)
                    Exit Select
                Case TokenType.MODELELEMENT
                    Value = EvalMODELELEMENT(tree, paramlist)
                    Exit Select
                Case TokenType.MODELELEMENTSTR
                    Value = EvalMODELELEMENTSTR(tree, paramlist)
                    Exit Select
                Case TokenType.MODELMODELELEMENT
                    Value = EvalMODELMODELELEMENT(tree, paramlist)
                    Exit Select
                Case TokenType.ROLENAMESTR
                    Value = EvalROLENAMESTR(tree, paramlist)
                    Exit Select
                Case TokenType.VALUELIST
                    Value = EvalVALUELIST(tree, paramlist)
                    Exit Select
                Case TokenType.VALUESTRING
                    Value = EvalVALUESTRING(tree, paramlist)
                    Exit Select
                Case TokenType.ADDENTITYTYPESTMT
                    Value = EvalADDENTITYTYPESTMT(tree, paramlist)
                    Exit Select
                Case TokenType.ADDFACTSTMT
                    Value = EvalADDFACTSTMT(tree, paramlist)
                    Exit Select
                Case TokenType.ADDFACTTYPESTMT
                    Value = EvalADDFACTTYPESTMT(tree, paramlist)
                    Exit Select
                Case TokenType.ADDROLESTMT
                    Value = EvalADDROLESTMT(tree, paramlist)
                    Exit Select
                Case TokenType.ADDMODELELEMENTSTMT
                    Value = EvalADDMODELELEMENTSTMT(tree, paramlist)
                    Exit Select
                Case TokenType.ADDVALUETYPESTMT
                    Value = EvalADDVALUETYPESTMT(tree, paramlist)
                    Exit Select
                Case TokenType.CREATECONCEPTSTMT
                    Value = EvalCREATECONCEPTSTMT(tree, paramlist)
                    Exit Select
                Case TokenType.CREATEENTITYTYPESTMT
                    Value = EvalCREATEENTITYTYPESTMT(tree, paramlist)
                    Exit Select
                Case TokenType.CREATEFACTTYPESTMT
                    Value = EvalCREATEFACTTYPESTMT(tree, paramlist)
                    Exit Select
                Case TokenType.CREATEMODELSTMT
                    Value = EvalCREATEMODELSTMT(tree, paramlist)
                    Exit Select
                Case TokenType.CREATEMODELELEMENTSTMT
                    Value = EvalCREATEMODELELEMENTSTMT(tree, paramlist)
                    Exit Select
                Case TokenType.CREATEVALUETYPESTMT
                    Value = EvalCREATEVALUETYPESTMT(tree, paramlist)
                    Exit Select
                Case TokenType.DELETESTMT
                    Value = EvalDELETESTMT(tree, paramlist)
                    Exit Select
                Case TokenType.DELETEALLSTMT
                    Value = EvalDELETEALLSTMT(tree, paramlist)
                    Exit Select
                Case TokenType.DELETEFACTSTMT
                    Value = EvalDELETEFACTSTMT(tree, paramlist)
                    Exit Select
                Case TokenType.EXISTSSTMT
                    Value = EvalEXISTSSTMT(tree, paramlist)
                    Exit Select
                Case TokenType.EXTENDINGROLECONSTRAINTCLAUSE
                    Value = EvalEXTENDINGROLECONSTRAINTCLAUSE(tree, paramlist)
                    Exit Select
                Case TokenType.EXTENDROLECONSTRAINTSTMT
                    Value = EvalEXTENDROLECONSTRAINTSTMT(tree, paramlist)
                    Exit Select
                Case TokenType.EXTERNALUNIQUENESSCONSTRAINTSTMT
                    Value = EvalEXTERNALUNIQUENESSCONSTRAINTSTMT(tree, paramlist)
                    Exit Select
                Case TokenType.FACTTYPESTMT
                    Value = EvalFACTTYPESTMT(tree, paramlist)
                    Exit Select
                Case TokenType.GETSUPERTYPESTMT
                    Value = EvalGETSUPERTYPESTMT(tree, paramlist)
                    Exit Select
                Case TokenType.INMODELSTMT
                    Value = EvalINMODELSTMT(tree, paramlist)
                    Exit Select
                Case TokenType.INSERTSTMT
                    Value = EvalINSERTSTMT(tree, paramlist)
                    Exit Select
                Case TokenType.ITISMANDATORYTHATSTMNT
                    Value = EvalITISMANDATORYTHATSTMNT(tree, paramlist)
                    Exit Select
                Case TokenType.ONMODELCLAUSE
                    Value = EvalONMODELCLAUSE(tree, paramlist)
                    Exit Select
                Case TokenType.ONPAGESTMT
                    Value = EvalONPAGESTMT(tree, paramlist)
                    Exit Select
                Case TokenType.OPENMODELSTMT
                    Value = EvalOPENMODELSTMT(tree, paramlist)
                    Exit Select
                Case TokenType.REMOVEINSTANCESTMT
                    Value = EvalREMOVEINSTANCESTMT(tree, paramlist)
                    Exit Select
                Case TokenType.RENAMEINSTANCESTMT
                    Value = EvalRENAMEINSTANCESTMT(tree, paramlist)
                    Exit Select
                Case TokenType.SELECTSTMT
                    Value = EvalSELECTSTMT(tree, paramlist)
                    Exit Select
                Case TokenType.UPDATESTMT
                    Value = EvalUPDATESTMT(tree, paramlist)
                    Exit Select
                Case TokenType.WHERESTMT
                    Value = EvalWHERESTMT(tree, paramlist)
                    Exit Select
                Case TokenType.WITHPREDICATESTMT
                    Value = EvalWITHPREDICATESTMT(tree, paramlist)
                    Exit Select
                Case TokenType.Start
                    Value = EvalStart(tree, paramlist)
                    Exit Select

                Case Else
                    Value = Token.Text
                    Exit Select
            End Select
            Return Value
        End Function

        Protected Overridable Function EvalAtom(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalADDITIONALMODELELEMENT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalADDITIONALCOLUMNNAME(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalADDITIONALCOMPARISON(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalADDITIONALVALUE(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalBRACKTEDCOLMNLIST(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalCOLUMNLIST(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalCOLUMNNAME(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalCOMPARISON(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalCOMPARISONLIST(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalFACTREADING(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalFACTTYPENAMESTR(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalINSERTCOLUMNLIST(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalMODELELEMENT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalMODELELEMENTSTR(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalMODELMODELELEMENT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalROLENAMESTR(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalVALUELIST(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalVALUESTRING(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalADDENTITYTYPESTMT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalADDFACTSTMT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalADDFACTTYPESTMT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalADDROLESTMT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalADDMODELELEMENTSTMT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalADDVALUETYPESTMT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalCREATECONCEPTSTMT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalCREATEENTITYTYPESTMT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalCREATEFACTTYPESTMT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalCREATEMODELSTMT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalCREATEMODELELEMENTSTMT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalCREATEVALUETYPESTMT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalDELETESTMT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalDELETEALLSTMT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalDELETEFACTSTMT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalEXISTSSTMT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalEXTENDINGROLECONSTRAINTCLAUSE(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalEXTENDROLECONSTRAINTSTMT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalEXTERNALUNIQUENESSCONSTRAINTSTMT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalFACTTYPESTMT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalGETSUPERTYPESTMT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalINMODELSTMT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalINSERTSTMT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalITISMANDATORYTHATSTMNT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalONMODELCLAUSE(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalONPAGESTMT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalOPENMODELSTMT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalREMOVEINSTANCESTMT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalRENAMEINSTANCESTMT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalSELECTSTMT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalUPDATESTMT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalWHERESTMT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalWITHPREDICATESTMT(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalStart(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Return "Could not interpret input; no semantics implemented."
        End Function



    End Class
#End Region
End Namespace

