' Generated by TinyPG v1.3 available at www.codeproject.com

Imports System
Imports System.Collections.Generic
Imports System.Text.RegularExpressions
Imports System.Xml.Serialization


Namespace TinyPG
#Region "Scanner"

    Partial Public Class Scanner
        Public Input As String
        Public StartPos As Integer = 0
        Public EndPos As Integer = 0
        Public CurrentLine As Integer
        Public CurrentColumn As Integer
        Public CurrentPosition As Integer
        Public Skipped As List(Of Token) ' tokens that were skipped
        Public Patterns As Dictionary(Of TokenType, Regex)

        Private LookAheadToken As Token
        Private Tokens As List(Of TokenType)
        Private SkipList As List(Of TokenType) ' tokens to be skipped

        Public Sub New()
            Dim regex As Regex
            Patterns = New Dictionary(Of TokenType, Regex)()
            Tokens = New List(Of TokenType)()
            LookAheadToken = Nothing
            Skipped = New List(Of Token)()

            SkipList = New List(Of TokenType)()
            SkipList.Add(TokenType.WHITESPACE)

            regex = new Regex("\(+", RegexOptions.Compiled)
            Patterns.Add(TokenType.BROPEN, regex)
            Tokens.Add(TokenType.BROPEN)

            regex = new Regex("\)+", RegexOptions.Compiled)
            Patterns.Add(TokenType.BRCLOSE, regex)
            Tokens.Add(TokenType.BRCLOSE)

            regex = new Regex("[aA-zZ0-9]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.COLUMNNAMESTR, regex)
            Tokens.Add(TokenType.COLUMNNAMESTR)

            regex = new Regex(",", RegexOptions.Compiled)
            Patterns.Add(TokenType.COMMA, regex)
            Tokens.Add(TokenType.COMMA)

            regex = new Regex("""", RegexOptions.Compiled)
            Patterns.Add(TokenType.DOUBLEQUOTE, regex)
            Tokens.Add(TokenType.DOUBLEQUOTE)

            regex = new Regex("^$", RegexOptions.Compiled)
            Patterns.Add(TokenType.EOF, regex)
            Tokens.Add(TokenType.EOF)

            regex = new Regex("=", RegexOptions.Compiled)
            Patterns.Add(TokenType.EQUALS, regex)
            Tokens.Add(TokenType.EQUALS)

            regex = new Regex("[aA-zZ]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.FACTTYPENAME, regex)
            Tokens.Add(TokenType.FACTTYPENAME)

            regex = new Regex("\*|/", RegexOptions.Compiled)
            Patterns.Add(TokenType.MULTDIV, regex)
            Tokens.Add(TokenType.MULTDIV)

            regex = new Regex("[aA-zZ]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.MODELNAME, regex)
            Tokens.Add(TokenType.MODELNAME)

            regex = new Regex("[A-Z0-9][a-z0-9]+([_|\sA-Z0-9][a-z0-9]+)*", RegexOptions.Compiled)
            Patterns.Add(TokenType.MODELELEMENTNAME, regex)
            Tokens.Add(TokenType.MODELELEMENTNAME)

            regex = new Regex("[aA-zZ0-9\-]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.MODELID, regex)
            Tokens.Add(TokenType.MODELID)

            regex = new Regex("[0-9]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.NUMBER, regex)
            Tokens.Add(TokenType.NUMBER)

            regex = new Regex("[aA-zZ0-9\.\s\-]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.PAGENAME, regex)
            Tokens.Add(TokenType.PAGENAME)

            regex = new Regex("(\+|-)", RegexOptions.Compiled)
            Patterns.Add(TokenType.PLUSMINUS, regex)
            Tokens.Add(TokenType.PLUSMINUS)

            regex = new Regex("[a-z\s]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.PREDICATE, regex)
            Tokens.Add(TokenType.PREDICATE)

            regex = new Regex("[aA-zZ]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.ROLENAME, regex)
            Tokens.Add(TokenType.ROLENAME)

            regex = new Regex("'", RegexOptions.Compiled)
            Patterns.Add(TokenType.SINGLEQUOTE, regex)
            Tokens.Add(TokenType.SINGLEQUOTE)

            regex = new Regex("\*", RegexOptions.Compiled)
            Patterns.Add(TokenType.STAR, regex)
            Tokens.Add(TokenType.STAR)

            regex = new Regex("[aA-zZ0-9]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.USERTABLENAME, regex)
            Tokens.Add(TokenType.USERTABLENAME)

            regex = new Regex("[aA-zZ0-9]+", RegexOptions.Compiled)
            Patterns.Add(TokenType.WHERECLAUSECOLUMNNAMESTR, regex)
            Tokens.Add(TokenType.WHERECLAUSECOLUMNNAMESTR)

            regex = new Regex("[aA-zZ0-9,\-\s+\#\*\?]*", RegexOptions.Compiled)
            Patterns.Add(TokenType.VALUE, regex)
            Tokens.Add(TokenType.VALUE)

            regex = new Regex("ADD", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDADD, regex)
            Tokens.Add(TokenType.KEYWDADD)

            regex = new Regex("ADD FACT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDADDFACT, regex)
            Tokens.Add(TokenType.KEYWDADDFACT)

            regex = new Regex("ADD FACTTYPE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDADDFACTTYPE, regex)
            Tokens.Add(TokenType.KEYWDADDFACTTYPE)

            regex = new Regex("AND", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDAND, regex)
            Tokens.Add(TokenType.KEYWDAND)

            regex = new Regex("AT MOST ONE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDATMOSTONE, regex)
            Tokens.Add(TokenType.KEYWDATMOSTONE)

            regex = new Regex("COUNT\(\*\)", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDCOUNTSTAR, regex)
            Tokens.Add(TokenType.KEYWDCOUNTSTAR)

            regex = new Regex("CREATE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDCREATE, regex)
            Tokens.Add(TokenType.KEYWDCREATE)

            regex = new Regex("CREATE CONCEPT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDCREATECONCEPT, regex)
            Tokens.Add(TokenType.KEYWDCREATECONCEPT)

            regex = new Regex("CREATE ENTITYTTYPE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDCREATEENTITYTYPE, regex)
            Tokens.Add(TokenType.KEYWDCREATEENTITYTYPE)

            regex = new Regex("CREATE FACTTYPE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDCREATEFACTTYPE, regex)
            Tokens.Add(TokenType.KEYWDCREATEFACTTYPE)

            regex = new Regex("CREATE MODEL", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDCREATEMODEL, regex)
            Tokens.Add(TokenType.KEYWDCREATEMODEL)

            regex = new Regex("CREATE VALUETYPE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDCREATEVALUETYPE, regex)
            Tokens.Add(TokenType.KEYWDCREATEVALUETYPE)

            regex = new Regex("DELETE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDELETE, regex)
            Tokens.Add(TokenType.KEYWDDELETE)

            regex = new Regex("DELETE ALL", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDELETEALL, regex)
            Tokens.Add(TokenType.KEYWDDELETEALL)

            regex = new Regex("DELETE FACT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDELETEFACT, regex)
            Tokens.Add(TokenType.KEYWDDELETEFACT)

            regex = new Regex("DISTINCT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDDISTINCT, regex)
            Tokens.Add(TokenType.KEYWDDISTINCT)

            regex = new Regex("ENTITY", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDENTITY, regex)
            Tokens.Add(TokenType.KEYWDENTITY)

            regex = new Regex("ENTITYTYPE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDENTITYTYPE, regex)
            Tokens.Add(TokenType.KEYWDENTITYTYPE)

            regex = new Regex("EXISTS", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDEXISTS, regex)
            Tokens.Add(TokenType.KEYWDEXISTS)

            regex = new Regex("EXTEND", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDEXTEND, regex)
            Tokens.Add(TokenType.KEYWDEXTEND)

            regex = new Regex("EXTENDING", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDEXTENDING, regex)
            Tokens.Add(TokenType.KEYWDEXTENDING)

            regex = new Regex("FACT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDFACT, regex)
            Tokens.Add(TokenType.KEYWDFACT)

            regex = new Regex("FACTTYPE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDFACTTYPE, regex)
            Tokens.Add(TokenType.KEYWDFACTTYPE)

            regex = new Regex("FOR", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDFOR, regex)
            Tokens.Add(TokenType.KEYWDFOR)

            regex = new Regex("FOR EACH", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDFOREACH, regex)
            Tokens.Add(TokenType.KEYWDFOREACH)

            regex = new Regex("FROM", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDFROM, regex)
            Tokens.Add(TokenType.KEYWDFROM)

            regex = new Regex("IN", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDIN, regex)
            Tokens.Add(TokenType.KEYWDIN)

            regex = new Regex("INSERT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDINSERT, regex)
            Tokens.Add(TokenType.KEYWDINSERT)

            regex = new Regex("INTO", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDINTO, regex)
            Tokens.Add(TokenType.KEYWDINTO)

            regex = new Regex("IT IS MANDATORY THAT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDITISMANDATORYTHAT, regex)
            Tokens.Add(TokenType.KEYWDITISMANDATORYTHAT)

            regex = new Regex("JOINING", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDJOINING, regex)
            Tokens.Add(TokenType.KEYWDJOINING)

            regex = new Regex("GET", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDGET, regex)
            Tokens.Add(TokenType.KEYWDGET)

            regex = new Regex("LANGUAGE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDLANGUAGE, regex)
            Tokens.Add(TokenType.KEYWDLANGUAGE)

            regex = new Regex("DFD", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDLANGUAGEDFD, regex)
            Tokens.Add(TokenType.KEYWDLANGUAGEDFD)

            regex = new Regex("ERD", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDLANGUAGEERD, regex)
            Tokens.Add(TokenType.KEYWDLANGUAGEERD)

            regex = new Regex("ETD", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDLANGUAGEETD, regex)
            Tokens.Add(TokenType.KEYWDLANGUAGEETD)

            regex = new Regex("ORM", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDLANGUAGEORM, regex)
            Tokens.Add(TokenType.KEYWDLANGUAGEORM)

            regex = new Regex("STD", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDLANGUAGESTD, regex)
            Tokens.Add(TokenType.KEYWDLANGUAGESTD)

            regex = new Regex("UCD", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDLANGUAGEUCD, regex)
            Tokens.Add(TokenType.KEYWDLANGUAGEUCD)

            regex = new Regex("MODEL", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDMODEL, regex)
            Tokens.Add(TokenType.KEYWDMODEL)

            regex = new Regex("MODEL.DICTIONARY", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDMODELDICTIONARY, regex)
            Tokens.Add(TokenType.KEYWDMODELDICTIONARY)

            regex = new Regex("OBJECT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDOBJECT, regex)
            Tokens.Add(TokenType.KEYWDOBJECT)

            regex = new Regex("OF", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDOF, regex)
            Tokens.Add(TokenType.KEYWDOF)

            regex = new Regex("ON", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDON, regex)
            Tokens.Add(TokenType.KEYWDON)

            regex = new Regex("ON PAGE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDONPAGE, regex)
            Tokens.Add(TokenType.KEYWDONPAGE)

            regex = new Regex("OPEN", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDOPEN, regex)
            Tokens.Add(TokenType.KEYWDOPEN)

            regex = new Regex("PAGE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDPAGE, regex)
            Tokens.Add(TokenType.KEYWDPAGE)

            regex = new Regex("PREDICATE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDPREDICATE, regex)
            Tokens.Add(TokenType.KEYWDPREDICATE)

            regex = new Regex("REMOVE INSTANCE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDREMOVEINSTANCE, regex)
            Tokens.Add(TokenType.KEYWDREMOVEINSTANCE)

            regex = new Regex("REMOVE MODELELEMENT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDREMOVEMODELELEMENT, regex)
            Tokens.Add(TokenType.KEYWDREMOVEMODELELEMENT)

            regex = new Regex("RENAME INSTANCE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDRENAMEINSTANCE, regex)
            Tokens.Add(TokenType.KEYWDRENAMEINSTANCE)

            regex = new Regex("ROLE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDROLE, regex)
            Tokens.Add(TokenType.KEYWDROLE)

            regex = new Regex("ROLECONSTRAINT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDROLECONSTRAINT, regex)
            Tokens.Add(TokenType.KEYWDROLECONSTRAINT)

            regex = new Regex("SELECT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDSELECT, regex)
            Tokens.Add(TokenType.KEYWDSELECT)

            regex = new Regex("SET", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDSET, regex)
            Tokens.Add(TokenType.KEYWDSET)

            regex = new Regex("SUPERTYPE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDSUPERTYPE, regex)
            Tokens.Add(TokenType.KEYWDSUPERTYPE)

            regex = new Regex("THAT", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDTHAT, regex)
            Tokens.Add(TokenType.KEYWDTHAT)

            regex = new Regex("TO", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDTO, regex)
            Tokens.Add(TokenType.KEYWDTO)

            regex = new Regex("UPDATE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDUPDATE, regex)
            Tokens.Add(TokenType.KEYWDUPDATE)

            regex = new Regex("VALUES", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDVALUES, regex)
            Tokens.Add(TokenType.KEYWDVALUES)

            regex = new Regex("VALUETYPE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDVALUETYPE, regex)
            Tokens.Add(TokenType.KEYWDVALUETYPE)

            regex = new Regex("WHERE", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDWHERE, regex)
            Tokens.Add(TokenType.KEYWDWHERE)

            regex = new Regex("WITH", RegexOptions.Compiled)
            Patterns.Add(TokenType.KEYWDWITH, regex)
            Tokens.Add(TokenType.KEYWDWITH)

            regex = new Regex("\s+", RegexOptions.Compiled)
            Patterns.Add(TokenType.WHITESPACE, regex)
            Tokens.Add(TokenType.WHITESPACE)



        End Sub

        Public Sub Init(ByVal input As String)
            Me.Input = input
            StartPos = 0
            EndPos = 0
            CurrentLine = 0
            CurrentColumn = 0
            CurrentPosition = 0
            Skipped = New List(Of Token)()
            LookAheadToken = Nothing
        End Sub

        Public Function GetToken(ByVal type As TokenType) As Token
            Dim t As New Token(Me.StartPos, Me.EndPos)
            t.Type = type
            Return t
        End Function

        ''' <summary>
        ''' executes a lookahead of the next token
        ''' and will advance the scan on the input string
        ''' </summary>
        ''' <returns></returns>
        Public Function Scan(ByVal ParamArray expectedtokens As TokenType()) As Token
            Dim tok As Token = LookAhead(expectedtokens)
            ' temporarely retrieve the lookahead
            LookAheadToken = Nothing
            ' reset lookahead token, so scanning will continue
            StartPos = tok.EndPos
            EndPos = tok.EndPos
            ' set the tokenizer to the new scan position
            Return tok
        End Function

        ''' <summary>
        ''' returns token with longest best match
        ''' </summary>
        ''' <returns></returns>
        Public Function LookAhead(ByVal ParamArray expectedtokens As TokenType()) As Token
            Dim i As Integer
            Dim start As Integer = StartPos
            Dim tok As Token = Nothing
            Dim scantokens As List(Of TokenType)

            ' this prevents double scanning and matching
            ' increased performance
            If LookAheadToken IsNot Nothing AndAlso LookAheadToken.Type <> TokenType._UNDETERMINED_ AndAlso LookAheadToken.Type <> TokenType._NONE_ Then
                Return LookAheadToken
            End If

            If expectedtokens.Length = 0 Then
                scantokens = Tokens
            Else
                scantokens = New List(Of TokenType)(expectedtokens)
                scantokens.AddRange(SkipList)
            End If

            Do
                Dim len As Integer = -1
                Dim index As TokenType = Integer.MaxValue
                Dim m_input As String

                If start > Input.Length Then
                    tok = New Token(start, start)
                    tok.Type = TokenType._UNDETERMINED_
                    Exit Do
                End If

                m_input = Input.Substring(start)

                tok = New Token(start, EndPos)


                For i = 0 To scantokens.Count - 1
                    Dim r As Regex = Patterns(scantokens(i))
                    Dim m As Match = r.Match(m_input)
                    If m.Success AndAlso m.Index = 0 AndAlso ((m.Length > len) OrElse (scantokens(i) < index AndAlso m.Length = len)) Then
                        len = m.Length
                        index = scantokens(i)
                        Exit For
                    End If
                Next i

                If index >= 0 AndAlso len >= 0 Then
                    tok.EndPos = start + len
                    If tok.StartPos + len <= Input.Length Then
                        tok.Text = Input.Substring(tok.StartPos, len)
                    End If
                    tok.Type = index
                Else
                    If tok.StartPos < tok.EndPos - 1 Then
                        tok.Text = Input.Substring(tok.StartPos, 1)
                    End If
                End If

                If SkipList.Contains(tok.Type) Then
                    start = tok.EndPos
                    Skipped.Add(tok)
                Else
                    tok.Skipped = Skipped
                    Skipped = New List(Of Token)
                End If
            Loop While SkipList.Contains(tok.Type)

            LookAheadToken = tok
            Return tok
        End Function
    End Class
#End Region

#Region "Token"

    Public Enum TokenType

        'Non terminal tokens:
        _NONE_      = 0
        _UNDETERMINED_= 1

        'Non terminal tokens:
        Atom        = 2
        ADDITIONALMODELELEMENT= 3
        ADDITIONALCOLUMNNAME= 4
        ADDITIONALCOMPARISON= 5
        ADDITIONALVALUE= 6
        BRACKTEDCOLMNLIST= 7
        COLUMNLIST  = 8
        COLUMNNAME  = 9
        COMPARISON  = 10
        COMPARISONLIST= 11
        FACTREADING = 12
        FACTTYPENAMESTR= 13
        INSERTCOLUMNLIST= 14
        MODELELEMENT= 15
        MODELELEMENTSTR= 16
        MODELMODELELEMENT= 17
        ROLENAMESTR = 18
        VALUELIST   = 19
        VALUESTRING = 20
        ADDENTITYTYPESTMT= 21
        ADDFACTSTMT = 22
        ADDFACTTYPESTMT= 23
        ADDROLESTMT = 24
        ADDMODELELEMENTSTMT= 25
        ADDVALUETYPESTMT= 26
        CREATECONCEPTSTMT= 27
        CREATEENTITYTYPESTMT= 28
        CREATEFACTTYPESTMT= 29
        CREATEMODELSTMT= 30
        CREATEMODELELEMENTSTMT= 31
        CREATEVALUETYPESTMT= 32
        DELETESTMT  = 33
        DELETEALLSTMT= 34
        DELETEFACTSTMT= 35
        EXISTSSTMT  = 36
        EXTENDINGROLECONSTRAINTCLAUSE= 37
        EXTENDROLECONSTRAINTSTMT= 38
        EXTERNALUNIQUENESSCONSTRAINTSTMT= 39
        FACTTYPESTMT= 40
        GETSUPERTYPESTMT= 41
        INMODELSTMT = 42
        INSERTSTMT  = 43
        ITISMANDATORYTHATSTMNT= 44
        ONMODELCLAUSE= 45
        ONPAGESTMT  = 46
        OPENMODELSTMT= 47
        REMOVEINSTANCESTMT= 48
        REMOVEMODELELEMENTSTMT= 49
        RENAMEINSTANCESTMT= 50
        SELECTSTMT  = 51
        UPDATESTMT  = 52
        WHERESTMT   = 53
        WITHPREDICATESTMT= 54
        Start       = 55

        'Terminal tokens:
        BROPEN      = 56
        BRCLOSE     = 57
        COLUMNNAMESTR= 58
        COMMA       = 59
        DOUBLEQUOTE = 60
        EOF         = 61
        EQUALS      = 62
        FACTTYPENAME= 63
        MULTDIV     = 64
        MODELNAME   = 65
        MODELELEMENTNAME= 66
        MODELID     = 67
        NUMBER      = 68
        PAGENAME    = 69
        PLUSMINUS   = 70
        PREDICATE   = 71
        ROLENAME    = 72
        SINGLEQUOTE = 73
        STAR        = 74
        USERTABLENAME= 75
        WHERECLAUSECOLUMNNAMESTR= 76
        VALUE       = 77
        KEYWDADD    = 78
        KEYWDADDFACT= 79
        KEYWDADDFACTTYPE= 80
        KEYWDAND    = 81
        KEYWDATMOSTONE= 82
        KEYWDCOUNTSTAR= 83
        KEYWDCREATE = 84
        KEYWDCREATECONCEPT= 85
        KEYWDCREATEENTITYTYPE= 86
        KEYWDCREATEFACTTYPE= 87
        KEYWDCREATEMODEL= 88
        KEYWDCREATEVALUETYPE= 89
        KEYWDDELETE = 90
        KEYWDDELETEALL= 91
        KEYWDDELETEFACT= 92
        KEYWDDISTINCT= 93
        KEYWDENTITY = 94
        KEYWDENTITYTYPE= 95
        KEYWDEXISTS = 96
        KEYWDEXTEND = 97
        KEYWDEXTENDING= 98
        KEYWDFACT   = 99
        KEYWDFACTTYPE= 100
        KEYWDFOR    = 101
        KEYWDFOREACH= 102
        KEYWDFROM   = 103
        KEYWDIN     = 104
        KEYWDINSERT = 105
        KEYWDINTO   = 106
        KEYWDITISMANDATORYTHAT= 107
        KEYWDJOINING= 108
        KEYWDGET    = 109
        KEYWDLANGUAGE= 110
        KEYWDLANGUAGEDFD= 111
        KEYWDLANGUAGEERD= 112
        KEYWDLANGUAGEETD= 113
        KEYWDLANGUAGEORM= 114
        KEYWDLANGUAGESTD= 115
        KEYWDLANGUAGEUCD= 116
        KEYWDMODEL  = 117
        KEYWDMODELDICTIONARY= 118
        KEYWDOBJECT = 119
        KEYWDOF     = 120
        KEYWDON     = 121
        KEYWDONPAGE = 122
        KEYWDOPEN   = 123
        KEYWDPAGE   = 124
        KEYWDPREDICATE= 125
        KEYWDREMOVEINSTANCE= 126
        KEYWDREMOVEMODELELEMENT= 127
        KEYWDRENAMEINSTANCE= 128
        KEYWDROLE   = 129
        KEYWDROLECONSTRAINT= 130
        KEYWDSELECT = 131
        KEYWDSET    = 132
        KEYWDSUPERTYPE= 133
        KEYWDTHAT   = 134
        KEYWDTO     = 135
        KEYWDUPDATE = 136
        KEYWDVALUES = 137
        KEYWDVALUETYPE= 138
        KEYWDWHERE  = 139
        KEYWDWITH   = 140
        WHITESPACE  = 141
    End Enum

    <Serializable()> _
    Public Class Token 
        Private m_startPos As Integer
        Private m_endPos As Integer
        Private m_text As String
        Private m_value As Object

        ' contains all prior skipped symbols
        Private m_skipped As List(Of Token)


        Public Property StartPos() As Integer
            Get
                Return m_startPos
            End Get
            Set(ByVal value As Integer)
                m_startPos = value
            End Set
        End Property

        Public Property EndPos() As Integer
            Get
                Return m_endPos
            End Get
            Set(ByVal value As Integer)
                m_endPos = value
            End Set
        End Property

        Public ReadOnly Property Length() As Integer
            Get
                Return m_endPos - m_startPos
            End Get
        End Property

        Public Property Text() As String
            Get
                Return m_text
            End Get
            Set(ByVal value As String)
                m_text = value
            End Set
        End Property

        Public Property Skipped() As List(Of Token)
            Get
                Return m_skipped
            End Get
            Set(ByVal value As List(Of Token))
                m_skipped = value
            End Set
        End Property

        Public Property Value() As Object
            Get
                Return m_value
            End Get
            Set(ByVal value As Object)
                Me.m_value = value
            End Set
        End Property

        <XmlAttribute()> _
        Public Type As TokenType

        Public Sub New()
            Me.New(0, 0)
        End Sub

        Public Sub New(ByVal start As Integer, ByVal endPos As Integer)
            Type = TokenType._UNDETERMINED_
            m_startPos = start
            m_endPos = endPos
            Text = ""
            ' must initialize with empty string, may cause null reference exceptions otherwise
            Value = Nothing
        End Sub

        Public Sub UpdateRange(ByVal token As Token)
            If token.StartPos < m_startPos Then
                m_startPos = token.StartPos
            End If
            If token.EndPos > m_endPos Then
                m_endPos = token.EndPos
            End If
        End Sub

        Public Overloads Overrides Function ToString() As String
            If Text <> Nothing Then
                Return Type.ToString() + " '" + Text + "'"
            Else
                Return Type.ToString()
            End If
        End Function
    End Class
#End Region
End Namespace
